_help_back;Exit menu
_help_emulators;Configure available emulators
_help_art_label;The label that identifies this resource (used by Layouts)
_help_art_path;The resource location
_help_art_add;Add a new artwork resource (marquee images, screen shots, etc.)
_help_emu_executable;The full path and name of the emulator executable. $HOME gets replaced with the user's home dir
_help_emu_args;The command line arguments for this emulator.  The following get substituted appropriately: [name], [romext], [rompath], [emulator]
_help_emu_rompath;The path to the roms for this emulator
_help_emu_romext;The rom extension for this emulator (i.e. .zip)
_help_emu_movie_path;The path to attract-mode videos (if any) for this emulator
_help_emu_movie_artwork;The artwork that gets displayed when a movie is not available
_help_emu_catver_file;The full path and name to the catver.ini file for this emulator (used to determine game categories)
_help_emu_listxml;Valid values for XML Mode are "mame" (if this a recent version of mame that provides -listxml output) or "mess <system>" (if this is a recent version of mess that provides -listsoftware output for the specified system).  For any other emulator this should be left empty
_help_emu_gen_romlist;Generate a romlist by searching the configured rom path for roms with the configured extension, incorporating XML and catver.ini information into the generated list if available
_help_emu_delete;Delete the entry for this emulator
_help_emu_sel;Configure emulator
_help_emu_add;Add a new emulator
_help_filter_target;Select the rom characteristic that you wish to filter
_help_filter_comp;Select the comparison type for your filter
_help_filter_value;Select the comparison value for your filter
_help_filter_clear;Clear the filter
_help_list_name;The title of this list
_help_list_layout;The presentation layout to use for this list
_help_list_romlist;The romlist to use for this list
_help_list_filter;The romlist filter for this list
_help_list_delete;Delete this list
_help_list_sel;Configure list
_help_list_add;Add a new list
_help_input_action;
_help_input_delete;Remove this input mapping
_help_input_add;Add a new input mapping
_help_input_sel;Configure input mappings
_help_volume;Valid volume settings are from 0 (mute) to 100 
_help_sound;Assign a sound to this event/action
_help_autorot;Autorotate to match the rotation of the last game played
_help_exit_command;Command to execute when Exit (Confirm) is selected [i.e. "sudo shutdown"]
_help_default_font;The name of the default font to use
_help_font_path;The directories containing fonts (semicolon separates multiple entries)
_help_emulators;Configure emulator settings
_help_lists;Configure display lists
_help_input;Configure input mappings
_help_sound;Configure sound volumes and sound mappings
_help_misc;Configure Miscellaneous settings
