#@中文 (Chinese);win_font=MSYH,YuGothR,MALGUN,ARIALUNI,MSMINCHO;mac_font=AppleMyungjo;linux_font=UnBatang
#
# Interface strings
#
Action;项目
Add a rule to this filter;添加分类规则
Add Artwork;添加插图（Artwork)
Add Emulator;添加模拟器
Add Filter;添加分类
Add Input;添加输入
Add New Display;添加新的界面
Add Rule;添加规则
Add/Remove Favourite;添加/移除收藏
Add/Remove Tags;添加/移除标签
Additional Import File(s);导入附加文件
All;全部
Allow Exit from 'Displays Menu';在界面菜单中加入退出选项
AltRomname;Rom名称(AltRomname)
AltTitle;标题(AltTitle)
Ambient Soundtrack;环境音
Ambient Volume;环境音量
Artwork Label;插图标签
Artwork Path;插图路径
Back;<返回<
Category;类别(Category)
CloneOf;克隆 (CloneOf)
Collection/Rom List;收集/游戏列表
Command Arguments;命令及参数（ Arguments）
Command;命令
Comparison;比较
Configure / Controls;设置 / 控制器
Configure / Emulators;设置 / 模拟器
Configure / Displays;设置/界面
Configure / Input;设置/控制器
Configure / Miscellaneous;设置/其它
Configure / Plug-ins;设置/插件
Configure / Scraper;搜刮
Configure / Sound;设置/声音
Configure available emulators;可用模拟器
Configure filter rule;设置分类规则
Configure Intro;设置开机画面
Configure Plug-in;设置插件
Configure Screen Saver;设置屏保
Configure;设置
Confirm Favourites;设置收藏
Control;控制器(Control)
Controls;控制器
Custom1;用户 1
Custom2;用户 2
Custom3;用户 3
Custom4;用户 4
Custom5;用户 5
Custom6;用户 6
Default Font;标准字体
Delete display '$1'?;删除 '$1' 界面?
Delete emulator '$1'?;删除 '$1' 模拟器?
Delete filter '$1'?;删除 '$1' 分类?
Delete this Display;删除界面
Delete this Emulator;删除模拟器
Delete this Filter;删除排序
Delete this filter;删除分类
Delete this Rule;删除规则
Disabled;不显示
Display Edit;界面修改
Display Name;界面名称
DisplayCount;界面数量(DisplayCount)
Displays Menu;显示器菜单
Displays;界面
DisplayType;界面各类(DisplayType)
Down;180度（向下）
Edit Artwork;编辑ARTWORK
Edit Emulator;编辑模拟器
Edit Input;编辑控制器
Emulator Name;模拟器名称
Emulator;模拟器(Emulator)
Emulators;模拟器
Enabled;显示
Enter Display Name;进入显示器名称
Enter Emulator Name;进入模拟器名称
Enter Filter Name;进入排序名称
Executable;执行
Exit (Confirm);退出 (Yes/No)
Exit Attract-Mode;退出ATTRACT-MODE
Exit Attract-Mode?;退出ATTRACT-MODE吗?
Exit Command;退出指令
Exit Hotkey;退出热键
Exit to Desktop;退出到桌面
Favourite;收藏
FileIsAvailable;文件可用
Fill Screen (Default);铺满屏幕 (标准)
Filter Edit;编辑分类
Filter Name;分类名称
Filter Value;分类内容
Filter Wrap Mode;分类切换模式
Filter;分类
Filters Menu;分类管理菜单
Flip;180度（向下）
font;字体
Font Path;字体路径
Fullscreen Mode;全屏模式
Game Return Sound;游戏返回声音
General;一般
Generate Collection/Rom List;生成收集ROM列表
Generating Rom List: $1%;ROM列表生成中: $1%
Global Filter;全局分类
Hide Brackets in Game Title;隐藏游戏标题中的括号
Info Source/Scraper;信息源/搜刮
Joystick Threshold;操纵杆的阈值
Jump to Next Display;跳到下一界面
Language;语言
Layout Options;布局选项
Layout;布局
Left;270度（向左）
List Limit;列表大小限制
Manufacturer;制造商
Minimum Run Time;最小运行时间
Mouse Threshold;鼠标的阈值
Movie Volume;视频音量
Name;名称
Next Display;下一界面
Next Favourite;下一收藏
Next Filter;下一分类
Next Letter;下一关键词
No Sort;不排序
No Wrap;不切换
No;否
None;没有
OR;或
Overwrite existing '$1' list?;覆盖现有的 '$1' 列表？
PlayedCount;游戏计数
PlayedTime;游戏时间
Players;玩家(Players)
Plug-ins;插件
Press Input;按下-设置按键
Previous Display;上一界面
Previous Favourite;上一收藏
Previous Filter;上一分类
Previous Letter;上一关键词
Random Game;随机游戏
Remove Input;移除-设置按键
Replay Last Game;重新上一次的游戏
Right;90度（向右）
Rom Extension(s);ROM扩展
Rom path '$1' not found, proceed anyways?;ROM路径 '$1' 没有找到。继续？
Rom Path(s);ROM路径
Rotation;旋转(Rotation)
Rule Edit;规则编辑
Rule;规则
Scrape Artwork;搜刮插图（Artwork）
Scrape Fanart;搜刮玩家自制（Fanart）
Scrape Flyers/Boxart;搜刮传单/手办（Flyers/Boxart）
Scrape Game Logos (Wheel Art);搜刮LOGO (Wheel Art) 
Scrape mamedb.com (MAME only);搜刮 mamedb.com（仅 MAME）
Scrape Marquees;搜刮跑马灯（Marquees）
Scrape Snaps;搜刮快照（Snaps）
Scrape Videos (MAME only);搜刮 Videos (MAME only)
Scraper;搜刮器
Scraping Artwork: $1%;正在搜刮 $1% 插图
Screen Saver Timeout;屏保等待时间
Screen Saver;屏保
Screenshot;截图
Select;选择
Sort By;排序方式
Sound Volume;声音音量
Sound;声音
Startup Sound;启动声音
Status;仿真、现状(Status)
System Identifier;系统标识（System Identifier）
Tags;标签（Tags）
Target;规则的目标（Target）
The name for this filter;分类的名称
This will overwrite an existing mapping ($1).  Proceed?;覆盖现有的映射 ($1)，继续？
Title;标题(Title)
Toggle Flip;反转 180度
Toggle Layout;切换布局
Toggle Movie;切换影片
Toggle Mute;静音
Toggle Rotate Left;转270度（向左)
Toggle Rotate Right;转90度（向右)
Track Usage;游戏时间/频率跟踪
Up;0度（向上）
Video Decoder;视频解码
Window Mode;窗口模式
Window;窗口化
Wrap within Display (Default);该列表的第一个过滤器（默认）
Wrote $1 entries to Collection/Rom List;所有 $1 ROM条目/ROM列表。
XML Mode;XML 模式
Year;年(Year)
Yes;是

#
# Configure/Controls
# not sup 不支持
#
Back(Exit(Confirm));返回（退出）
Up(Previous Game);↑（上一游戏）
Down(Next Game);↓（下一游戏）
Left(Previous Display);←（上一界面）
Right(Next Display);→（下一界面）

#
# Configure ScreenSaver
# not sup 不支持
#
Basic Movie;全屏式动态画面
Movie Collage;拼图式动态画面
Image Collage;拼图式静态画面
RGB Movie;RGB模式（RGB Movie）
Overlay Artwork;悬浮的插图
Play Sound;声音
Preserve Aspect Ratio;以当前游戏为背景

#
#The filter
#
contains;包含
does not contain;不包含
does not equal;不等于
equals;等于

#
# Displays Menu Options 
# Ver2.2 New added
#
'Displays Menu' Options;界面选择器设置
Menu Style / Layout;主题
Menu Prompt;标题


$1 Rule(s);$1 规则(s)
Add '$1' to Favourites?;添加 '$1' 到收藏？
Add Exception;添加例外 Add Exception
Default Action;默认动作 Default Action
Empty;空
Enable Multiple Monitors;使多个显示器
Exception;其他 Exception
Exception Edit;其他编辑 Exception Edit
Intro;启动画面
Launch Last Game;载入最后一次运行的游戏
Next Game;下一游戏
Next Page;下一页
Play Sound;播放声音
Previous Game;上一游戏
Previous Page;上一页
Remove '$1' from Favourites?;从收藏中先锋队 '$1'？
Show Displays Menu;界面选择器
Show Last Selection (Default);显示最后的选择 (默认)
Show in Cycle;在界面切换转轮中显示
Show in Menu;在界面选择菜单中显示
Startup Mode;启动模式


#
# Extra strings provided by translation
#
Ambient Sounds;背景音乐
Exit menu;退出菜单
Extra;其他信息(Extra)
Launch Last Game on Startup;启动时载入最后一次运行的游戏
Page Down;向下翻页
Page Up;向上翻页
de;Deutsch
en;English
es;Español
fr;Français
jp;日本語 (Japanese)
kr;한글 (Korean)
cn;中文 (Chinese)


#@DONE_TRANSLATED

#
# Strings still needing translation 
#

#
# Help messages
#
_help_art;An artwork resource available for use by layouts
_help_art_add;새로운 아트워크 (스크린샷, 타이틀 화면, 기타 동영상 등) 를 추가할 수 있습니다.
_help_art_label;지정된 라벨명이 레이아웃에서 사용됩니다
_help_art_path;해당 동영상/그림 파일의 경로입니다
_help_autolaunch_last_game;프로그램 시작 시에, 마지막으로 실행하였던 게임을 바로 재 시작할지 여부를 설정합니다
_help_back;Exit menu
_help_confirm_favs;즐겨하는 게임을 추가/삭제할 때에 사용자에게 Yes/No 로 물을 지 여부를 설정합니다
_help_control_add_favourite;현재 선택된 게임을 즐겨찾기에 추가/삭제 하는 키를 설정합니다.
_help_control_add_tags;현재 선택된 게임의 태그를 편집하는 키를 설정합니다.
_help_control_back;Set the control(s) that go back
_help_control_configure;본 '설정 화면' 을 띄우는 키를 설정합니다.
_help_control_custom1;사용자 지정 키 1을 설정합니다.
_help_control_custom2;사용자 지정 키 2를 설정합니다.
_help_control_custom3;Set the "Custom3" control(s)
_help_control_custom4;Set the "Custom4" control(s)
_help_control_custom5;Set the "Custom5" control(s)
_help_control_custom6;Set the "Custom6" control(s)
_help_control_displays_menu;'목록 메뉴' 를 호출하는 키를 설정합니다.
_help_control_down;아래 항목으로 한 칸 이동하는 키를 설정합니다.
_help_control_exit;본 프로그램을 종료하는 키를 설정합니다.
_help_control_exit_no_menu;본 프로그램을 확인 창 없이 바로 종료하는 키를 설정합니다.
_help_control_filters_menu;'필터 메뉴' 를 호출하는 키를 설정합니다.
_help_control_left;Set the control(s) that move the selection left
_help_control_next_display;다음 항목으로 이동하는 키를 설정합니다.
_help_control_next_favourite;다음 즐겨찾기 게임으로 이동하는 키를 설정합니다.
_help_control_next_filter;다음 필터로 이동하는 키를 설정합니다.
_help_control_next_game;Set the control(s) that move to the next game
_help_control_next_letter;다음 글자로 이동하는 키를 설정합니다.
_help_control_next_page;Set the control(s) that move the selection up one page
_help_control_page_down;아래 항목으로 한 페이지 이동하는 키를 설정합니다.
_help_control_page_up;위 항목으로 한 페이지 이동하는 키를 설정합니다.
_help_control_prev_display;이전 목록으로 이동하는 키를 설정합니다.
_help_control_prev_favourite;이전 즐겨찾기 게임으로 이동하는 키를 설정합니다.
_help_control_prev_filter;이전 필터로 이동하는 키를 설정합니다.
_help_control_prev_game;Set the control(s) that move to the previous game
_help_control_prev_letter;이전 글자로 이동하는 키를 설정합니다.
_help_control_prev_page;Set the control(s) that move the selection down one page
_help_control_random_game;랜덤한 게임을 선택하는 키를 설정합니다.
_help_control_replay_last_game;마지막으로 실행했던 게임을 다시 실행하는 키를 설정합니다.
_help_control_right;Set the control(s) that move the selection right
_help_control_screen_saver;화면 보호기를 활성하는 키를 설정합니다.
_help_control_screenshot;스크린샷을 찍는 키를 설정합니다.
_help_control_sel;
_help_control_select;현재 선택된 게임을 실행하는 키를 설정합니다.
_help_control_toggle_flip;화면을 180도 회전하는 키를 설정합니다.
_help_control_toggle_layout;레이아웃을 변경하는 키를 설정합니다. (사용중인 레이아웃에 따라 동작 여부가 달라질 수 있습니다.)
_help_control_toggle_movie;동영상 재생을 켜고 끄는 키를 설정합니다.
_help_control_toggle_mute;음 소거 키를 설정합니다.
_help_control_toggle_rotate_left;화면을 반시계 방향으로 90도 회전하는 키를 설정합니다.
_help_control_toggle_rotate_right;화면을 시계 방향으로 90도 회전하는 키를 설정합니다.
_help_control_up;위 항목으로 한 칸 이동하는 키를 설정합니다.
_help_controls;각종 입력을 설정합니다
_help_default_font;프로그램이 기본으로 사용할 폰트 이름을 지정합니다
_help_display_add;새로운 목록을 추가합니다
_help_display_add_filter;목록에 새로운 필터를 추가합니다
_help_display_delete;목록를 삭제합니다
_help_display_filter;목록의 필터 정보를 관리합니다
_help_display_global_filter;전체 목록에 적용될 전역 필터를 설정합니다.
_help_display_in_cycle;Include this display in the "Previous Display"/"Next Display" cycle?
_help_display_in_menu;Include this display in the "Displays Menu"?
_help_display_layout;목록이 사용할 레이아웃을 지정합니다
_help_display_layout_options;레이아웃에서 지정한 옵션을 바꿀 수 있습니다
_help_display_name;목록의 이름을 나타냅니다
_help_display_romlist;목록이 사용할 롬 목록 파일을 지정합니다
_help_display_sel;목록의 설정을 변경합니다
_help_displays;목록을 설정합니다
_help_displays_menu_exit;리스트 메뉴에 '프로그램 종료' 항목을 넣을 지 여부를 설정합니다
_help_emu_add;새로운 에뮬레이터를 등록합니다.
_help_emu_args;에뮬레이터에 전달할 실행 인자를 설정합니다. 이하의 항목은 각각 알맞게 치환되어 전달됩니다 : [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_emu_delete;에뮬레이터에 대한 항목을 삭제합니다.
_help_emu_executable;에뮬레이터의 실행파일 위치를 지정합니다. $HOME 은 사용자의 홈 디렉토리로 치환됩니다.
_help_emu_exit_hotkey;해당 에뮬레이터를 종료할 전역 핫키를 지정합니다. 해당 핫키가 눌리면 Attract-Mode 에서 에뮬레이터를 강제종료합니다.
_help_emu_gen_romlist;지정된 롬 파일 경로와 XML 옵션, 추가 파일 (catver.ini 등) 을 이용하여 롬 목록을 생성합니다.
_help_emu_import_extras;롬 파일 목록 생성시에 추가로 활용할 파일을 지정합니다. 장르 (catver.ini) 나 게임 플레이 인원 (nplayers.ini) 정보를 담은 파일을 지정할 수 있습니다.
_help_emu_info_source;mess : MAME 방식의 -listxml, mess : MESS 방식의 -listsoftware, thegamesdb.net : 해당 사이트에서 정보를 취득할 경우, steam : 스팀 사이트에서 정보를 취득할 경우. mess, thegamesdb.net 의 경우 식별자가 해당 방식에 맞게 설정되어 있어야 합니다.
_help_emu_listxml;
_help_emu_minimum_run_time; 최소 실행 시간을 초 단위로 지정합니다. 게임 실행 시 적어도 해당 시간 만큼이 지난 후 Attract-Mode 로 제어가 돌아가게 됩니다. 보통은 0 으로 설정하면 됩니다만, 스팀 게임은 적절한 값을 설정해주어야 합니다.
_help_emu_romext;롬 파일들의 확장자 (.zip 등) 을 지정합니다. 세미콜론 (
_help_emu_rompath;에뮬레이터의 롬 파일들이 위치한 경로를 지정합니다.
_help_emu_scrape_artwork;TheGamesDB.net 및 mamedb.com 에서 게임 관련 데이터를 다운로드 합니다.
_help_emu_sel;에뮬레이터의 설정을 변경합니다.
_help_emu_system;본 에뮬레이터의 식별자 입니다. 세미콜론 (
_help_emulators;에뮬레이터를 설정합니다
_help_exit_command;종료 (Yes/No 확인) 명령으로 프로그램을 끌 때 실행할 외부 명령어 입니다. (예. "sudo shutdown")
_help_filter_add_exception;Add an exception to this filter.  If a game matches an exception (and wasn't filtered out by an earlier rule) it will be listed in the filter
_help_filter_add_rule;필터에 새 규칙 추가
_help_filter_delete;본 필터를 삭제합니다.
_help_filter_exception;Configure this filter exception.  If a game matches an exception it will be listed in the filter.  Rules and exceptions get applied in the order that they are listed
_help_filter_list_limit;목록의 크기 제한을 설정할 수 있습니다. 양수는 상위 X 개, 음수는 하위 X 개를 지정하는 데 사용할 수 있습니다. 0 은 무제한입니다.
_help_filter_name;필터의 이름
_help_filter_rule;필터의 규칙을 정의합니다.
_help_filter_sort_by;목록을 정렬할 기준을 설정합니다. 원래 목록 순서대로 표시하려면 '정렬 안 함' 을 선택하십시오.
_help_filter_wrap_mode;목록의 마지막 필터에서 '다음 필터' 키가 입력되었을 때 처리 방식을 결정합니다.
_help_font_path;폰트를 찾을 경로를 지정합니다. 세미콜론 (
_help_hide_brackets;게임 제목을 표시할 때에, 괄호로 둘러싸인 부분은 표시하지 않을 지 여부를 설정합니다
_help_input_action;
_help_input_add;입력 키를 추가합니다
_help_input_default_action;Set the default behaviour for this control
_help_input_delete;해당 입력 키를 삭제합니다
_help_intro;Configure intro
_help_joystick_threshold;조이스틱 입력 민감도를 설정합니다. 1에서 100까지이며, 클수록 덜 민감합니다
_help_language;언어를 설정합니다
_help_misc;그 외 여러 가지 설정을 변경합니다
_help_mouse_threshold;마우스 입력 민감도를 설정합니다. 1 에서 100까지이며, 클수록 덜 민감합니다
_help_multiple_monitors;Enable the use of multiple monitors by Attract-Mode
_help_plugin_command;플러그 인의 실행 파일을 지정합니다
_help_plugin_enabled;플러그 인을 사용할 지 여부를 설정합니다
_help_plugin_sel;플러그 인을 설정합니다
_help_plugins;외부 플러그 인을 설정합니다
_help_rule_comp;필터에 속한 규칙을 설정합니다
_help_rule_delete;해당 규칙을 삭제합니다
_help_rule_target;필터가 게임의 어떤 특성을 가지고 걸러낼 지를 설정합니다
_help_rule_value;필터의 규칙을 정규 표현식으로 설정합니다. 예를 들어 규칙 대상이 '연도' 이며 비교 조건이 '일치' 에 표현식이  "1984" 이면 1984년도에 제작된 게임만 표시합니다. "198." 이면 1980년도에 제작된 모든 게임이 표시됩니다. "(198.)|(199.)" 은 1980년도 및 1990년도의 모든 게임을 표시합니다.
_help_scrape_fanart;온라인에서 팬들이 그린 그림을 다운로드 할지 설정합니다.
_help_scrape_flyers;온라인에서 게임 홍보 포스터 / 박스 아트를 다운로드 할지 설정합니다.
_help_scrape_marquees;온라인에서 Marquee를 다운로드 할지 설정합니다.
_help_scrape_snaps;온라인에서 스크린샷을 다운로드 할지 설정합니다.
_help_scrape_vids;Set whether game videos should be downloaded when scraping
_help_scrape_wheels;온라인에서 Wheel Art 형식의 게임 로고를 다운로드 할지 설정합니다.
_help_scraper;게임 관련 데이터를 다운로드할 사이트 정보를 설정합니다.
_help_screen_saver;화면 보호기를 설정합니다
_help_screen_saver_timeout;몇 초 동안 입력이 없을 시 화면 보호기를 작동시킬 지를 설정합니다. 0 이면 화면 보호기 기능을 정지합니다
_help_sound;효과음, 배경음악, 볼륨 조절 등을 설정합니다
_help_sound_sel;해당 상황에 재생할 소리를 지정합니다
_help_startup_mode;Set what should happen when Attract-Mode first starts up
_help_track_usage;플레이 내역 (플레이 횟수, 시간) 을 기록할지 설정합니다.
_help_volume;음량을 설정합니다. 0 에서 100 까지 이며, 0 이 음소거 입니다.
_help_window_mode;.Attract-Mode 가 창 모드로 동작할지 전체 화면으로 동작할지를 설정합니다.
_sort_regexp;^(Vs\. The |The |Vs\. )


#
# Listbox
#
#wof;三国志

#
# fiter
#
#Fighter;格斗类
