#@中文 (Chinese);win_font=MSYH,YuGothR,MALGUN,ARIALUNI,MSMINCHO;mac_font=AppleLiSung;linux_font=UMing,NotoSansCJK-Regular
#
# Interface strings
#
$1 Rule(s);$1 规则(s)
Action;项目
Add '$1' to Favourites?;添加 '$1' 到收藏？
Add Artwork;添加插图（Artwork)
Add Emulator;添加模拟器
Add Exception;添加例外 Add Exception
Add Filter;添加分类
Add Input;添加输入
Add New Display;添加新的界面
Add Rule;添加规则
Add/Remove Favourite;添加/移除收藏
Add/Remove Tags;添加/移除标签
Additional Import File(s);导入附加文件
All;全部
Allow Exit from 'Displays Menu';在界面菜单中加入退出选项
AltRomname;Rom名称(AltRomname)
AltTitle;标题(AltTitle)
Ambient Soundtrack;环境音
Ambient Volume;环境音量
Artwork Label;插图标签
Artwork Path;插图路径
Back;<返回<
Category;类别(Category)
CloneOf;克隆 (CloneOf)
Collection/Rom List;收集/游戏列表
Command;命令
Command Arguments;命令及参数（ Arguments）
Comparison;比较
Configure;设置
Configure / Controls;设置 / 控制器
Configure / Displays;设置/界面
Configure / Emulators;设置 / 模拟器
Configure / Miscellaneous;设置/其它
Configure / Plug-ins;设置/插件
Configure / Scraper;搜刮
Configure / Sound;设置/声音
Configure Intro;设置开机画面
Configure Plug-in;设置插件
Configure Screen Saver;设置屏保
Confirm Favourites;设置收藏
Control;控制器(Control)
Controls;控制器
Custom1;用户 1
Custom2;用户 2
Custom3;用户 3
Custom4;用户 4
Custom5;用户 5
Custom6;用户 6
Default Action;默认动作 Default Action
Default Font;标准字体
Delete display '$1'?;删除 '$1' 界面?
Delete emulator '$1'?;删除 '$1' 模拟器?
Delete filter '$1'?;删除 '$1' 分类?
Delete this Display;删除界面
Delete this Emulator;删除模拟器
Delete this Filter;删除排序
Delete this Rule;删除规则
Disabled;不显示
Display Edit;界面修改
Display Name;界面名称
DisplayCount;界面数量(DisplayCount)
DisplayType;界面各类(DisplayType)
Displays;界面
Displays Menu;显示器菜单
Down;180度（向下）
Edit Artwork;编辑ARTWORK
Edit Emulator;编辑模拟器
Edit Input;编辑控制器
Empty;空
Emulator;模拟器(Emulator)
Emulator Name;模拟器名称
Emulators;模拟器
Enable Multiple Monitors;使多个显示器
Enabled;显示
Enter Display Name;进入显示器名称
Enter Emulator Name;进入模拟器名称
Enter Filter Name;进入排序名称
Exception;其他 Exception
Exception Edit;其他编辑 Exception Edit
Executable;执行
Exit;退出 (Yes/No)
Exit Attract-Mode;退出ATTRACT-MODE
Exit Attract-Mode?;退出ATTRACT-MODE吗?
Exit Command;退出指令
Exit Hotkey;退出热键
Exit to Desktop;退出到桌面
Extra;其他信息(Extra)
Favourite;收藏
FileIsAvailable;文件可用
Fill Screen (Default);铺满屏幕 (标准)
Filter;分类
Filter Edit;编辑分类
Filter Name;分类名称
Filter Value;分类内容
Filter Wrap Mode;分类切换模式
Filters Menu;分类管理菜单
Flip;180度（向下）
Font Path;字体路径
Fullscreen Mode;全屏模式
Game Return Sound;游戏返回声音
General;一般
Generate Collection/Rom List;生成收集ROM列表
Generating Rom List: $1%;ROM列表生成中: $1%
Global Filter;全局分类
Hide Brackets in Game Title;隐藏游戏标题中的括号
Info Source/Scraper;信息源/搜刮
Intro;启动画面
Joystick Threshold;操纵杆的阈值
Jump to Next Display;跳到下一界面
Language;语言
Launch Last Game;载入最后一次运行的游戏
Layout;布局
Layout Options;布局选项
Left;270度（向左）
List Limit;列表大小限制
Manufacturer;制造商
Menu Prompt;标题
Menu Style / Layout;主题
Mouse Threshold;鼠标的阈值
Movie Volume;视频音量
Name;名称
Next Display;下一界面
Next Favourite;下一收藏
Next Filter;下一分类
Next Game;下一游戏
Next Letter;下一关键词
Next Page;下一页
No;否
No Sort;不排序
No Wrap;不切换
None;没有
OR;或
Overwrite existing '$1' list?;覆盖现有的 '$1' 列表？
Play Sound;播放声音
PlayedCount;游戏计数
PlayedTime;游戏时间
Players;玩家(Players)
Plug-ins;插件
Press Input;按下-设置按键
Previous Display;上一界面
Previous Favourite;上一收藏
Previous Filter;上一分类
Previous Game;上一游戏
Previous Letter;上一关键词
Previous Page;上一页
Random Game;随机游戏
Remove '$1' from Favourites?;从收藏中先锋队 '$1'？
Remove Input;移除-设置按键
Replay Last Game;重新上一次的游戏
Right;90度（向右）
Rom Extension(s);ROM扩展
Rom Path(s);ROM路径
Rom path '$1' not found, proceed anyways?;ROM路径 '$1' 没有找到。继续？
Rotation;旋转(Rotation)
Rule;规则
Rule Edit;规则编辑
Scrape Artwork;搜刮插图（Artwork）
Scrape Fanart;搜刮玩家自制（Fanart）
Scrape Flyers/Boxart;搜刮传单/手办（Flyers/Boxart）
Scrape Game Logos (Wheel Art);搜刮LOGO (Wheel Art) 
Scrape Marquees;搜刮跑马灯（Marquees）
Scrape Snaps;搜刮快照（Snaps）
Scrape Videos (MAME only);搜刮 Videos (MAME only)
Scraper;搜刮器
Scraping Artwork: $1%;正在搜刮 $1% 插图
Screen Saver;屏保
Screen Saver Timeout;屏保等待时间
Screenshot;截图
Select;选择
Show Displays Menu;界面选择器
Show Last Selection (Default);显示最后的选择 (默认)
Show in Cycle;在界面切换转轮中显示
Show in Menu;在界面选择菜单中显示
Sort By;排序方式
Sound;声音
Sound Volume;声音音量
Startup Mode;启动模式
Startup Sound;启动声音
Status;仿真、现状(Status)
System Identifier;系统标识（System Identifier）
Tags;标签（Tags）
Target;规则的目标（Target）
The name for this filter;分类的名称
This will overwrite an existing mapping ($1).  Proceed?;覆盖现有的映射 ($1)，继续？
Title;标题(Title)
Toggle Flip;反转 180度
Toggle Layout;切换布局
Toggle Movie;切换影片
Toggle Mute;静音
Toggle Rotate Left;转270度（向左)
Toggle Rotate Right;转90度（向右)
Track Usage;游戏时间/频率跟踪
Up;0度（向上）
Video Decoder;视频解码
Window;窗口化
Window Mode;窗口模式
Wrap within Display (Default);该列表的第一个过滤器（默认）
Wrote $1 entries to Collection/Rom List;所有 $1 ROM条目/ROM列表。
Year;年(Year)
Yes;是
contains;包含
does not contain;不包含
does not equal;不等于
equals;等于

#
# Help messages
#

#
# Extra strings provided by translation
#
'Displays Menu' Options;界面选择器设置
Add a rule to this filter;添加分类规则
Ambient Sounds;背景音乐
Back(Exit(Confirm));返回（退出）
Basic Movie;全屏式动态画面
Configure / Input;设置/控制器
Configure available emulators;可用模拟器
Configure filter rule;设置分类规则
Delete this filter;删除分类
Down(Next Game);↓（下一游戏）
Exit menu;退出菜单
Image Collage;拼图式静态画面
Launch Last Game on Startup;启动时载入最后一次运行的游戏
Left(Previous Display);←（上一界面）
Minimum Run Time;最小运行时间
Movie Collage;拼图式动态画面
Overlay Artwork;悬浮的插图
Page Down;向下翻页
Page Up;向上翻页
Preserve Aspect Ratio;以当前游戏为背景
RGB Movie;RGB模式（RGB Movie）
Right(Next Display);→（下一界面）
Scrape mamedb.com (MAME only);搜刮 mamedb.com（仅 MAME）
Up(Previous Game);↑（上一游戏）
XML Mode;XML 模式
cn;中文 (Chinese)
de;Deutsch
en;English
es;Español
font;字体
fr;Français
jp;日本語 (Japanese)
kr;한글 (Korean)

#@DONE_TRANSLATED
#
# Strings still needing translation
#
Add tag: '$1';Add tag: '$1'
Artwork Name;Artwork Name
Attract-Mode detected emulator(s) that can be imported automatically.  Import them now?;Attract-Mode detected emulator(s) that can be imported automatically.  Import them now?
Blank Game;Blank Game
Buttons;Buttons
Clear Hotkey?;Clear Hotkey?
Configure / Displays Menu;Configure / Displays Menu
Configure / Joystick Mapping;Configure / Joystick Mapping
Configure Layout;Configure Layout
Confirm Exit;Confirm Exit
Create new tag;Create new tag
Custom Arguments;Custom Arguments
Custom Executable;Custom Executable
Default;Default
Delete game '$1'?;Delete game '$1'?
Delete shortcut '$1'?;Delete shortcut '$1'?
Delete this Game;Delete this Game
Delete this Shortcut;Delete this Shortcut
Edit Game;Edit Game
Edit Shortcut;Edit Shortcut
Enter Romlist Name;Enter Romlist Name
Enter new tag name;Enter new tag name
Exit Message;Exit Message
Insert Command Shortcut;Insert Command Shortcut
Insert Display Shortcut;Insert Display Shortcut
Insert Game Entry;Insert Game Entry
Insert Menu Entry;Insert Menu Entry
Joystick $1;Joystick $1
Joystick Mappings;Joystick Mappings
Layout File;Layout File
Non-Blocking Mode Wait;Non-Blocking Mode Wait
Overview;Overview
Pause Hotkey;Pause Hotkey
Please Wait;Please Wait
Press Hotkey;Press Hotkey
Remove tag: '$1';Remove tag: '$1'
Select template to use for emulator settings;Select template to use for emulator settings
Window (No Border);Window (No Border)
Working Directory;Working Directory
multi;multi
_help_art;An artwork resource available for use by layouts
_help_art_add;Add a new artwork resource (marquee images, screen shots, etc.)
_help_art_label;The label that identifies this artwork resource (used by layouts)
_help_art_path;The path to the files for this artwork.  Multiple paths can be entered if separated by a semicolon.
_help_back;Exit menu
_help_confirm_exit;Confirm before exiting Attact-Mode?
_help_confirm_favs;Confirm the addition/removal of Favourites?
_help_control_add_favourite;Set the control(s) that mark/unmark the currently selected game as a favourite
_help_control_add_tags;Set the control(s) that add/remove tags from the currently selected game
_help_control_back;Set the control(s) that go back
_help_control_configure;Set the control(s) that show the "Configuration Menu"
_help_control_custom1;Set the "Custom1" control(s)
_help_control_custom2;Set the "Custom2" control(s)
_help_control_custom3;Set the "Custom3" control(s)
_help_control_custom4;Set the "Custom4" control(s)
_help_control_custom5;Set the "Custom5" control(s)
_help_control_custom6;Set the "Custom6" control(s)
_help_control_displays_menu;Set the control(s) that show the "Displays Menu"
_help_control_down;Set the control(s) that move the selection down
_help_control_edit_game;Set the control(s) to edit the current selection
_help_control_exit;Set the control(s) that exit the frontend
_help_control_exit_to_desktop;Set the control(s) that exit the frontend immediately to the desktop
_help_control_filters_menu;Set the control(s) that show the "Filters Menu"
_help_control_intro;Set the control(s) that show the intro video
_help_control_left;Set the control(s) that move the selection left
_help_control_next_display;Set the control(s) that move to the next display
_help_control_next_favourite;Set the control(s) that move to the next favourite
_help_control_next_filter;Set the control(s) that move to the next filter
_help_control_next_game;Set the control(s) that move to the next game
_help_control_next_letter;Set the control(s) that move to the next letter
_help_control_next_page;Set the control(s) that move the selection up one page
_help_control_prev_display;Set the control(s) that move to the previous display
_help_control_prev_favourite;Set the control(s) that move to the previous favourite
_help_control_prev_filter;Set the control(s) that move to the previous filter
_help_control_prev_game;Set the control(s) that move to the previous game
_help_control_prev_letter;Set the control(s) that move to the previous letter
_help_control_prev_page;Set the control(s) that move the selection down one page
_help_control_random_game;Set the control(s) that select a random game from the current list
_help_control_replay_last_game;Set the control(s) that relaunch the last game played
_help_control_right;Set the control(s) that move the selection right
_help_control_screen_saver;Set the control(s) that launch screen saver mode
_help_control_screenshot;Set the control(s) that take a screenshot of the frontend
_help_control_select;Set the control(s) that launch the current selection
_help_control_toggle_flip;Set the control(s) that toggle whether the display should be rotated 180 degrees
_help_control_toggle_layout;Set the control(s) that toggle the layout script to use (It depends on the layout you are using whether this does anything)
_help_control_toggle_movie;Set the control(s) that toggle whether or not videos should be played
_help_control_toggle_mute;Set the control(s) that mute/unmute frontend sound
_help_control_toggle_rotate_left;Set the control(s) that toggle whether the display should be rotated 90 degrees to the left
_help_control_toggle_rotate_right;Set the control(s) that toggle whether the display should be rotated 90 degrees to the right
_help_control_up;Set the control(s) that move the selection up
_help_controls;Configure the joystick, keyboard and mouse inputs that control Attract-Mode
_help_default_font;The name of the default font to use
_help_display_add;Add a new display
_help_display_add_filter;Add a filter to this display's filter set
_help_display_delete;Delete this display
_help_display_filter;Configure this filter from the display's filter set
_help_display_global_filter;Configure global filter rules that are applied to every entry in this display's collection/rom list
_help_display_in_cycle;Include this display in the "Previous Display"/"Next Display" cycle?
_help_display_in_menu;Include this display in the "Displays Menu"?
_help_display_layout;The layout to use for this display
_help_display_layout_options;Configure any layout-specific options
_help_display_name;The title for this display
_help_display_romlist;The collection/rom list to use for this display
_help_display_sel;Configure display
_help_displays;Configure the romlist/layout groupings (a.k.a. "Displays") that are available to be cycled through in Attract-Mode
_help_displays_menu;Configure options for the "Displays Menu"
_help_displays_menu_exit;Configure whether an Exit option should be provided in the"Displays Menu"
_help_displays_menu_layout;The layout to use for the 'Displays Menu'. Set to 'Default' to use the frontend's built-in menu
_help_displays_menu_prompt;The 'Displays Menu' prompt (i.e. "Select System")
_help_emu_add;Add a new emulator
_help_emu_args;The command line arguments for this emulator.  The following get substituted appropriately: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn], [workdir], [nothing], as well as any valid 'magic tokens' (see layout documentation)
_help_emu_delete;Delete the entry for this emulator
_help_emu_executable;The full path and name of the emulator executable. Possible variables: $HOME = User's home dir, $PROGDIR = Attract-Mode program dir. Windows OS additionally has %SYSTEMROOT% and %PROGRAMFILES% matching system environment variables.
_help_emu_exit_hotkey;Set a global hotkey to exit the emulator.  Attract-Mode will terminate the emulator process if this hotkey gets pressed
_help_emu_gen_romlist;Generate a romlist by searching the configured rom path for roms with the configured extension, incorporating XML and additional import file information into the generated list (if available)
_help_emu_import_extras;Path to any additional files that need to be read when generating a romlist for this emulator.  Supported files are: catver.ini (for game categories), nplayers.ini (for number of players) and mame.xml.  Multiple file paths can be entered if separated by a semicolon
_help_emu_info_source;Use "listxml" for mame -listxml output, "listsoftware" for mame/mess -listsoftware output, "thegamesdb.net" to scrape data from thegamesdb.net, "steam" to read from a steam installation, or "scummvm" if the emulator is scummvm.  "listsoftware" and "thegamesdb.net" also require that a System Identifier recognized by those sources be configured
_help_emu_nb_mode_wait;If this is non-zero, the emulator will be run in 'non-blocking mode'.  The frontend will wait up to this number of seconds to lose focus to the emulator's window, and will wake up again when focus returns to the frontend's window.  This is necessary for launching programs like Steam correctly.  Should be 0 unless you know you need it
_help_emu_pause_hotkey;Set a global hotkey to pause the emulator.  When pressed, Attract-Mode will pause the emulator process and return to the frontend. The emulator process can be resumed by selecting the same game again in the frontend.
_help_emu_romext;The rom extension(s) for this emulator (i.e. .zip).  Multiple extensions can be entered if separated by a semicolon.  Specify "<DIR>" as an entry if games are stored in separate subdirectories
_help_emu_rompath;The path to the roms for this emulator.  Multiple paths can be entered if separated by a semicolon.
_help_emu_scrape_artwork;Scrape missing artwork images for this emulator from the net
_help_emu_sel;Configure emulator
_help_emu_sel_gen_romlist;Generate a Collection/Romlist containing games for multiple emulators
_help_emu_system;The system identifier(s) for this emulator.  Multiple values can be entered if separated by a semicolon
_help_emu_workdir;The working directory for this emulator.  This is the directory that the frontend runs the emulator from.  Also, any relative rom paths, artwork paths, or additional import file paths are treated as being relative to this directory
_help_emulators;Configure emulator settings
_help_exit_command;Command to execute when exiting the frontend [i.e. "sudo shutdown"]
_help_exit_message;Alternate message to exit the frontend [i.e. "Shut Down System"]
_help_filter_add_exception;Add an exception to this filter.  If a game matches an exception (and wasn't filtered out by an earlier rule) it will be listed in the filter
_help_filter_add_rule;Add a rule to this filter.  A game must match all filter rules (or a single exception) to be listed in a filter
_help_filter_delete;Delete this filter
_help_filter_exception;Configure this filter exception.  If a game matches an exception it will be listed in the filter.  Rules and exceptions get applied in the order that they are listed
_help_filter_list_limit;Set this to a non-zero value if you wish to limit the size of a sorted list.  Use a positive value for the first X entries (i.e. "10" gives the first 10 entries), a negative value for the last X entries (i.e. "-25" gives the last 25 entries), or "0" for no limit
_help_filter_name;The name for this filter
_help_filter_rule;Configure this filter rule.  A game must match all filter rules (or a single exception) to be listed in a filter
_help_filter_sort_by;The game information attribute that you wish to sort the collection/rom list by.  Set to "No Sort" to keep the ordering from the source collection/rom list
_help_filter_wrap_mode;Set what happens when the "Next Filter" or "Previous Filter" actions reach the end of the filter set
_help_font_path;The directories containing fonts.  Multiple directories can be entered if separated by a semicolon.  Attract-Mode will recursively search these directories to find a specified font
_help_game_custom_args;Set this to override the default command line arguments for this game.  Set this to [nothing] if you want to override with no parameters.  The following get substituted appropriately: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_game_custom_executable;Set this to override the default executable for this game
_help_game_delete;Delete this game from the Romlist
_help_game_edit;Edit this game information
_help_game_overview;Edit game overview
_help_generator_build;Generate romlist with the selected emulator(s)
_help_generator_opt;Set whether this emulator is to be included in the generated romlist
_help_hide_brackets;Hide text in brackets when showing game titles
_help_hide_console;Hide console on startup. Note that this only works if starting Attract-Mode from a Windows GUI. If started from an existing console window (e.g. a batch file) then the process will always "attach" to the existing console and output to it.
_help_input_action;
_help_input_add;Add a new input mapping for this control
_help_input_default_action;Set the default behaviour for this control
_help_input_delete;Remove this input mapping
_help_intro;Configure intro
_help_joystick_map;Map the frontend's joystick slots to specifically named joystick/gamepad devices attached to your computer (You can use this to force the frontend to always use 'Microsoft X-Box 360 pad' as Joystick 0, for example.)
_help_joystick_threshold;The threshold for registering joystick moves, from 1 to 100 (100=least sensitive)
_help_language;Select the language to use in Attract-Mode's user interface
_help_layout_file;Some layouts provide multiple layout*.nut files.  Select which layout file to use
_help_misc;Configure miscellaneous settings
_help_mouse_threshold;The threshold for registering mouse moves, from 1 to 100 (100=least sensitive)
_help_multiple_monitors;Enable the use of multiple monitors by Attract-Mode.  Setting this to 'No' may reduce screen flicker when launching games
_help_plugin_command;The executable associated with this plug-in
_help_plugin_enabled;Set whether this plug-in is enabled
_help_plugin_sel;Configure plug-in
_help_plugins;Configure available plug-ins
_help_rule_comp;Comparison type for the filter
_help_rule_delete;Delete this filter rule
_help_rule_target;The game information attribute that you wish to filter based on
_help_rule_value;The regular expression value to filter to.  For example, if the filter target is "Year" and comparison is "equals", a value of "1984" will match the year of 1984, "198." will match any year in the 80s, and "(198.)|(199.)" will match any year in the 80s or 90s
_help_scrape_fanart;Set whether game fanart should be downloaded when scraping
_help_scrape_flyers;Set whether game flyers and box covers should be downloaded when scraping
_help_scrape_marquees;Set whether game marquees and banners should be downloaded when scraping
_help_scrape_snaps;Set whether game snapshots should be downloaded when scraping
_help_scrape_vids;Set whether game videos should be downloaded when scraping
_help_scrape_wheels;Set whether game logos should be downloaded when scraping
_help_scraper;Configure artwork scraper settings
_help_screen_saver;Configure screen saver
_help_screen_saver_timeout;The amount of time in seconds to wait before switching to the screen saver.  0 to disable
_help_shortcut_artwork_name_edit;Optionally provide an artwork name to be associated with this shortcut.  The frontend will try to load artworks with this name when displaying the shortcut
_help_shortcut_delete;Delete this shortcut from the Romlist
_help_shortcut_label_edit;Edit this shortcut's label
_help_shortcut_target_edit;Edit this shortcut's target
_help_sound;Configure sound volumes, sound event mappings and the ambient soundtrack
_help_sound_sel;Assign a sound to this event/action
_help_startup_mode;Set what should happen when Attract-Mode first starts up
_help_track_usage;Configure whether Attract-Mode should track usage (played time and play count for each game)
_help_video_decoder;Configure the decoder to use for video playback (if multiple decoders are available)
_help_volume;Valid volume settings are from 0 (mute) to 100
_help_window_mode;Set whether Attract-Mode fills the screen or runs in a window
_sort_regexp;^(Vs\. The |The |Vs\. )
