#@Deutsch
#
# Interface strings
#
$1 Rule(s);$1 Regel(n)
Action;Aktion
Add Artwork;Bilddatei hinzufügen
Add Emulator;Emulator hinzufügen
Add Filter;Filter hinzufügen
Add Input;Steuerung hinzufügen
Add New Display;Neuen Bildschirm hinzufügen
Add Rule;Regel hinzufügen
Add/Remove Favourite;Favorit hinzufügen/löschen
Add/Remove Tags;Markierungen hinzufügen/löschen
Additional Import File(s);Zusätzliche Import Datei(en)
All;Alle
Allow Exit from 'Displays Menu';Verlassen des "Listen Menüs" zulassen
AltRomname;Alternativer Rom-Name
AltTitle;Alternativer Titel
Ambient Soundtrack;Umgebungs-Soundtrack
Ambient Volume;Umgebungs-Lautstärke
Artwork Label;Bezeichnung der Bilddatei
Artwork Path;Pfad zur Bilddatei
Back;Zurück
Category;Kategorie
CloneOf;Clon von
Collection/Rom List;Sammlung/Romliste
Command;Kommando
Command Arguments;Kommandozeilenargumente
Comparison;Vergleich
Configure;Konfiguration
Configure / Controls;Konfiguration / Steuerung
Configure / Displays;Konfiguration / Bildschirme
Configure / Emulators;Konfiguration / Emulator(en)
Configure / Miscellaneous;Konfiguration / Verschiedenes
Configure / Plug-ins;Konfiguration / Plug-ins
Configure / Scraper;Konfiguration / Scraper
Configure / Sound;Konfiguration / Klang
Configure Plug-in;Konfiguriere Plug-in
Configure Screen Saver;Bildschirmschoner konfigurieren
Confirm Favourites;Favoriten bestätigen
Control;Steuerung
Controls;Steuerungen
Custom1;Eigendefiniert1
Custom2;Eigendefiniert2
Custom3;Eigendefiniert3
Custom4;Eigendefiniert4
Custom5;Eigendefiniert5
Custom6;Eigendefiniert6
Default Font;Standard Font
Delete display '$1'?;Bildschirm '$1' löschen?
Delete emulator '$1'?;Emulator '$1' löschen?
Delete filter '$1'?;Filter '$1' löschen?
Delete this Display;Diesen Bildschirm löschen
Delete this Emulator;Diesen Emulator löschen
Delete this Filter;Diesen Filter löschen
Delete this Rule;Diese Regel löschen
Disabled;ausgeschaltet
Display Edit;Bildschirm bearbeiten
DisplayCount;Anzahl Bildschirme
DisplayType;Bildschirm Typ
Displays;Bildschirme
Displays Menu;Bildschirm Menü
Down;Runter
Edit Artwork;Bilddatei bearbeiten
Edit Emulator;Emulator bearbeiten
Edit Input;Steuerung editieren
Empty;Leer
Emulator;Emulator
Emulator Name;Name des Emulators
Emulators;Emulatoren
Enabled;Aktiviert
Enter Display Name;Bezeichnung des Bildschrim eingeben
Enter Emulator Name;Name des Emulators eingeben
Enter Filter Name;Bezeichnung des Filters eingeben
Executable;Ausführbare Datei
Exit;Beenden (Bestätigen)
Exit Attract-Mode;Attract-Mode beenden
Exit Attract-Mode?;Attract-Mode beenden?
Exit Command;Kommando zum Beenden
Exit Hotkey;Hotkey zum Beenden
Exit to Desktop;Beenden zum Desktop
Favourite;Favorit
Fill Screen (Default);Bildschirm ausfüllen (Standard)
Filter;Filter
Filter Edit;Filter editieren
Filter Name;Bezeichnung des Filters
Filter Value;Filterwert
Filter Wrap Mode;Rolliermodus des Filters
Filters Menu;Filter-Menü
Flip;Umdrehen
Font Path;Pfad zu den Fonts
Fullscreen Mode;Vollbildmodus
Game Return Sound;Klang bei Rückkehr zum Spiel
General;Allgemein
Generate Collection/Rom List;Sammlung/Romliste anlegen
Generating Rom List: $1%;Erzeuge Romliste $1%
Global Filter;Globaler Filter
Hide Brackets in Game Title;Unterdrücke Klammern im Spieltitel
Info Source/Scraper;Info Quelle/Scraper
Joystick Threshold;Schwellwert Joystick
Jump to Next Display;Springe zur nächsten Liste
Language;Sprache
Layout;Thema
Layout Options;Themen Optionen
Left;Links
List Limit;Limit für die Liste 
Manufacturer;Hersteller
Mouse Threshold;Schwellwert Maus
Movie Volume;Film-Lautstärke
Name;Name
Next Display;Nächster Bildschirm
Next Favourite;Nächster Favorit
Next Filter;Nächster Filter
Next Letter;Nächster Buchstabe
Next Page;Seite zurück
No;Nein
No Sort;Keine Sortierung
No Wrap;Kein Rollieren
None;Keine
OR;ODER
Overwrite existing '$1' list?;Existierende Romliste '$1' überschreiben?
Play Sound;Klang abspielen
PlayedCount;Male gespielt
PlayedTime;Zeit gespielt
Players;Spieler
Plug-ins;Plug-ins
Press Input;Steuerung betätigen
Previous Display;Vorheriger Bildschirm
Previous Favourite;Voriger Favorit
Previous Filter;Vorheriger Filter
Previous Letter;Voriger Buchstabe
Previous Page;Seite vor
Random Game;Zufälliges Spiel
Remove Input;Steuerung löschen
Replay Last Game;Letztes Spiel wiederholen
Right;Rechts
Rom Extension(s);ROM Dateiendung(en)
Rom Path(s);Pfad(e) zu dem ROMs
Rom path '$1' not found, proceed anyways?;ROM-Pfad '$1' nicht gefunden. Trotzdem fortfahren?
Rotation;Ausrichtung
Rule;Regel
Rule Edit;Regel editieren
Scrape Artwork;Scrape Bilddateien
Scrape Flyers/Boxart;Scrape Flyers/Boxart
Scrape Game Logos (Wheel Art);Scrape Spiele Logos (Wheel Art)
Scrape Marquees;Scrape Marquees
Scrape Snaps;Scrape Snaps
Scraper;Scraper
Scraping Artwork: $1%;Scrape Bilddatei: $1%
Screen Saver;Bildschirmschoner
Screen Saver Timeout;Timeout des Bildschirmschoners
Screenshot;Bildschirmphoto
Select;Auswählen
Sort By;Sortiert nach
Sound;Klänge
Sound Volume;Klang-Lautstärke
Startup Sound;Start-Klang
Status;Status
System Identifier;System Kennung
Tags;Markierungen
Target;Ziel
The name for this filter;Bezeichnung dieses Filters
This will overwrite an existing mapping ($1).  Proceed?;Dies überschreibt die existierende Zuordnung ($1). Fortfahren?
Title;Titel
Toggle Flip;Umdrehen (180°)
Toggle Layout;Thema wechseln
Toggle Movie;Movie wechseln
Toggle Mute;Stummschaltung wechseln
Toggle Rotate Left;Linksdrehung
Toggle Rotate Right;Rechtsdrehung
Track Usage;Protokolliere Nutzung
Up;Hoch
Window;Fenster
Window Mode;Fenstermodus
Wrap within Display (Default);Rollieren innerhalb der Liste (Standard)
Wrote $1 entries to Collection/Rom List;$1 Einträge zur Romliste hinzugefügt
Year;Jahr
Yes;Ja
contains;enthält
does not contain;enthält nicht
does not equal;ist ungleich
equals;ist gleich

#
# Help messages
#
_help_art;Eine Bilddatei-Quelle, welche im Thema verfügbar ist
_help_art_add;Füge eine neue Bilddatei-Quelle (Marquees, Screenshots etc.) hinzu
_help_art_label;Kennzeichnung zur Identikikation dieser Bilddatei-Quelle (verwendet in Themen)
_help_art_path;Der Pfad zu den Dateien für diese Bilddatei. Mehrere Pfade können durch Semikolon getrennt werden.
_help_back;Menü verlassen
_help_confirm_favs;Das Hinzufügen/Löschen zu den Favoriten bestätigen
_help_control_add_favourite;Definiere die Taste(n), um das momentan gewählten Spiel als Favoriten zu markiern/löschen
_help_control_add_tags;Definiere die Taste(n), um Markierungen zum momentan gewählten Spiel hinzuzufügen/zu löschen
_help_control_configure;Definiere die Taste(n), um das "Konfigurations Menu" anzuzeigen
_help_control_custom1;Definiere die Taste(n) für "Eigendefiniert1" 
_help_control_custom2;Definiere die Taste(n) für "Eigendefiniert2"
_help_control_displays_menu;Definiere die Taste(n), um das "Bildschirm Menü" anzuzeigen
_help_control_down;Definiere die Taste(n), um die Auswahl nach unten zu bewegen
_help_control_exit;Definiere die Taste(n), um das Frontend zu verlassen
_help_control_exit_to_desktop;Definiere die Taste(n), um das Frontend unmittelbar zum Desktop zu verlassen
_help_control_filters_menu;Definiere die Taste(n), um das "Filter Menü" anzuzeigen
_help_control_next_display;Definiere die Taste(n), um zum nächsten Bildschirm zu springen
_help_control_next_favourite;Definiere die Taste(n), um zum nächsten Favoriten zu springen
_help_control_next_filter;Definiere die Taste(n), um zum nächsten Filter zu springen
_help_control_next_letter;Definiere die Taste(n), um zum nächsten Buchstaben zu springen
_help_control_next_page;Definiere die Taste(n), um die Auswahl eine Seite nach unten zu bewegen
_help_control_prev_display;Definiere die Taste(n), um zum vorigen Bildschirm zu springen
_help_control_prev_favourite;Definiere die Taste(n), um zum vorigen Favoriten zu springen
_help_control_prev_filter;Definiere die Taste(n), um zum vorigen Filter zu springen
_help_control_prev_letter;Definiere die Taste(n), um zum vorigen Buchstaben zu springen
_help_control_prev_page;Definiere die Taste(n), um die Auswahl eine Seite nach oben zu bewegen
_help_control_random_game;Definiere die Taste(n), die ein zufälliges Spiel aus der aktuellen Liste wählen
_help_control_replay_last_game;Definiere die Taste(n), die das zuletzt gespielte Spiel erneut starten
_help_control_screen_saver;Definiere die Taste(n), die den Bildschirmschoner starten
_help_control_screenshot;Definiere die Taste(n), um das einen Screenshot vom Frontend zu machen
_help_control_select;Definiere die Taste(n), um die aktuelle Auswahl starten
_help_control_toggle_flip;Definiere die Taste(n), die umschalten ob der Bildschirm 180 Grad gedreht werden soll
_help_control_toggle_layout;Definiere die Taste(n), die umschalten welches Themen-Script genutzt wird (Es hängt aber vom verwendeten Thema ab, ob dies überhaupt etwas bewirkt)
_help_control_toggle_movie;Definiere die Taste(n), die umschalten ob Videos abgespielt werden oder nicht
_help_control_toggle_mute;Definiere die Taste(n), die die Frontend-Klänge stumm/laut schalten
_help_control_toggle_rotate_left;Definiere die Taste(n), die umschalten ob der Bildschirm 90 Grad nach links gedreht werden soll
_help_control_toggle_rotate_right;Definiere die Taste(n), die umschalten ob der Bildschirm 90 Grad nach rechts gedreht werden soll
_help_control_up;Definiere die Taste(n), um die Auswahl nach oben zu bewegen
_help_controls;Konfiguriere die Joystick-, Tastatur- und Maus-Eingaben die Attract-Mode steuern
_help_default_font;Bezeichnung der zu nutzenden Standard-Schriftart
_help_display_add;Neuen Bildschirm hinzufügen
_help_display_add_filter;Füge einen Filter dem Filter-Set dieses Bildschirm hinzu
_help_display_delete;Diesen Bildschirm löschen
_help_display_filter;Konfiguriere diesen Filter vom Filter-Set des Bildschirms
_help_display_global_filter;Konfiguriere die globalen Filterregeln, die auf jeden Eintrag in der Sammlung/Romliste dieses Bildschirm angewendet werden
_help_display_layout;Welches Thema soll dieser Bildschirm nutzen
_help_display_layout_options;Konfiguriere alle Themen-spezifischen Optionen
_help_display_name;Der Titel dieses Bildschirms
_help_display_romlist;Die Sammlung/Romliste, die für diesen Bildschirm verwendet wird
_help_display_sel;Konfiguriere Bildschirm
_help_displays;Konfiguriere die Romlisten/Themen-Gruppierungen (die "Bildschirme") welche in Attract-Mode zum Durchblättern verfügbar sind
_help_displays_menu_exit;Lege fest, ob eine Beenden-Option im "Bildschirm Menü" verfügbar sein soll
_help_emu_add;Neuen Emulator hinzufügen
_help_emu_args;Die Kommandozeilenargumente für diesen Emulator. Folgende Einträge werden entsprechend ersetzt: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_emu_delete;Lösche den Eintrag für diesen Emulator
_help_emu_executable;Der komplette Pfad und Bezeichnung der Emulator Executable. $HOME wird durch die Homedir des Users ersetzt
_help_emu_exit_hotkey;Definiere einen globalen Hotkey, um den Emulator zu verlassen.  Attract-Mode wird den Emulator Prozess beenden, wenn dieser Hotkey betätigt wird.
_help_emu_gen_romlist;Generiere eine Romliste, indem der eingestellte ROM-Pfad nach ROMs mit der definierten Endung durchsucht wird. Falls verfügbar, werden XML-Informationen und zusätzliche Import-Dateien mit einbezogen.
_help_emu_import_extras;Pfad zu beliebigen zusätzlichen Dateien welche gelesen werden müssen wenn eine Romliste für diesen Emulator generiert wird. Unterstützte Dateien sind: catver.ini (für Spiele Kategorien) und nplayers.ini (für Anzahl an Spielern).  Mehrere Dateipfade können durch Semikolon getrennt werden.
_help_emu_info_source;Verwende "listxml" falls der Emulator mame -listxml Ausgabe bereitstellt, "listsoftware" für mame/mess -listsoftware Ausgabe, "thegamesdb.net" um Daten von thegamesdb.net zu scrapen, oder "steam" um von einer Steam-Installation zu lesen. "listsoftware" und "thegamesdb.net" benötigen zusätzlich die Konfiguration einer System-Kennung welche von diesen Ressourcen erkannt wird
_help_emu_nb_mode_wait;Definiere eine minimale Laufzeit (in Sekunden).  Attract-Mode wird nach dem Lauf dieses Emulators warten bis die minimale Zeit verstrichen ist und es zum Vordergund-Fenster wird. Dies wird speziell benötigt, um Steam korrekt unter Windows auszuführen. Lass es auf 0 stehen, ausser du weisst, dass du es benötigst
_help_emu_romext;Die ROM Dateiendung(en) für diesen Emulator (z.B. .zip). Mehrere Endungen können durch Semikolon getrennt werden. Gib "<DIR>" als Eintrag an, falls die Spiele in separaten Unterverzeichnissen gespeichert sind
_help_emu_rompath;Der Pfad zu den ROMs für diesen Emulator. Mehrere Pfade können durch Semikolon getrennt werden.
_help_emu_scrape_artwork;Scrape fehlende Bilddateien für diesen Emulator von TheGamesDB.net und mamedb.com
_help_emu_sel;Konfiguriere Emulator
_help_emu_system;Die System-Kennung(en) für diesen Emulator.  Mehrere Werte können durch Semikolon getrennt werden.
_help_emulators;Konfiguriere verfügbare Spielsysteme und Emulatoren
_help_exit_command;Befehl der ausgeführt wird, wenn Beenden (Bestätigen) gewählt wird [z.B. "sudo shutdown"]
_help_filter_add_rule;Diesem Filter eine Regel hinzufügen
_help_filter_delete;Lösche diesen Filter
_help_filter_list_limit;Setze dies zu einem Wert ungleich Null um die Größe der sortierten Liste zu limitieren. Verwende einen positiven Wert für die ersten X Einträge (z.B. "10" für die ersten 10 Einträge), einen negativen Wert für die letzten X Einträge (z.B. "-25" für die letzten 25 Einträge), oder "0" für alle
_help_filter_name;Bezeichnung für diesen Filter
_help_filter_rule;Konfiguriere Filterregel
_help_filter_sort_by;Das Spiel-Informationsattribut nach dem du die Sammlung/Romliste sortieren möchtest. Stelle auf "Keine Sortierung" um die Sortierung der Quell-Sammlung/Romliste zu verwenden
_help_filter_wrap_mode;Definiere was passieren soll wenn die "Nächster Filter" oder "Vorheriger Filter" Aktionen das Ende Filterliste erreichen
_help_font_path;Die Verzeichnisse mit den Schriftarten. Mehrere Verzeichnisse können angegeben werden, durch Semikolon separiert.  Attract-Mode wird diese Verzeichnisse rekursiv durchsuchen um die angegebene Schriftart zu finden
_help_hide_brackets;Verberge bei der Anzeige der Spieletitel den Text in Klammern 
_help_input_action;
_help_input_add;Dieser Aktion ein neues Steuerungs-Mapping zuordnen
_help_input_delete;Dieses Steuerungs-Mapping löschen
_help_intro;Intro konfigurieren
_help_joystick_threshold;Der Schwellwert um Joystick-Bewegungen noch zu erkennen, von 1 bis 100 (100=am wenigsten empfindlich)
_help_misc;Konfiguriere sonstige Einstellungen
_help_mouse_threshold;Der Schwellwert um Maus-Bewegungen noch zu erkennen, von 1 bis 100 (100=am wenigsten empfindlich)
_help_plugin_command;Die ausführbare Datei, welche mit diesem Plug-in verknüpft ist
_help_plugin_enabled;Festlegen, ob dieses Plug-in aktiviert ist
_help_plugin_sel;Konfiguriere Plug-in
_help_plugins;Konfiguriere verfügbare Plug-ins
_help_rule_comp;Vergleichstyp für diesen Filter
_help_rule_delete;Diese Filterregel löschen
_help_rule_target;Das Spiel-Informationsattribut basierend auf dem du filtern möchtest
_help_rule_value;The reguläre Ausdruckswert nach dem gefiltert wird. Wenn zum Beispiel der Filter auf "Jahr" und der Vergleichswert auf "ist gleich" gesetzt wird, wird ein Wert "1984" das Jahr 1984 filtern, "198." jedes Jahr in den Achtzigern und "(198.)|(199.)" jedes Jahr in den 80er oder 90ern
_help_scrape_fanart;Lege fest ob, Spiel Fanart während des Scrapens heruntergeladen werden sollen
_help_scrape_flyers;Lege fest ob, Spiel Flyers und Box Cover während des Scrapens heruntergeladen werden sollen
_help_scrape_marquees;Lege fest ob, Spiel Marquees und Banner während des Scrapens heruntergeladen werden sollen
_help_scrape_snaps;Lege fest ob, Spiel Snapshots während des Scrapens heruntergeladen werden sollen
_help_scrape_vids;Lege fest ob, Videos der Spiele während des Scrapens heruntergeladen werden sollen
_help_scrape_wheels;Lege fest ob, Spiel Logos während des Scrapens heruntergeladen werden sollen
_help_scraper;Konfiguriere die Bilddatei-Scraper Einstellungen
_help_screen_saver;Konfiguriere Bildschirmschoner
_help_screen_saver_timeout;Die Wartezeit in Sekunden, bevor der Bildschirmschoner aktiv wird. 0 zum Deaktivieren
_help_sound;Konfiguriere Klang-Lautstärke, Klang->Ereignis Zuordnungen und den Umgebungs-Soundtrack
_help_sound_sel;Weise diesem Ereignis/dieser Aktion einen Klang zu
_help_track_usage;Konfiguriere, ob Attract-Mode die Nutzung protokollieren soll (gespielte Zeit und wie-oft-gespielt pro Spiel)
_help_volume;Gültige Lautstärke Einstellungen gehen von 0 (stumm) bis 100 
_help_window_mode;Lege fest, ob Attract-Mode in einem Fenster läuft oder den Bildschirm füllt
_sort_regexp;^(Vs\. The |The |Vs\. )

#
# Extra strings provided by translation
#
Add a rule to this filter;Diesem Filter eine Regel hinzufügen
Ambient Sounds;Umgebungs-Klänge
Basic Movie;Basis Video
Configure available emulators;Verfügbare Emulatoren konfigurieren
Configure filter rule;Filterregel konfigurieren
Delete this filter;Diesen Filter löschen
Image collage;Bilder Collage
Launch Last Game on Startup;Letztes Spiel beim Starten ausführen
Minimum Run Time;Minimale Laufzeit
Movie collage;Video Collage
Overlay Artwork;Bilddatei als Overlay
Preserve Aspect Ratio;Seitenverhältnis beibehalten
XML Mode;XML-Modus
de;Deutsch
en;English
es;Español
fr;Français
_help_autolaunch_last_game;Beim Hochfahren automatisch das zuletzt gespielte Spiel starten

#@DONE_TRANSLATED
#
# Strings still needing translation
#
Add '$1' to Favourites?;Add '$1' to Favourites?
Add Exception;Add Exception
Add tag: '$1';Add tag: '$1'
Artwork Name;Artwork Name
Attract-Mode detected emulator(s) that can be imported automatically.  Import them now?;Attract-Mode detected emulator(s) that can be imported automatically.  Import them now?
Blank Game;Blank Game
Buttons;Buttons
Clear Hotkey?;Clear Hotkey?
Configure / Displays Menu;Configure / Displays Menu
Configure / Joystick Mapping;Configure / Joystick Mapping
Configure Intro;Configure Intro
Configure Layout;Configure Layout
Confirm Exit;Confirm Exit
Create new tag;Create new tag
Custom Arguments;Custom Arguments
Custom Executable;Custom Executable
Default;Default
Default Action;Default Action
Delete game '$1'?;Delete game '$1'?
Delete shortcut '$1'?;Delete shortcut '$1'?
Delete this Game;Delete this Game
Delete this Shortcut;Delete this Shortcut
Display Name;Display Name
Edit Game;Edit Game
Edit Shortcut;Edit Shortcut
Enable Multiple Monitors;Enable Multiple Monitors
Enter Romlist Name;Enter Romlist Name
Enter new tag name;Enter new tag name
Exception;Exception
Exception Edit;Exception Edit
Exit Message;Exit Message
Extra;Extra
FileIsAvailable;FileIsAvailable
Insert Command Shortcut;Insert Command Shortcut
Insert Display Shortcut;Insert Display Shortcut
Insert Game Entry;Insert Game Entry
Insert Menu Entry;Insert Menu Entry
Intro;Intro
Joystick $1;Joystick $1
Joystick Mappings;Joystick Mappings
Launch Last Game;Launch Last Game
Layout File;Layout File
Menu Prompt;Menu Prompt
Menu Style / Layout;Menu Style / Layout
Next Game;Next Game
Non-Blocking Mode Wait;Non-Blocking Mode Wait
Overview;Overview
Pause Hotkey;Pause Hotkey
Please Wait;Please Wait
Press Hotkey;Press Hotkey
Previous Game;Previous Game
Remove '$1' from Favourites?;Remove '$1' from Favourites?
Remove tag: '$1';Remove tag: '$1'
Scrape Fanart;Scrape Fanart
Scrape Videos (MAME only);Scrape Videos (MAME only)
Select template to use for emulator settings;Select template to use for emulator settings
Show Displays Menu;Show Displays Menu
Show Last Selection (Default);Show Last Selection (Default)
Show in Cycle;Show in Cycle
Show in Menu;Show in Menu
Startup Mode;Startup Mode
Video Decoder;Video Decoder
Window (No Border);Window (No Border)
Working Directory;Working Directory
multi;multi
_help_confirm_exit;Confirm before exiting Attact-Mode?
_help_control_back;Set the control(s) that go back
_help_control_custom3;Set the "Custom3" control(s)
_help_control_custom4;Set the "Custom4" control(s)
_help_control_custom5;Set the "Custom5" control(s)
_help_control_custom6;Set the "Custom6" control(s)
_help_control_edit_game;Set the control(s) to edit the current selection
_help_control_intro;Set the control(s) that show the intro video
_help_control_left;Set the control(s) that move the selection left
_help_control_next_game;Set the control(s) that move to the next game
_help_control_prev_game;Set the control(s) that move to the previous game
_help_control_right;Set the control(s) that move the selection right
_help_display_in_cycle;Include this display in the "Previous Display"/"Next Display" cycle?
_help_display_in_menu;Include this display in the "Displays Menu"?
_help_displays_menu;Configure options for the "Displays Menu"
_help_displays_menu_layout;The layout to use for the 'Displays Menu'. Set to 'Default' to use the frontend's built-in menu
_help_displays_menu_prompt;The 'Displays Menu' prompt (i.e. "Select System")
_help_emu_pause_hotkey;Set a global hotkey to pause the emulator.  When pressed, Attract-Mode will pause the emulator process and return to the frontend. The emulator process can be resumed by selecting the same game again in the frontend.
_help_emu_sel_gen_romlist;Generate a Collection/Romlist containing games for multiple emulators
_help_emu_workdir;The working directory for this emulator.  This is the directory that the frontend runs the emulator from.  Also, any relative rom paths, artwork paths, or additional import file paths are treated as being relative to this directory
_help_exit_message;Alternate message to exit the frontend [i.e. "Shut Down System"]
_help_filter_add_exception;Add an exception to this filter.  If a game matches an exception (and wasn't filtered out by an earlier rule) it will be listed in the filter
_help_filter_exception;Configure this filter exception.  If a game matches an exception it will be listed in the filter.  Rules and exceptions get applied in the order that they are listed
_help_game_custom_args;Set this to override the default command line arguments for this game.  Set this to [nothing] if you want to override with no parameters.  The following get substituted appropriately: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_game_custom_executable;Set this to override the default executable for this game
_help_game_delete;Delete this game from the Romlist
_help_game_edit;Edit this game information
_help_game_overview;Edit game overview
_help_generator_build;Generate romlist with the selected emulator(s)
_help_generator_opt;Set whether this emulator is to be included in the generated romlist
_help_hide_console;Hide console on startup. Note that this only works if starting Attract-Mode from a Windows GUI. If started from an existing console window (e.g. a batch file) then the process will always "attach" to the existing console and output to it.
_help_input_default_action;Set the default behaviour for this control
_help_joystick_map;Map the frontend's joystick slots to specifically named joystick/gamepad devices attached to your computer (You can use this to force the frontend to always use 'Microsoft X-Box 360 pad' as Joystick 0, for example.)
_help_language;Select the language to use in Attract-Mode's user interface
_help_layout_file;Some layouts provide multiple layout*.nut files.  Select which layout file to use
_help_multiple_monitors;Enable the use of multiple monitors by Attract-Mode.  Setting this to 'No' may reduce screen flicker when launching games
_help_shortcut_artwork_name_edit;Optionally provide an artwork name to be associated with this shortcut.  The frontend will try to load artworks with this name when displaying the shortcut
_help_shortcut_delete;Delete this shortcut from the Romlist
_help_shortcut_label_edit;Edit this shortcut's label
_help_shortcut_target_edit;Edit this shortcut's target
_help_startup_mode;Set what should happen when Attract-Mode first starts up
_help_video_decoder;Configure the decoder to use for video playback (if multiple decoders are available)
