#@Deutsch
#
# Languages
#
Language;Sprache
en;English
fr;Français
es;Español
de;Deutsch

#
# General
#
Exit Attract-Mode;Attract-Mode beenden
Exit Attract-Mode?;Attract-Mode beenden?
Yes;Ja
No;Nein

#
# Emulator Settings Configuration
#
Edit Artwork;Bilddatei bearbeiten
Artwork Label;Bezeichnung der Bilddatei
Artwork Path;Pfad zur Bilddatei
Edit Emulator;Emulator bearbeiten
Emulator Name;Name des Emulators
Executable;Ausführbare Datei
Command Arguments;Kommandozeilenargumente
Rom Path(s);Pfad(e) zu dem ROMs
Rom Extension(s);ROM Dateiendung(en)
Additional Import File(s);Zusätzliche Import Datei(en)
XML Mode;XML-Modus
Add Artwork;Bilddatei hinzufügen
Generate Collection/Romlist;Sammlung/Romliste anlegen
Delete this Emulator;Diesen Emulator löschen
Generating Rom List: $1%;Erzeuge Romliste $1%
Rom path '$1' not found, proceed anyways?;ROM-Pfad '$1' nicht gefunden. Trotzdem fortfahren?
Overwrite existing '$1' romlist?;Existierende Romliste '$1' überschreiben?
Wrote $1 entries to romlist;$1 Einträge zur Romliste hinzugefügt
Delete emulator '$1'?;Emulator '$1' löschen?
Config / Emulators;Konfiguration / Emulator(en)
Add Emulator;Emulator hinzufügen
Enter Emulator Name;Name des Emulators eingeben
Configure available emulators;Verfügbare Emulatoren konfigurieren
Exit Hotkey; Hotkey zum Beenden

#
# Filter Settings Configuration
#
Enter Filter Name;Bezeichnung des Filters eingeben
Rule Edit;Regel editieren
Target;Ziel
Comparison;Vergleich
Filter Value;Filterwert
Delete this Rule;Diese Regel löschen
Filter Edit;Filter editieren
Filter Name;Bezeichnung des Filters
Rule;Regel
Add Rule;Regel hinzufügen
Delete this Filter;Diesen Filter löschen
Delete filter '$1'?;Filter '$1' löschen?
All;Alle
Title;Titel
Emulator;Emulator
CloneOf;Clon von
Year;Jahr
Manufacturer;Hersteller
Category;Kategorie
Players;Spieler
Rotation;Ausrichtung
Control;Steuerung
Status;Status
DisplayType;Bildschirm Typ
DisplayCount;Anzahl Bildschirme
Favourite;Favorit
equals;ist gleich
does not equal;ist ungleich
contains;enthält
does not contain;enthält nicht
The name for this filter;Bezeichnung dieses Filters
Configure filter rule;Filterregel konfigurieren
Add a rule to this filter;Diesem Filter eine Regel hinzufügen
Delete this filter;Diesen Filter löschen

#
# Display Settings Configuration
#
Display Edit;Bildschirm bearbeiten
Layout;Thema
Collection/Rom List;Sammlung/Romliste
Filter;Filter
Add Filter;Filter hinzufügen
Delete this Display;Diesen Bildschirm löschen
Delete display '$1'?;Bildschirm '$1' löschen?
Configure / Displays;Konfiguration / Bildschirme
Add New Display;Neuen Bildschirm hinzufügen
Enter Display Name;Bezeichnung des Bildschrim eingeben

#
# Input Settings Configuration
#
Edit Input;Steuerung editieren
Action;Aktion
Remove Input;Steuerung löschen
Add Input;Steuerung hinzufügen
Press Input;Steuerung betätigen
This will overwrite an existing mapping ($1).  Proceed?;Dies überschreibt die existierende Zuordnung ($1). Fortfahren?
Configure / Input;Konfiguration / Steuerung
OR;ODER
Select;Auswählen
Up;Hoch
Down;Runter
Page Up;Seite vor
Page Down;Seite zurück
Previous Display;Vorheriger Bildschirm
Next Display;Nächster Bildschirm
Displays Menu;Bildschirm Menü
Previous Filter;Vorheriger Filter
Next Filter;Nächster Filter
Filters Menu;Filter-Menü
Toggle Layout;Thema wechseln
Toggle Movie;Movie wechseln
Toggle Mute;Stummschaltung wechseln
Toggle Rotate Right;Rechtsdrehung
Toggle Flip;Umdrehen (180°)
Toggle Rotate Left;Linksdrehung
Exit (Confirm);Beenden (Bestätigen)
Exit to Desktop;Beenden zum Desktop
Screenshot;Bildschirmphoto
Configure;Konfigurieren
Random Game;Zufälliges Spiel
Add/Remove Favourite;Favorit hinzufügen/löschen
Next Favourite;Nächster Favorit
Previous Favourite;Voriger Favorit
Replay Last Game;Letztes Spiel wiederholen
Ambient Sounds;Umgebungs-Klänge
Startup Sound;Start-Klang
Game Return Sound;Klang bei Rückkehr zum Spiel
Mouse Threshold;Schwellwert Maus
Joystick Threshold;Schwellwert Joystick

#
# Sound Settings Configuration
#
Configure / Sound;Konfiguration / Klang
Sound Volume;Klang-Lautstärke
Ambient Volume;Umgebungs-Lautstärke
Movie Volume;Film-Lautstärke
Ambient Soundtrack;Umgebungs-Soundtrack

#
# Miscellaneous Settings Configuration
#
Configure / Miscellaneous;Konfiguration / Verschiedenes
Hide Brackets in Game Title;Unterdrücke Klammern im Spieltitel
Launch Last Game on Startup;Letztes Spiel beim Starten ausführen
Confirm Favourites;Favoriten bestätigen
Layout Options;Themen Optionen
None;Keine
Right;Rechts
Flip;Umdrehen
Left;Links
Exit Command;Kommando zum Beenden
Default Font;Standard Font
Font Path;Pfad zu den Fonts
Allow Exit from 'Lists Menu';Verlassen des "Listen Menüs" zulassen
Configure Screen Saver;Bildschirmschoner konfigurieren
Screen Saver Timeout;Timeout des Bildschirmschoners

#
# Plug-in Configuration
#
Configure Plug-in;Konfiguriere Plug-in
Name;Name
Command;Kommando
Enabled;Aktiviert
Configure / Plug-ins;Konfiguration / Plug-ins

#
# Configuration Main Menu
#
Configure;Konfiguration
Emulators;Emulatoren
Displays;Bildschirme
Controls;Steuerungen
Sound;Klänge
Screen Saver;Bildschirmschoner
Plug-ins;Plug-ins
General;Allgemein
Back;Zurück

#
# Help text
#
_help_art;Eine Bilddatei-Quelle, welche im Thema verfügbar ist
_help_art_add;Füge eine neue Bilddatei-Quelle (Marquees, Screenshots etc.) hinzu
_help_art_label;Kennzeichnung zur Identikikation dieser Bilddatei-Quelle (verwendet in Themen)
_help_art_path;Der Pfad zu den Dateien für diese Bilddatei. Mehrere Pfade können durch Semikolon getrennt werden.
_help_autolaunch_last_game;Beim Hochfahren automatisch das zuletzt gespielte Spiel starten
_help_back;Menü verlassen
_help_control_select;Definiere die Taste(n), um die aktuelle Auswahl starten
_help_control_up;Definiere die Taste(n), um die Auswahl nach oben zu bewegen
_help_control_down;Definiere die Taste(n), um die Auswahl nach unten zu bewegen
_help_control_page_up;Definiere die Taste(n), um die Auswahl eine Seite nach oben zu bewegen
_help_control_page_down;Definiere die Taste(n), um die Auswahl eine Seite nach unten zu bewegen
_help_control_prev_display;Definiere die Taste(n), um zum vorigen Bildschirm zu springen
_help_control_next_display;Definiere die Taste(n), um zum nächsten Bildschirm zu springen
_help_control_displays_menu;Definiere die Taste(n), um das "Bildschirm Menü" anzuzeigen
_help_control_prev_filter;Definiere die Taste(n), um zum vorigen Filter zu springen
_help_control_next_filter;Definiere die Taste(n), um zum nächsten Filter zu springen
_help_control_filters_menu;Definiere die Taste(n), um das "Filter Menü" anzuzeigen
_help_control_toggle_layout;Definiere die Taste(n), die umschalten welches Themen-Script genutzt wird (Es hängt aber vom verwendeten Thema ab, ob dies überhaupt etwas bewirkt)
_help_control_toggle_movie;Definiere die Taste(n), die umschalten ob Videos abgespielt werden oder nicht
_help_control_toggle_mute;Definiere die Taste(n), die die Frontend-Klänge stumm/laut schalten
_help_control_toggle_rotate_right;Definiere die Taste(n), die umschalten ob der Bildschirm 90 Grad nach rechts gedreht werden soll
_help_control_toggle_flip;Definiere die Taste(n), die umschalten ob der Bildschirm 180 Grad gedreht werden soll
_help_control_toggle_rotate_left;Definiere die Taste(n), die umschalten ob der Bildschirm 90 Grad nach links gedreht werden soll
_help_control_exit;Definiere die Taste(n), um das Frontend zu verlassen
_help_control_exit_no_menu;Definiere die Taste(n), um das Frontend unmittelbar zum Desktop zu verlassen
_help_control_screenshot;Definiere die Taste(n), um das einen Screenshot vom Frontend zu machen
_help_control_configure;Definiere die Taste(n), um das "Konfigurations Menu" anzuzeigen
_help_control_random_game;Definiere die Taste(n), die ein zufälliges Spiel aus der aktuellen Liste wählen
_help_control_replay_last_game;Definiere die Taste(n), die das zuletzt gespielte Spiel erneut starten
_help_control_add_favourite;Definiere die Taste(n), um das momentan gewählten Spiel als Favoriten zu markiern/löschen
_help_control_prev_favourite;Definiere die Taste(n), um zum vorigen Favoriten zu springen
_help_control_next_favourite;Definiere die Taste(n), um zum nächsten Favoriten zu springen
_help_control_add_tags;Definiere die Taste(n), um Markierungen zum momentan gewählten Spiel hinzuzufügen/zu löschen
_help_control_screen_saver;Definiere die Taste(n), die den Bildschirmschoner starten
_help_control_prev_letter;Definiere die Taste(n), um zum vorigen Buchstaben zu springen
_help_control_next_letter;Definiere die Taste(n), um zum nächsten Buchstaben zu springen
_help_control_custom1;Definiere die Taste(n) für "Eigendefiniert1" 
_help_control_custom2;Definiere die Taste(n) für "Eigendefiniert2"
_help_confirm_favs;Das Hinzufügen/Löschen zu den Favoriten bestätigen
_help_controls;Konfiguriere die Joystick-, Tastatur- und Maus-Eingaben die Attract-Mode steuern
_help_default_font;Bezeichnung der zu nutzenden Standard-Schriftart
_help_display_name;Der Titel dieses Bildschirms
_help_display_layout;Welches Thema soll dieser Bildschirm nutzen
_help_display_romlist;Die Sammlung/Romliste, die für diesen Bildschirm verwendet wird
_help_display_filter;Konfiguriere diesen Filter vom Filter-Set des Bildschirms
_help_display_global_filter;Konfiguriere globale Filterregeln, die auf jeden Eintrag in der Sammlung/Romliste dieses Bildschirm angewendet werden
_help_display_add_filter;Füge einen Filter dem Filter-Set dieses Bildschirm hinzu
_help_display_layout_options;Konfiguriere alle Themen-spezifischen Optionen
_help_display_delete;Diesen Bildschirm löschen
_help_display_sel;Konfiguriere Bildschirm
_help_display_add;Neuen Bildschirm hinzufügen
_help_displays_menu_exit;Lege fest, ob eine Beenden-Option im "Bildschirm Menü" verfügbar sein soll
_help_display_global_filter;Konfiguriere die globalen Filterregeln, die auf jeden Eintrag in der Sammlung/Romliste dieses Bildschirm angewendet werden
_help_displays;Konfiguriere die Romlisten/Themen-Gruppierungen (die "Bildschirme") welche in Attract-Mode zum Durchblättern verfügbar sind
_help_emu_scrape_artwork;Scrape fehlende Bilddateien für diesen Emulator von TheGamesDB.net und mamedb.com
_help_emu_executable;Der komplette Pfad und Bezeichnung der Emulator Executable. $HOME wird durch die Homedir des Users ersetzt
_help_emu_args;Die Kommandozeilenargumente für diesen Emulator. Folgende Einträge werden entsprechend ersetzt: [name], [romext], [rompath], [emulator], [romfilename]
_help_emu_rompath;Der Pfad zu den ROMs für diesen Emulator. Mehrere Pfade können durch Semikolon getrennt werden.
_help_emu_romext;Die ROM Dateiendung(en) für diesen Emulator (z.B. .zip). Mehrere Endungen können durch Semikolon getrennt werden. Gib "<DIR>" als Eintrag an, falls die Spiele in separaten Unterverzeichnissen gespeichert sind
_help_emu_import_extras;Pfad zu beliebigen zusätzlichen Dateien welche gelesen werden müssen wenn eine Romliste für diesen Emulator generiert wird. Unterstützte Dateien sind: catver.ini (für Spiele Kategorien) und nplayers.ini (für Anzahl an Spielern).  Mehrere Dateipfade können durch Semikolon getrennt werden.
_help_emu_system;Die System-Kennung(en) für diesen Emulator.  Mehrere Werte können durch Semikolon getrennt werden.
_help_emu_info_source;Verwende "mame" falls der Emulator mame -listxml Ausgabe bereitstellt, "mess" für mess -listsoftware Ausgabe, "thegamesdb.net" um Daten von thegamesdb.net zu scrapen, oder "steam" um von einer Steam-Installation zu lesen. "mess" und "thegamesdb.net" benötigen zusätzlich die Konfiguration einer System-Kennung welche von diesen Ressourcen erkannt wird
_help_emu_minimum_run_time;Definiere eine minimale Laufzeit (in Sekunden).  Attract-Mode wird nach dem Lauf dieses Emulators warten bis die minimale Zeit verstrichen ist und es zum Vordergund-Fenster wird. Dies wird speziell benötigt, um Steam korrekt unter Windows auszuführen. Lass es auf 0 stehen, ausser du weisst, dass du es benötigst
_help_emu_gen_romlist;Generiere eine Romliste, indem der eingestellte ROM-Pfad nach ROMs mit der definierten Endung durchsucht wird. Falls verfügbar, werden XML-Informationen und zusätzliche Import-Dateien mit einbezogen.
_help_emu_exit_hotkey;Definiere einen globalen Hotkey, um den Emulator zu verlassen.  Attract-Mode wird den Emulator Prozess beenden, wenn dieser Hotkey betätigt wird.
_help_emu_delete;Lösche den Eintrag für diesen Emulator
_help_emu_sel;Konfiguriere Emulator
_help_emu_add;Neuen Emulator hinzufügen
_help_emulators;Konfiguriere verfügbare Spielsysteme und Emulatoren
_help_exit_command;Befehl der ausgeführt wird, wenn Beenden (Bestätigen) gewählt wird [z.B. "sudo shutdown"]
_help_filter_name;Bezeichnung für diesen Filter
_help_filter_rule;Konfiguriere Filterregel
_help_filter_add_rule;Diesem Filter eine Regel hinzufügen
_help_filter_sort_by;Das Spiel-Informationsattribut nach dem du die Sammlung/Romliste sortieren möchtest. Stelle auf "Keine Sortierung" um die Sortierung der Quell-Sammlung/Romliste zu verwenden
_help_filter_list_limit;Setze dies zu einem Wert ungleich Null um die Größe der sortierten Liste zu limitieren. Verwende einen positiven Wert für die ersten X Einträge (z.B. "10" für die ersten 10 Einträge), einen negativen Wert für die letzten X Einträge (z.B. "-25" für die letzten 25 Einträge), oder "0" für alle
_help_filter_delete;Diesen Filter löschen
_help_filter_wrap_mode;Definiere was passieren soll wenn die "Nächster Filter" oder "Vorheriger Filter" Aktionen das Ende Filterliste erreichen
_help_filter_delete;Lösche diesen Filter
_help_font_path;Die Verzeichnisse mit den Schriftarten. Mehrere Verzeichnisse können angegeben werden, durch Semikolon separiert.  Attract-Mode wird diese Verzeichnisse rekursiv durchsuchen um die angegebene Schriftart zu finden
_help_hide_brackets;Verberge bei der Anzeige der Spieletitel den Text in Klammern 
_help_input_action;
_help_input_delete;Dieses Steuerungs-Mapping löschen
_help_input_add;Dieser Aktion ein neues Steuerungs-Mapping zuordnen
_help_intro;Intro konfigurieren
_help_joystick_threshold;Der Schwellwert um Joystick-Bewegungen noch zu erkennen, von 1 bis 100 (100=am wenigsten empfindlich)
_help_misc;Konfiguriere sonstige Einstellungen
_help_mouse_threshold;Der Schwellwert um Maus-Bewegungen noch zu erkennen, von 1 bis 100 (100=am wenigsten empfindlich)
_help_plugin_command;Die ausführbare Datei, welche mit diesem Plug-in verknüpft ist
_help_plugin_enabled;Festlegen, ob dieses Plug-in aktiviert ist
_help_plugin_sel;Konfiguriere Plug-in
_help_plugins;Konfiguriere verfügbare Plug-ins
_help_rule_target;Das Spiel-Informationsattribut basierend auf dem du filtern möchtest
_help_rule_comp;Vergleichstyp für diesen Filter
_help_rule_value;The reguläre Ausdruckswert nach dem gefiltert wird. Wenn zum Beispiel der Filter auf "Jahr" und der Vergleichswert auf "ist gleich" gesetzt wird, wird ein Wert "1984" das Jahr 1984 filtern, "198." jedes Jahr in den Achtzigern und "(198.)|(199.)" jedes Jahr in den 80er oder 90ern
_help_rule_delete;Diese Filterregel löschen
_help_scrape_snaps;Lege fest ob, Spiel Snapshots während des Scrapens heruntergeladen werden sollen
_help_scrape_marquees;Lege fest ob, Spiel Marquees und Banner während des Scrapens heruntergeladen werden sollen
_help_scrape_flyers;Lege fest ob, Spiel Flyers und Box Cover während des Scrapens heruntergeladen werden sollen
_help_scrape_wheels;Lege fest ob, Spiel Logos während des Scrapens heruntergeladen werden sollen
_help_scrape_fanart;Lege fest ob, Spiel Fanart während des Scrapens heruntergeladen werden sollen
_help_scrape_vids;Lege fest ob, Videos der Spiele während des Scrapens heruntergeladen werden sollen
_help_scraper;Konfiguriere die Bilddatei-Scraper Einstellungen
_help_sound;Konfiguriere Klang-Lautstärke, Klang->Ereignis Zuordnungen und den Umgebungs-Soundtrack
_help_screen_saver;Konfiguriere Bildschirmschoner
_help_screen_saver_timeout;Die Wartezeit in Sekunden, bevor der Bildschirmschoner aktiv wird. 0 zum Deaktivieren
_help_sound_sel;Weise diesem Ereignis/dieser Aktion einen Klang zu
_help_track_usage;Konfiguriere, ob Attract-Mode die Nutzung protokollieren soll (gespielte Zeit und wie-oft-gespielt pro Spiel)
_help_volume;Gültige Lautstärke Einstellungen gehen von 0 (stumm) bis 100 
_help_window_mode;Lege fest, ob Attract-Mode in einem Fenster läuft oder den Bildschirm füllt
_sort_regexp;^(Vs\. The |The |Vs\. )

System Identifier;System Kennung
Info Source/Scraper;Info Quelle/Scraper
Minimum Run Time;Minimale Laufzeit
Exit Hotkey;Hotkey zum Beenden
Sort By;Sortiert nach
No Sort;Keine Sortierung
AltRomname;Alternativer Rom-Name
AltTitle;Alternativer Titel
Tags;Markierungen
PlayedCount;Male gespielt
PlayedTime;Zeit gespielt
List Limit;Limit für die Liste 
Add/Remove Tags;Markierungen hinzufügen/löschen
Previous Letter;Voriger Buchstabe
Next Letter;Nächster Buchstabe
Track Usage;Protokolliere Nutzung
Filter Wrap Mode;Rolliermodus des Filters
Wrap within List (Default);Rollieren innerhalb der Liste (Standard)
Jump to Next List;Springe zur nächsten Liste
No Wrap;Kein Rollieren
Window Mode;Fenstermodus
Fill Screen (Default);Bildschirm ausfüllen (Standard)
Fullscreen Mode;Vollbildmodus
Window;Fenster
Empty;Leer
$1 Rule(s);$1 Regel(n)
Global Filter;Globaler Filter
Custom1;Eigendefiniert1
Custom2;Eigendefiniert2
Custom3;Eigendefiniert3
Custom4;Eigendefiniert4
Custom5;Eigendefiniert5
Custom6;Eigendefiniert6
Basic Movie;Basis Video
Movie collage;Video Collage
Image collage;Bilder Collage
Overlay Artwork;Bilddatei als Overlay
Play Sound;Klang abspielen
Preserve Aspect Ratio;Seitenverhältnis beibehalten
 
# Needs translation
Disabled;ausgeschaltet
Scraper;Scraper
Scrape Artwork;Scrape Bilddateien
Configure / Scraper;Konfiguration / Scraper
Scrape Snaps;Scrape Snaps
Scrape Marquees;Scrape Marquees
Scrape Flyers/Boxart;Scrape Flyers/Boxart
Scrape Game Logos (Wheel Art);Scrape Spiele Logos (Wheel Art)
Scraping Artwork: $1%;Scrape Bilddatei: $1%
