#@Español
#
# Interface strings
#
$1 Rule(s);$1 Regla(s)
Action;Acción
Add Artwork;Agregar tema
Add Emulator;Agregar emulador
Add Filter;Agregar filtro
Add Input;Agregar control
Add New Display;Agregar nueva pantalla
Add Rule;Agregar regla
Add/Remove Favourite;Agregar/eliminar favoritos
Add/Remove Tags;Agregar/Remover etiquetas
Additional Import File(s);Archivos de importación adicionales
All;Todos
Allow Exit from 'Displays Menu';Permitir salir desde el 'menú de pantallas'
AltRomname;Nombre de rom alternativo
AltTitle;Título alternativo
Ambient Soundtrack;Canción de sonido de ambiente
Ambient Volume;Volumen de ambiente
Artwork Label;Nombre del tema
Artwork Path;Ruta del tema
Back;Volver
Category;Categoría
CloneOf;Clon de
Collection/Rom List;Colección/Lista de roms
Command;Comandos
Command Arguments;Argumentos
Comparison;Comparación
Configure;Configuración
Configure / Controls;Configuración / Controles
Configure / Displays;Configuración / Pantallas
Configure / Emulators;Configuración / Emuladores
Configure / Miscellaneous;Configuración / Varios
Configure / Plug-ins;Configuración / Plugins
Configure / Scraper;Configure / Scraper
Configure / Sound;Configuración / Sonido
Configure Plug-in;Configuración de Plugins
Configure Screen Saver;Configurar el protector de pantalla
Confirm Favourites;Confirmar favoritos
Control;Controles
Controls;Controles
Custom1; Personalizado 1
Custom2; Personalizado 2
Custom3; Personalizado 3
Custom4; Personalizado 4
Custom5; Personalizado 5
Custom6; Personalizado 6
Default Font;Fuente por defecto
Delete display '$1'?;¿Desea borrar la pantalla '$1'?
Delete emulator '$1'?;¿Desea borrar el emulador '$1'?
Delete filter '$1'?;¿Desea borrar el filtro '$1'?
Delete this Display;Borrar esta pantalla
Delete this Emulator;Suprimir este emulador
Delete this Filter;Borrar este filtro
Delete this Rule;Borrar esta regla
Disabled;Disabled
Display Edit;Editar pantalla
DisplayCount;Contador de pantalla
DisplayType;Tipo de pantalla
Displays;Pantallas
Displays Menu;Mostrar menú
Down;Abajo
Edit Artwork;Modificar tema
Edit Emulator;Modificar emulador
Edit Input;Editar controles
Empty;Vacío
Emulator;Emulador
Emulator Name;Nombre del emulador
Emulators;Emuladores
Enabled;activado
Enter Display Name;Ingrese el nombre de la pantalla
Enter Emulator Name;Ingrese el nombre del emulador
Enter Filter Name;Ingrese el nombre para el filtro
Executable;Ejecutable
Exit;Salir (Confirmación)
Exit Attract-Mode;Salir de Attract-Mode
Exit Attract-Mode?;Salir de Attract-Mode?
Exit Command;Comando de salida
Exit Hotkey; Tecla rápida de salida
Exit to Desktop;Salir a escritorio
Favourite;Favorito
Fill Screen (Default);Llenar pantalla (Por defecto)
Filter;Filtro
Filter Edit;Editar filtro
Filter Name;Nombre del filtro
Filter Value;Valor del filtro
Filter Wrap Mode;Modo de ciclado de filtro
Filters Menu;Menú de filtros
Flip;Invertir
Font Path;Ruta de fuentes
Fullscreen Mode;Modo pantalla completa
Game Return Sound;Sonido de retorno al juego
General;General
Generate Collection/Rom List;Generar lista de roms
Generating Rom List: $1%;Generación de lista de roms: $1%
Global Filter;Filtro global
Hide Brackets in Game Title;Esconder paréntesis en títutlos de juegos
Info Source/Scraper;Fuente de información/Scraper
Joystick Threshold;Umbral de la palanca
Jump to Next Display;Saltar a la siguiente pantalla 
Language;Idioma
Layout;Tema
Layout Options;Opciones de temas
Left;Izquierda
List Limit;Límite de lista
Manufacturer;Fabricante
Mouse Threshold;Umbral del ratón
Movie Volume;Volumen de videos
Name;Nombre
Next Display;Pantalla siguiente
Next Favourite;Siguiente favorito
Next Filter;Filtro posterior
Next Letter;Letra siguiente
Next Page;Página anterior
No;No
No Sort;No ordenar
No Wrap;No ciclar
None;Ninguno
OR;O
Overwrite existing '$1' list?;¿Desea sobreescribir la lista de roms '$1'?
Play Sound;Reproducir sonido
PlayedCount;Cuenta de partidas
PlayedTime;Tiempo jugado
Players;Jugadores
Plug-ins;Plug-ins
Press Input;Presionar control
Previous Display;Pantalla previa
Previous Favourite;Anterior favorito
Previous Filter;Filtro anterior
Previous Letter;Letra previa
Previous Page;Página posterior
Random Game;Juego aleatorio
Remove Input;Eliminar control
Replay Last Game;Repetir el último juego
Right;Derecha
Rom Extension(s);Extension(es) de roms
Rom Path(s);Ruta(s) de roms
Rom path '$1' not found, proceed anyways?;Ruta de roms '$1' no encontrada, ¿desea continuar?
Rotation;Rotación
Rule;Regla
Rule Edit;Editar reglas
Scrape Artwork;Scrape Artwork
Scrape Flyers/Boxart;Scrape Flyers/Boxart
Scrape Game Logos (Wheel Art);Scrape Game Logos (Wheel Art)
Scrape Marquees;Scrape Marquees
Scrape Snaps;Scrape Snaps
Scraper;Scraper
Scraping Artwork: $1%;Scraping Artwork: $1%
Screen Saver;Potector de pantalla
Screen Saver Timeout;Límite de tiempo para el salvapantalla
Screenshot;Captura de pantalla
Select;Seleccionar
Sort By;Ordenado por
Sound;Sonido
Sound Volume;Volumen general
Startup Sound;Sonido de inicio
Status;Estado
System Identifier;Identificador de sistema
Tags;Etiquetas
Target;Objetivo
The name for this filter;Nombre para este filtro
This will overwrite an existing mapping ($1).  Proceed?;Esto sobreescribirá un mapeo de controles existente ($1). ¿Desea continuar?
Title;Título
Toggle Flip;Invertir
Toggle Layout;Cambiar tema
Toggle Movie;Cambiar video
Toggle Mute;Silenciar
Toggle Rotate Left;Rotar a la izquierda
Toggle Rotate Right;Rotar a la derecha
Track Usage;Usar seguimiento
Up;Arriba
Window;Ventana
Window Mode;Modo ventana
Wrap within Display (Default);Ciclar dentro de la pantalla (Por defecto)
Wrote $1 entries to Collection/Rom List;Se agregaron $1 entradas a la lista de roms
Year;Año
Yes;Si
contains;contiene
does not contain;no contiene
does not equal;no es igual a
equals;igual

#
# Help messages
#
_help_art;Una fuente de artwork disponible para ser usado por el temas
_help_art_add;Agregar una nueva fuente de artwork (marquesinas, capturas de pantalla, etc.)
_help_art_label;Etiqueta que identifica este artwork (usado por los temas)
_help_art_path;Ruta a los archivos de este artwork. Es posible ingresar multiples rutas separadas por punto y coma.
_help_back;Salir del menu
_help_confirm_favs;Confirma la adición/remoción a favoritos
_help_control_add_favourite;Configura el(los) control(es) que marca/desmarca el juego actualmente seleccionado como favorito
_help_control_add_tags;Configura el(los) control(es) que agragan/remueven etiquetas del juego actualmente seleccionado
_help_control_configure;Configura el(los) control(es) que muestra el "Menú de configuración"
_help_control_custom1;Configura el(los) control(es) "Personalizado1"
_help_control_custom2;Configura el(los) control(es) "Personalizado2"
_help_control_displays_menu;Configurar el(los) control(es) que "muestra el menú"
_help_control_down;Configurar el(los) control(es) que mueven hacia abajo la selección
_help_control_exit;Configura el(los) control(es) que cierran el frontend
_help_control_exit_to_desktop;Configura el(los) control(es) que sale del frontend inmediatamente al escritorio
_help_control_filters_menu;Configurar el(los) control(es) que muestran el "Menú de filtros"
_help_control_next_display;Configurar el(los) control(es) que mueven hacia la pantalla siguiente
_help_control_next_favourite;Configura el(los) control(es) que mueven hacia el favorito siguiente
_help_control_next_filter;Configurar el(los) control(es) que mueven hacia el filtro siguiente
_help_control_next_letter;Configura el(los) control(es) que mueve hacia la letra siguiente
_help_control_next_page;Configurar el(los) control(es) que mueven hacia abajo una página la selección
_help_control_prev_display;Configurar el(los) control(es) que mueven hacia la pantalla previa
_help_control_prev_favourite;Configura el(los) control(es) que mueven hacia el favorito previo
_help_control_prev_filter;Configurar el(los) control(es) que mueven hacia el filtro previo
_help_control_prev_letter;Configura el(los) control(es) que mueve hacia la letra previa
_help_control_prev_page;Configurar el(los) control(es) que mueven hacia arriba una página la selección
_help_control_random_game;Configura el(los) control(es) que selecciona un jego aleatorio de la lista actual
_help_control_replay_last_game;Configura el(los) control(es) que relanza el último juego jugado
_help_control_screen_saver;Configura el(los) control(es) que lanzan el protector de pantalla
_help_control_screenshot;Configura el(los) control(es) que toma una captura de pantalla del frontend
_help_control_select;Configura los el(los) control(es) que lanzan la selción actual
_help_control_toggle_flip;Configura el(los) control(es) que cambia si la pantalla debe ser rotada o no 180 grados
_help_control_toggle_layout;Configura el(los) control(es) que cambia el script de tema a usar (Depende del tema que está usando si esto hace algo)
_help_control_toggle_movie;Configura el(los) control(es) que cambia si los videos son o no reproducidos
_help_control_toggle_mute;Configura el(los) control(es) que silencia o no el sonido del frontend
_help_control_toggle_rotate_left;Configura el(los) control(es) que cambia si la pantalla debe ser rotada o no 90 grados a la izquierda
_help_control_toggle_rotate_right;Configura el(los) control(es) que cambia si lapantalla debe ser rotada o no 90 grados a la derecha
_help_control_up;Configurar el(los) control(es) que mueven hacia arriba la selección
_help_controls;Configura las entradas de palanca, teclado y ratón que controlan Attract-Mode
_help_default_font;Nombre de la fuente por defecto a usar
_help_display_add;Agragar una nueva pantalla
_help_display_add_filter;Agregar un filtro a este conjunto de filtros de pantalla
_help_display_delete;Borra esta pantalla
_help_display_filter;Configura este filtro desde el conjunto de filtros de pantalla
_help_display_global_filter;Configura reglas globales de filtros que son aplicados a cada entrada de la lista de roms de esta pantalla
_help_display_layout;Tema usado para esta pantalla
_help_display_layout_options;Configurar cualquier opción especifica de temas
_help_display_name;Nombre de la pantalla
_help_display_romlist;Colección/lista de roms usada para esta pantalla
_help_display_sel;Configurar pantalla
_help_displays;Configura los grupos de lista de roms/temas ("Pantallas") que están disponibles para hacer circular enAttract-Mode
_help_displays_menu_exit;configura si la opción de Salir debe ser provista en el "menú de pantallas"
_help_emu_add;Agrega un nuevo emulador
_help_emu_args;Argumento de linea de comandos usado por este emulador.  Los siguientes pueden ser propiamente sustituidos: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_emu_delete;Borra la entrada para este emulador
_help_emu_executable;Ruta completa y nombre del ejecutable del emulador. $HOME es reemplazado por con el directorio home del usuario
_help_emu_exit_hotkey;Configura una tecla global para salir del emulador. Attract-Mode terminará el proceso del emulador si esta tecla es presionada
_help_emu_gen_romlist;Genera una lista de roms buscando en las rutas de roms configuradas con las extensiones configuradas, incorporando XML e importando información adicional a la lista generada (si está disponible)
_help_emu_import_extras;Ruta de cualquier archivo adicional que neceiste ser leido cuando se genera la lista de roms para este emulador.  Los archivos soportados son: catver.ini (para categorias de juegos) y nplayers.ini (para el número de jugadores). Es posible ingresar multiples rutas separadas por punto y coma.
_help_emu_info_source;Use "listxml" si el emulador prove la salida de mame -listxml, "listsoftware" para la salida de mame/mess -listsoftware, "thegamesdb.net" para extraer información desde thegamesdb.net, o "steam" para leer desde una instalación de steam.  "listsoftware" y "thegamesdb.net" también requieren que sea configurado un identificador de sistema reconocible por esas fuentes
_help_emu_nb_mode_wait;Configura un tiempo mínimo de ejecución (en segundos).  Attract-Mode esperará después de ejecutar este emulador hasta que haya transcurrido el tiempo mínimo de ejecución y pasará a ejecución de fondo. Esto necesita ser configurado por Steam para funcionar correctamente en Windows. Configure esto en 0 a menos que sepa que lo necesita
_help_emu_romext;Extensión(es) para este emulador (por ej. .zip). Es posible ingresar multiples extensiones separadas por punto y coma. Especificar "<DIR>" como entrada si los juegos se encuientran en subdirectorios separados
_help_emu_rompath;Ruta a las roms para este emulador.  Es posible ingresar multiples rutas separadas por punto y coma.
_help_emu_scrape_artwork;Scrape missing artwork images for this emulator from TheGamesDB.net and mamedb.com
_help_emu_sel;Configura el emulador
_help_emu_system;Identificador(es) de sistema para este emulador. Es posible ingresar multiples valores separadas por punto y coma.
_help_emulators;Configurar configuraciones del emulador
_help_exit_command;Comando seleccionado cuando Salir (con confirmación) es seleccionado [por ej. "sudo shutdown"]
_help_filter_add_rule;Agrega una regla para este filtro
_help_filter_delete;Borrar este filtro
_help_filter_list_limit;Configurar esto a cero si desea limitar el tamaño de una lista ordenada. Use un valor positivo para las X primeras entradas (por ej. "10" entrega las primeras 10 entradas), un valor negativo para las últimas X entradas (por ej. "-25" entrega las últimas 25 entradas), o "0" para ilimitado
_help_filter_name;Name ára este filtro
_help_filter_rule;Configura regla para el filtro
_help_filter_sort_by;Atriburo del juego a partir del cual desea que la colección/lista de roms sea ordenada. Configure a "No ordenar" para mantener el orden de la colección/lista de romo
_help_filter_wrap_mode;Configura que pasa cuando el "Siguiente filtro" o "Filtro previo" alcanza el final del conjunto de filtros
_help_font_path; Direcctorio de fuentes. Es posible especificar multiples directorios separados pro punto y coma.  Attract-Mode buscará recursivamente estos directorios para encontrar una fuente especificada
_help_hide_brackets;Esconde Hide el texto en paréntesis cuando se muestran los títulos de los juegos
_help_input_action;
_help_input_add;Agrega una nueva asignación de controles para esta acción
_help_input_delete;Remover esta asignación de controles
_help_intro;Configure intro
_help_joystick_threshold;Umbral para los movimientos de palanca registrados, de 1 a 100 (100=menos sensible)
_help_misc;Configuraciones varias
_help_mouse_threshold;Umbral para los movimientos del ratón, de 1 a 100 (100=menos sensible)
_help_plugin_command;Ejecutable asociado a este plugin
_help_plugin_enabled;Configura si este plugin está o no habilitado
_help_plugin_sel;Configurar plugin
_help_plugins;Configura los plugins disponibles
_help_rule_comp;Tipo de comparación para el filtro
_help_rule_delete;Borra esta regla de filtro
_help_rule_target;El atributo de información del juego en el cual quiere basar el fitro
_help_rule_value;Expresión regular para filtrar. Por ejemplo, si el objetivo del filtro es "Año" y la comparación es "igual",un valor de "1984" coincidirá con el año 1984, "198." coincidirá con cualquier año de los 80s, y "(198.)|(199.)" coincidirá con cualquier año de los 80s o 90s
_help_scrape_fanart;Set whether game fan art should be downloaded when scraping
_help_scrape_flyers;Set whether game flyers and box covers should be downloaded when scraping
_help_scrape_marquees;Set whether game marquees and banners should be downloaded when scraping
_help_scrape_snaps;Set whether game snapshots should be downloaded when scraping
_help_scrape_vids;Set whether game videos should be downloaded when scraping
_help_scrape_wheels;Set whether game logos should be downloaded when scraping
_help_scraper;Configure artwork scraper settings
_help_screen_saver;Configura ell protector de pantalla
_help_screen_saver_timeout;Cantidad de tiempo en segundos a esperar antes de lanzar el protector de pantalla. 0 para deshabilitar
_help_sound;Configura volumenes de sonidos, asignaciones de eventos de sonido y el tema (canción) de ambiente
_help_sound_sel;Asigna un sonido a este evento/acción
_help_track_usage;Configura si Attract-Mode debería registrar el uso (tiempo jugado y cuenta de partidas para cada juego)
_help_volume;Las configuraciones válidas se volumen van de 0 (silencio) a 100 
_help_window_mode;configura si Attract-Mode llena lapantalla o se ejecuta en una ventana
_sort_regexp;^(Vs\. The |The |Vs\. )

#
# Extra strings provided by translation
#
Add a rule to this filter;Agregar una regla para este filtro
Ambient Sounds;Sondio ambiente
Basic Movie;Video básico
Configure available emulators;Configurar los emuladores disponibles
Configure filter rule;Configuración de la regla del filtro
Custom 1;Personalizado 1
Custom 2;Personalizado 2
Delete this filter;Borrar este filtro
Image collage;Collage de imágenes
Launch Last Game on Startup;Lanzar último juego en el inicio
Minimum Run Time;Tiempo mínimo de ejecución
Movie collage;Collage de video
Overlay Artwork;superposición de artworks
Preserve Aspect Ratio;Preservar relación de aspecto
XML Mode;Modo XML
en;English
es;Español
fr;Français
_help_autolaunch_last_game;Lanza automaticamente el útlito juego jugado en el inicio

#@DONE_TRANSLATED
#
# Strings still needing translation
#
Add '$1' to Favourites?;Add '$1' to Favourites?
Add Exception;Add Exception
Add tag: '$1';Add tag: '$1'
Artwork Name;Artwork Name
Attract-Mode detected emulator(s) that can be imported automatically.  Import them now?;Attract-Mode detected emulator(s) that can be imported automatically.  Import them now?
Blank Game;Blank Game
Buttons;Buttons
Clear Hotkey?;Clear Hotkey?
Configure / Displays Menu;Configure / Displays Menu
Configure / Joystick Mapping;Configure / Joystick Mapping
Configure Intro;Configure Intro
Configure Layout;Configure Layout
Confirm Exit;Confirm Exit
Create new tag;Create new tag
Custom Arguments;Custom Arguments
Custom Executable;Custom Executable
Default;Default
Default Action;Default Action
Delete game '$1'?;Delete game '$1'?
Delete shortcut '$1'?;Delete shortcut '$1'?
Delete this Game;Delete this Game
Delete this Shortcut;Delete this Shortcut
Display Name;Display Name
Edit Game;Edit Game
Edit Shortcut;Edit Shortcut
Enable Multiple Monitors;Enable Multiple Monitors
Enter Romlist Name;Enter Romlist Name
Enter new tag name;Enter new tag name
Exception;Exception
Exception Edit;Exception Edit
Exit Message;Exit Message
Extra;Extra
FileIsAvailable;FileIsAvailable
Insert Command Shortcut;Insert Command Shortcut
Insert Display Shortcut;Insert Display Shortcut
Insert Game Entry;Insert Game Entry
Insert Menu Entry;Insert Menu Entry
Intro;Intro
Joystick $1;Joystick $1
Joystick Mappings;Joystick Mappings
Launch Last Game;Launch Last Game
Layout File;Layout File
Menu Prompt;Menu Prompt
Menu Style / Layout;Menu Style / Layout
Next Game;Next Game
Non-Blocking Mode Wait;Non-Blocking Mode Wait
Overview;Overview
Pause Hotkey;Pause Hotkey
Please Wait;Please Wait
Press Hotkey;Press Hotkey
Previous Game;Previous Game
Remove '$1' from Favourites?;Remove '$1' from Favourites?
Remove tag: '$1';Remove tag: '$1'
Scrape Fanart;Scrape Fanart
Scrape Videos (MAME only);Scrape Videos (MAME only)
Select template to use for emulator settings;Select template to use for emulator settings
Show Displays Menu;Show Displays Menu
Show Last Selection (Default);Show Last Selection (Default)
Show in Cycle;Show in Cycle
Show in Menu;Show in Menu
Startup Mode;Startup Mode
Video Decoder;Video Decoder
Window (No Border);Window (No Border)
Working Directory;Working Directory
multi;multi
_help_confirm_exit;Confirm before exiting Attact-Mode?
_help_control_back;Set the control(s) that go back
_help_control_custom3;Set the "Custom3" control(s)
_help_control_custom4;Set the "Custom4" control(s)
_help_control_custom5;Set the "Custom5" control(s)
_help_control_custom6;Set the "Custom6" control(s)
_help_control_edit_game;Set the control(s) to edit the current selection
_help_control_intro;Set the control(s) that show the intro video
_help_control_left;Set the control(s) that move the selection left
_help_control_next_game;Set the control(s) that move to the next game
_help_control_prev_game;Set the control(s) that move to the previous game
_help_control_right;Set the control(s) that move the selection right
_help_display_in_cycle;Include this display in the "Previous Display"/"Next Display" cycle?
_help_display_in_menu;Include this display in the "Displays Menu"?
_help_displays_menu;Configure options for the "Displays Menu"
_help_displays_menu_layout;The layout to use for the 'Displays Menu'. Set to 'Default' to use the frontend's built-in menu
_help_displays_menu_prompt;The 'Displays Menu' prompt (i.e. "Select System")
_help_emu_pause_hotkey;Set a global hotkey to pause the emulator.  When pressed, Attract-Mode will pause the emulator process and return to the frontend. The emulator process can be resumed by selecting the same game again in the frontend.
_help_emu_sel_gen_romlist;Generate a Collection/Romlist containing games for multiple emulators
_help_emu_workdir;The working directory for this emulator.  This is the directory that the frontend runs the emulator from.  Also, any relative rom paths, artwork paths, or additional import file paths are treated as being relative to this directory
_help_exit_message;Alternate message to exit the frontend [i.e. "Shut Down System"]
_help_filter_add_exception;Add an exception to this filter.  If a game matches an exception (and wasn't filtered out by an earlier rule) it will be listed in the filter
_help_filter_exception;Configure this filter exception.  If a game matches an exception it will be listed in the filter.  Rules and exceptions get applied in the order that they are listed
_help_game_custom_args;Set this to override the default command line arguments for this game.  Set this to [nothing] if you want to override with no parameters.  The following get substituted appropriately: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_game_custom_executable;Set this to override the default executable for this game
_help_game_delete;Delete this game from the Romlist
_help_game_edit;Edit this game information
_help_game_overview;Edit game overview
_help_generator_build;Generate romlist with the selected emulator(s)
_help_generator_opt;Set whether this emulator is to be included in the generated romlist
_help_hide_console;Hide console on startup. Note that this only works if starting Attract-Mode from a Windows GUI. If started from an existing console window (e.g. a batch file) then the process will always "attach" to the existing console and output to it.
_help_input_default_action;Set the default behaviour for this control
_help_joystick_map;Map the frontend's joystick slots to specifically named joystick/gamepad devices attached to your computer (You can use this to force the frontend to always use 'Microsoft X-Box 360 pad' as Joystick 0, for example.)
_help_language;Select the language to use in Attract-Mode's user interface
_help_layout_file;Some layouts provide multiple layout*.nut files.  Select which layout file to use
_help_multiple_monitors;Enable the use of multiple monitors by Attract-Mode.  Setting this to 'No' may reduce screen flicker when launching games
_help_shortcut_artwork_name_edit;Optionally provide an artwork name to be associated with this shortcut.  The frontend will try to load artworks with this name when displaying the shortcut
_help_shortcut_delete;Delete this shortcut from the Romlist
_help_shortcut_label_edit;Edit this shortcut's label
_help_shortcut_target_edit;Edit this shortcut's target
_help_startup_mode;Set what should happen when Attract-Mode first starts up
_help_video_decoder;Configure the decoder to use for video playback (if multiple decoders are available)
