#
# Languages
#
Language;Idioma
en;English
fr;Français
es;Español
#
# General
#
Exit Attract-Mode;Salir de Attract-Mode
Exit Attract-Mode?;Salir de Attract-Mode?
Yes;Si
No;No
#
# Emulator Settings Configuration
#
Edit Artwork;Modificar tema
Artwork Label;Nombre del tema
Artwork Path;Ruta del tema
Edit Emulator;Modificar emulador
Emulator Name;Nombre del emulador
Executable;Ejecutable
Command Arguments;Argumentos
Rom Path(s);Ruta(s) de roms
Rom Extension(s);Extension(es) de roms
Additional Import File(s);Archivos de importación adicionales
XML Mode;Modo XML
Add Artwork;Agregar tema
Generate Collection/Rom List;Generar lista de roms
Delete this Emulator;Suprimir este emulador
Generating Rom List: $1%;Generación de lista de roms: $1%
Rom path '$1' not found, proceed anyways?;Ruta de roms '$1' no encontrada, ¿desea continuar?
Overwrite existing '$1' list?;¿Desea sobreescribir la lista de roms '$1'?
Wrote $1 entries to Collection/Rom List;Se agregaron $1 entradas a la lista de roms
Delete emulator '$1'?;¿Desea borrar el emulador '$1'?
Config / Emulators;Configuración / Emuladores
Add Emulator;Agregar emulador
Enter Emulator Name;Ingrese el nombre del emulador
Configure available emulators;Configurar los emuladores disponibles
Exit Hotkey; Tecla rápida de salida
#
# Filter Settings Configuration
#
Enter Filter Name;Ingrese el nombre para el filtro
Rule Edit;Editar reglas
Target;Objetivo
Comparison;Comparación
Filter Value;Valor del filtro
Delete this Rule;Borrar esta regla
Filter Edit;Editar filtro
Filter Name;Nombre del filtro
Rule;Regla
Add Rule;Agregar regla
Delete this Filter;Borrar este filtro
Delete filter '$1'?;¿Desea borrar el filtro '$1'?
All;Todos
Title;Título
Emulator;Emulador
CloneOf;Clon de
Year;Año
Manufacturer;Fabricante
Category;Categoría
Players;Jugadores
Rotation;Rotación
Control;Controles
Status;Estado
DisplayType;Tipo de pantalla
DisplayCount;Contador de pantalla
Favourite;Favorito
equals;igual
does not equal;no es igual a
contains;contiene
does not contain;no contiene
The name for this filter;Nombre para este filtro
Configure filter rule;Configuración de la regla del filtro
Add a rule to this filter;Agregar una regla para este filtro
Delete this filter;Borrar este filtro
#
# Display Settings Configuration
#
Display Edit;Editar pantalla
Layout;Tema
Collection/Rom List;Colección/Lista de roms
Filter;Filtro
Add Filter;Agregar filtro
Delete this Display;Borrar esta pantalla
Delete display '$1'?;¿Desea borrar la pantalla '$1'?
Configure / Displays;Configuración / Pantallas
Add New Display;Agregar nueva pantalla
Enter Display Name;Ingrese el nombre de la pantalla
#
# Input Settings Configuration
#
Edit Input;Editar controles
Action;Acción
Remove Input;Eliminar control
Add Input;Agregar control
Press Input;Presionar control
This will overwrite an existing mapping ($1).  Proceed?;Esto sobreescribirá un mapeo de controles existente ($1). ¿Desea continuar?
Configure / Input;Configuración / Controles
OR;O
Select;Seleccionar
Up;Arriba
Down;Abajo
Page Up;Página posterior
Page Down;Página anterior
Previous Display;Pantalla previa
Next Display;Pantalla siguiente
Displays Menu;Mostrar menú
Previous Filter;Filtro anterior
Next Filter;Filtro posterior
Filters Menu;Menú de filtros
Toggle Layout;Cambiar tema
Toggle Movie;Cambiar video
Toggle Mute;Silenciar
Toggle Rotate Right;Rotar a la derecha
Toggle Flip;Invertir
Toggle Rotate Left;Rotar a la izquierda
Exit (Confirm);Salir (Confirmación)
Exit to Desktop;Salir a escritorio
Screenshot;Captura de pantalla
Configure;Configurar
Random Game;Juego aleatorio
Add/Remove Favourite;Agregar/eliminar favoritos
Next Favourite;Siguiente favorito
Previous Favourite;Anterior favorito
Replay Last Game;Repetir el último juego
Ambient Sounds;Sondio ambiente
Startup Sound;Sonido de inicio
Game Return Sound;Sonido de retorno al juego
Mouse Threshold;Umbral del ratón
Joystick Threshold;Umbral de la palanca
#
# Sound Settings Configuration
#
Configure / Sound;Configuración / Sonido
Sound Volume;Volumen general
Ambient Volume;Volumen de ambiente
Movie Volume;Volumen de videos
Ambient Soundtrack;Canción de sonido de ambiente
#
# Miscellaneous Settings Configuration
#
Configure / Miscellaneous;Configuración / Varios
Hide Brackets in Game Title;Esconder paréntesis en títutlos de juegos
Launch Last Game on Startup;Lanzar último juego en el inicio
Confirm Favourites;Confirmar favoritos
Layout Options;Opciones de temas
None;Ninguno
Right;Derecha
Flip;Invertir
Left;Izquierda
Exit Command;Comando de salida
Default Font;Fuente por defecto
Font Path;Ruta de fuentes
Allow Exit from 'Displays Menu';Permitir salir desde el 'menú de pantallas'
Configure Screen Saver;Configurar el protector de pantalla
Screen Saver Timeout;Límite de tiempo para el salvapantalla
#
# Plug-in Configuration
#
Configure Plug-in;Configuración de Plugins
Name;Nombre
Command;Comandos
Enabled;activado
Configure / Plug-ins;Configuración / Plugins
#
# Configuration Main Menu
#
Configure;Configuración
Emulators;Emuladores
Displays;Pantallas
Controls;Controles
Sound;Sonido
Screen Saver;Potector de pantalla
Plug-ins;Plug-ins
General;General
Back;Volver
#
#
# Help text
#
_help_back;Salir del menu
_help_emulators;Configurar juegos y emuladores disponibles
_help_art_label;Etiqueta que identifica este artwork (usado por los temas)
_help_art_path;Ruta a los archivos de este artwork. Es posible ingresar multiples rutas separadas por punto y coma.
_help_art_add;Agregar una nueva fuente de artwork (marquesinas, capturas de pantalla, etc.)
_help_art;Una fuente de artwork disponible para ser usado por el temas
_help_emu_executable;Ruta completa y nombre del ejecutable del emulador. $HOME es reemplazado por con el directorio home del usuario
_help_emu_args;Argumento de linea de comandos usado por este emulador.  Los siguientes pueden ser propiamente sustituidos: [name], [romext], [rompath], [emulator], [romfilename]
_help_emu_rompath;Ruta a las roms para este emulador.  Es posible ingresar multiples rutas separadas por punto y coma.
_help_emu_romext;Extensión(es) para este emulador (por ej. .zip). Es posible ingresar multiples extensiones separadas por punto y coma. Especificar "<DIR>" como entrada si los juegos se encuientran en subdirectorios separados
_help_emu_import_extras;Ruta de cualquier archivo adicional que neceiste ser leido cuando se genera la lista de roms para este emulador.  Los archivos soportados son: catver.ini (para categorias de juegos) y nplayers.ini (para el número de jugadores). Es posible ingresar multiples rutas separadas por punto y coma.
_help_emu_system;Identificador(es) de sistema para este emulador. Es posible ingresar multiples valores separadas por punto y coma.
_help_emu_info_source;Use "mame" si el emulador prove la salida de mame -listxml, "mess" para la salida de mess -listsoftware, "thegamesdb.net" para extraer información desde thegamesdb.net, o "steam" para leer desde una instalación de steam.  "mess" y "thegamesdb.net" también requieren que sea configurado un identificador de sistema reconocible por esas fuentes
_help_emu_minimum_run_time;Configura un tiempo mínimo de ejecución (en segundos).  Attract-Mode esperará después de ejecutar este emulador hasta que haya transcurrido el tiempo mínimo de ejecución y pasará a ejecución de fondo. Esto necesita ser configurado por Steam para funcionar correctamente en Windows. Configure esto en 0 a menos que sepa que lo necesita
_help_emu_gen_romlist;Genera una lista de roms buscando en las rutas de roms configuradas con las extensiones configuradas, incorporando XML e importando información adicional a la lista generada (si está disponible)
_help_emu_exit_hotkey;Configura una tecla global para salir del emulador. Attract-Mode terminará el proceso del emulador si esta tecla es presionada
_help_emu_delete;Borra la entrada para este emulador
_help_emu_sel;Configura el emulador
_help_emu_add;Agrega un nuevo emulador
_help_filter_name;Name ára este filtro
_help_filter_rule;Configura regla para el filtro
_help_filter_add_rule;Agrega una regla para este filtro
_help_filter_sort_by;Atriburo del juego a partir del cual desea que la colección/lista de roms sea ordenada. Configure a "No ordenar" para mantener el orden de la colección/lista de romo
_help_filter_list_limit;Configurar esto a cero si desea limitar el tamaño de una lista ordenada. Use un valor positivo para las X primeras entradas (por ej. "10" entrega las primeras 10 entradas), un valor negativo para las últimas X entradas (por ej. "-25" entrega las últimas 25 entradas), o "0" para ilimitado
_help_filter_delete;Borrar este filtro
_help_rule_target;El atributo de información del juego en el cual quiere basar el fitro
_help_rule_comp;Tipo de comparación para el filtro
_help_rule_value;Expresión regular para filtrar. Por ejemplo, si el objetivo del filtro es "Año" y la comparación es "igual",un valor de "1984" coincidirá con el año 1984, "198." coincidirá con cualquier año de los 80s, y "(198.)|(199.)" coincidirá con cualquier año de los 80s o 90s
_help_rule_delete;Borra esta regla de filtro
_help_display_name;Nombre de la pantalla
_help_display_layout;Tema usado para esta pantalla
_help_display_romlist;Colección/lista de roms usada para esta pantalla
_help_display_filter;Configura este filtro desde el conjunto de filtros de pantalla
_help_display_global_filter;Configura reglas globales de filtros que son aplicados a cada entrada de la lista de roms de esta pantalla
_help_display_add_filter;Agregar un filtro a este conjunto de filtros de pantalla
_help_display_layout_options;Configurar cualquier opción especifica de temas
_help_display_delete;Borra esta pantalla
_help_display_sel;Configurar pantalla
_help_display_add;Agragar una nueva pantalla
_help_input_action;
_help_input_delete;Remover esta asignación de controles
_help_input_add;Agrega una nueva asignación de controles para esta acción
_help_control_select;Configura los el(los) control(es) que lanzan la selción actual
_help_control_up;Configurar el(los) control(es) que mueven hacia arriba la selección
_help_control_down;Configurar el(los) control(es) que mueven hacia abajo la selección
_help_control_page_up;Configurar el(los) control(es) que mueven hacia arriba una página la selección
_help_control_page_down;Configurar el(los) control(es) que mueven hacia abajo una página la selección
_help_control_prev_display;Configurar el(los) control(es) que mueven hacia la pantalla previa
_help_control_next_display;Configurar el(los) control(es) que mueven hacia la pantalla siguiente
_help_control_displays_menu;Configurar el(los) control(es) que "muestra el menú"
_help_control_prev_filter;Configurar el(los) control(es) que mueven hacia el filtro previo
_help_control_next_filter;Configurar el(los) control(es) que mueven hacia el filtro siguiente
_help_control_filters_menu;Configurar el(los) control(es) que muestran el "Menú de filtros"
_help_control_toggle_layout;Configura el(los) control(es) que cambia el script de tema a usar (Depende del tema que está usando si esto hace algo)
_help_control_toggle_movie;Configura el(los) control(es) que cambia si los videos son o no reproducidos
_help_control_toggle_mute;Configura el(los) control(es) que silencia o no el sonido del frontend
_help_control_toggle_rotate_right;Configura el(los) control(es) que cambia si lapantalla debe ser rotada o no 90 grados a la derecha
_help_control_toggle_flip;Configura el(los) control(es) que cambia si la pantalla debe ser rotada o no 180 grados
_help_control_toggle_rotate_left;Configura el(los) control(es) que cambia si la pantalla debe ser rotada o no 90 grados a la izquierda
_help_control_exit;Configura el(los) control(es) que cierran el frontend
_help_control_exit_no_menu;Configura el(los) control(es) que sale del frontend inmediatamente al escritorio
_help_control_screenshot;Configura el(los) control(es) que toma una captura de pantalla del frontend
_help_control_configure;Configura el(los) control(es) que muestra el "Menú de configuración"
_help_control_random_game;Configura el(los) control(es) que selecciona un jego aleatorio de la lista actual
_help_control_replay_last_game;Configura el(los) control(es) que relanza el último juego jugado
_help_control_add_favourite;Configura el(los) control(es) que marca/desmarca el juego actualmente seleccionado como favorito
_help_control_prev_favourite;Configura el(los) control(es) que mueven hacia el favorito previo
_help_control_next_favourite;Configura el(los) control(es) que mueven hacia el favorito siguiente
_help_control_add_tags;Configura el(los) control(es) que agragan/remueven etiquetas del juego actualmente seleccionado
_help_control_screen_saver;Configura el(los) control(es) que lanzan el protector de pantalla
_help_control_prev_letter;Configura el(los) control(es) que mueve hacia la letra previa
_help_control_next_letter;Configura el(los) control(es) que mueve hacia la letra siguiente
_help_control_custom1;Configura el(los) control(es) "Personalizado1"
_help_control_custom2;Configura el(los) control(es) "Personalizado2"
_help_joystick_threshold;Umbral para los movimientos de palanca registrados, de 1 a 100 (100=menos sensible)
_help_mouse_threshold;Umbral para los movimientos del ratón, de 1 a 100 (100=menos sensible)
_help_plugin_command;Ejecutable asociado a este plugin
_help_plugin_enabled;Configura si este plugin está o no habilitado
_help_plugin_sel;Configurar plugin
_help_volume;Las configuraciones válidas se volumen van de 0 (silencio) a 100 
_help_sound_sel;Asigna un sonido a este evento/acción
_help_exit_command;Comando seleccionado cuando Salir (con confirmación) es seleccionado [por ej. "sudo shutdown"]
_help_default_font;Nombre de la fuente por defecto a usar
_help_font_path; Direcctorio de fuentes. Es posible especificar multiples directorios separados pro punto y coma.  Attract-Mode buscará recursivamente estos directorios para encontrar una fuente especificada
_help_screen_saver_timeout;Cantidad de tiempo en segundos a esperar antes de lanzar el protector de pantalla. 0 para deshabilitar
_help_displays_menu_exit;configura si la opción de Salir debe ser provista en el "menú de pantallas"
_help_hide_brackets;Esconde Hide el texto en paréntesis cuando se muestran los títulos de los juegos
_help_autolaunch_last_game;Lanza automaticamente el útlito juego jugado en el inicio
_help_confirm_favs;Confirma la adición/remoción a favoritos
_help_track_usage;Configura si Attract-Mode debería registrar el uso (tiempo jugado y cuenta de partidas para cada juego)
_help_window_mode;configura si Attract-Mode llena lapantalla o se ejecuta en una ventana
_help_filter_wrap_mode;Configura que pasa cuando el "Siguiente filtro" o "Filtro previo" alcanza el final del conjunto de filtros
_help_emulators;Configurar configuraciones del emulador
_help_displays;Configura los grupos de lista de roms/temas ("Pantallas") que están disponibles para hacer circular enAttract-Mode
_help_controls;Configura las entradas de palanca, teclado y ratón que controlan Attract-Mode
_help_sound;Configura volumenes de sonidos, asignaciones de eventos de sonido y el tema (canción) de ambiente
_help_screen_saver;Configura ell protector de pantalla
_help_plugins;Configura los plugins disponibles
_help_misc;Configuraciones varias
_sort_regexp;^(Vs\. The |The |Vs\. )

System Identifier;Identificador de sistema
Info Source/Scraper;Fuente de información/Scraper
Minimum Run Time;Tiempo mínimo de ejecución
Sort By;Ordenado por
No Sort;No ordenar
AltRomname;Nombre de rom alternativo
AltTitle;Título alternativo
Tags;Etiquetas
PlayedCount;Cuenta de partidas
PlayedTime;Tiempo jugado
List Limit;Límite de lista
Add/Remove Tags;Agregar/Remover etiquetas
Previous Letter;Letra previa
Next Letter;Letra siguiente
Custom 1;Personalizado 1
Custom 2;Personalizado 2
Track Usage;Usar seguimiento
Filter Wrap Mode;Modo de ciclado de filtro
Wrap within Display (Default);Ciclar dentro de la pantalla (Por defecto)
Jump to Next Display;Saltar a la siguiente pantalla 
No Wrap;No ciclar
Window Mode;Modo ventana
Fill Screen (Default);Llenar pantalla (Por defecto)
Fullscreen Mode;Modo pantalla completa
Window;Ventana
Empty;Vacío
$1 Rule(s);$1 Regla(s)
Global Filter;Filtro global
Custom1; Personalizado 1
Custom2; Personalizado 2
Custom3; Personalizado 3
Custom4; Personalizado 4
Custom5; Personalizado 5
Custom6; Personalizado 6
Basic Movie;Video básico
Movie collage;Collage de video
Image collage;Collage de imágenes
Overlay Artwork;superposición de artworks
Play Sound;Reproducir sonido
Preserve Aspect Ratio;Preservar relación de aspecto
 
# Needs translation
Disabled;Disabled
Scraper;Scraper
Scrape Artwork;Scrape Artwork
Configure / Scraper;Configure / Scraper
Scrape Snaps;Scrape Snaps
Scrape Marquees;Scrape Marquees
Scrape Flyers/Boxart;Scrape Flyers/Boxart
Scrape Game Logos (Wheel Art);Scrape Game Logos (Wheel Art)
Scraping Artwork: $1%;Scraping Artwork: $1%

_help_emu_scrape_artwork;Scrape missing artwork images for this emulator from TheGamesDB.net and mamedb.com
_help_scraper;Configure artwork scraper settings
_help_scrape_snaps;Set whether game snapshots should be downloaded when scraping
_help_scrape_marquees;Set whether game marquees and banners should be downloaded when scraping
_help_scrape_flyers;Set whether game flyers and box covers should be downloaded when scraping
_help_scrape_wheels;Set whether game logos should be downloaded when scraping
_help_scrape_fanart;Set whether game fan art should be downloaded when scraping
_help_intro;Configure intro
