#@Français
#
# Interface strings
#
Action;Action
Add Artwork;Ajouter Artwork
Add Emulator;Ajouter un émulateur
Add Filter;Ajouter un filtre
Add Input;Ajouter un contrôle
Add New Display;Ajouter une nouvelle liste
Add Rule;Ajouter une règle
Add/Remove Favourite;Ajouter/Supprimer Favoris
Add/Remove Tags;Ajouter/Supprimer des mots clés
Additional Import File(s);Fichiers additionnels
All;Tous
Allow Exit from 'Displays Menu';Autoriser la sortie depuis la liste des listes
AltRomname;Nom de rom alternatif
AltTitle;Titre alternatif
Ambient Soundtrack;Musique d'ambiance
Ambient Volume;Volume des sons d'ambiances
Artwork Label;Label de l'Artwork
Artwork Path;Chemin de l'Artwork
Back;Retour
Category;Catégorie
CloneOf;Clone de
Collection/Rom List;Liste de ROM
Command;Commandes
Command Arguments;Ligne de commande
Comparison;Comparaison
Configure;Configuration
Configure / Controls;Configuration / Contrôles
Configure / Displays;Configuration / Listes
Configure / Emulators;Configuration / Emulateurs
Configure / Miscellaneous;Configuration / Divers
Configure / Plug-ins;Configuration / Plug-in
Configure / Scraper;Configurer l'aspiration
Configure / Sound;Configuration / Son
Configure Plug-in;Configurer Plug-in
Configure Screen Saver;Configurer l'économiseur d'écran
Confirm Favourites;Confirmer les favoris
Control;Contrôle
Controls;Contrôles
Custom1;Custom1
Custom2;Custom2
Custom3;Custom3
Custom4;Custom4
Custom5;Custom5
Custom6;Custom6
Default Font;Police par défaut
Delete display '$1'?;Supprimer la liste '$1'?
Delete emulator '$1'?;Supprimer l'émulateur '$1'?
Delete filter '$1'?;Supprimer le filtre '$1'?
Delete this Display;Supprimer cette liste
Delete this Emulator;Supprimer cet émulateur
Delete this Filter;Supprimer ce filtre
Delete this Rule;Supprimer cette règle
Disabled;Désactivé
Display Edit;Edition de la liste
Display Name;Nom de la liste
DisplayCount;Afficher compteur
DisplayType;Afficher type
Displays;Listes d'affichage
Displays Menu;Liste des Listes d'affichage
Down;Bas
Edit Artwork;Modifier l'Artwork
Edit Emulator;Modifier l'émulateur
Edit Input;Editer le contrôle
Emulator;Emulateur
Emulator Name;Nom de l'émulateur
Emulators;Emulateurs
Enabled;Activé
Enter Display Name;Entrer le nom de la liste
Enter Emulator Name;Nom de l'émulateur?
Enter Filter Name;Entrer le nom du filtre
Executable;Exécutable
Exit;Sortie (Confirmer)
Exit Attract-Mode;Quitter Attract-Mode
Exit Attract-Mode?;Quitter Attract-Mode?
Exit Command;Commande de sortie
Exit Hotkey;Raccourci clavier pour sortir
Exit to Desktop;Sortie vers le bureau
Favourite;Favoris
Fill Screen (Default);Rempli l'écran (Default)
Filter;Filtre
Filter Edit;Edition du filtre
Filter Name;Nom du filtre
Filter Value;Filtre de valeur
Filter Wrap Mode;Mode de fin de liste de filtres
Filters Menu;Menu des filtres
Flip;Retourné
Font Path;Chemin de la police
Fullscreen Mode;Mode plein écran 
Game Return Sound;Son au retour du jeu
General;Général
Generate Collection/Rom List;Générer la liste de roms 
Generating Rom List: $1%;Génération de la liste de ROM: $1%
Global Filter;Filtre global
Hide Brackets in Game Title;Cacher les crochets dans le titre du jeu
Info Source/Scraper;Info Source/Aspiration
Joystick Threshold;Seuil du joystick
Jump to Next Display;Bascule sur la liste de roms suivante 
Language;Langue
Layout;Thème
Layout Options;Options du Layout
Left;Gauche
List Limit;taille maximum de la liste
Manufacturer;Fabriquant
Mouse Threshold;Seuil de la souris
Movie Volume;Volume des vidéos
Name;Nom
Next Display;Liste suivante
Next Favourite;Favoris suivant
Next Filter;Filtre suivant
Next Letter;Lettre suivante
Next Page;Page Précédente
No;Non
No Sort;Non classé
No Wrap;Ne fait rien
None;Non
OR;OU
Overwrite existing '$1' list?;Ecraser la liste de ROM '$1' existante?
PlayedCount;Compteur de jeu
PlayedTime;Temps de jeu
Players;Joueurs
Plug-ins;Plug-in
Press Input;Appuyer sur le contrôle
Previous Display;Liste précédente
Previous Favourite;Favoris précédent
Previous Filter;Filtre précédent
Previous Letter;Lettre précédente 
Previous Page;Page Suivante
Random Game;Jeu au hasard
Remove Input;Enlever le contrôle
Replay Last Game;Rejouer au dernier jeu
Right;Droite
Rom Extension(s);Extension(s) des ROM
Rom Path(s);Chemin des ROM
Rom path '$1' not found, proceed anyways?;Chemin des ROM '$1' introuvable, continuer?
Rotation;Rotation
Rule;Règle
Rule Edit;Editer les règles
Scrape Artwork;Aspirer les Artworks
Scrape Fanart;Aspire les 'Fanart'
Scrape Flyers/Boxart;Aspire les Flyers/Couvertures
Scrape Game Logos (Wheel Art);Aspire les logos des jeux (Wheel Art)
Scrape Marquees;Aspire les Marquees
Scrape Snaps;Aspire les images des jeux
Scraper;Aspiration
Scraping Artwork: $1%;Aspire l'Artwork: $1%
Screen Saver;Economiseur d'écran
Screen Saver Timeout;Décompte économiseur d'écran
Screenshot;Photo écran
Select;Sélection
Sort By;Classé par
Sound;Son
Sound Volume;Volume général
Startup Sound;Son au démarrage
Status;Etat
System Identifier;Identifiant du système
Tags;Mots clés
Target;Cible
The name for this filter;Nom du filtre
This will overwrite an existing mapping ($1).  Proceed?;Ecraser le contrôle existant ($1). Confirmer?
Title;Titre
Toggle Flip;Basculer mode retourné
Toggle Layout;Basculer le thème
Toggle Movie;Basculer la vidéo
Toggle Mute;Basculer en mode silence
Toggle Rotate Left;Basculer Rotation gauche
Toggle Rotate Right;Basculer Rotation droite
Track Usage;Mode de comptage
Up;Haut
Window;Fenêtre
Window Mode;Mode d'affichage
Wrap within Display (Default);Revient au début de la liste de filtres (Défaut)
Wrote $1 entries to Collection/Rom List;Création de $1 entrées dans la liste de ROM
Year;Année
Yes;Oui
contains;contient
does not contain;ne contient pas
does not equal;n'est pas égal à
equals;est égal à

#
# Help messages
#
_help_art_add;Ajouter une nouvelle ressource à l'Artwork (marquee, capture d'écran, etc.)
_help_art_label;Label identifiant cette ressource d'Artwork (utilisé par les thèmes)
_help_art_path;Répertoire contenant les Artworks
_help_confirm_favs;Confirmer l'addition/suppression des favoris
_help_control_add_favourite;Définit le(s) contrôle(s) qui permet(ent) d'ajouter/supprimer le jeu selectionné à la liste des favoris
_help_control_add_tags;Définit le(s) contrôle(s) qui ajoute(nt)/supprime(nt) des mots clés au jeu sélectionné
_help_control_configure;Définit le(s) contrôle(s) qui affiche(nt) le menu de configuration  
_help_control_custom1;Définit le(s) contrôle(s) utilisateur(s) "Custom1"
_help_control_custom2;Définit le(s) contrôle(s) utilisateur(s) "Custom2"
_help_control_custom3;Définit le(s) contrôle(s) utilisateur(s) "Custom3"
_help_control_custom4;Définit le(s) contrôle(s) utilisateur(s) "Custom4"
_help_control_custom5;Définit le(s) contrôle(s) utilisateur(s) "Custom5"
_help_control_custom6;Définit le(s) contrôle(s) utilisateur(s) "Custom6"
_help_control_displays_menu;Définit le(s) contrôle(s) qui affiche(nt) la liste des listes 
_help_control_down;Définit le(s) contrôle(s) qui décrémente(nt) la séléction d'une valeur
_help_control_exit;Définit le(s) contrôle(s) qui quitte(nt) Attract Mode 
_help_control_exit_to_desktop;Définit le(s) contrôle(s) qui quitte(nt) immédiatement Attract Mode pour revenir au bureau
_help_control_filters_menu;Définit le(s) contrôle(s) qui affiche(nt) la liste des filtres 
_help_control_next_display;Définit le(s) contrôle(s) qui bascule(nt) à la liste suivante
_help_control_next_favourite;Définit le(s) contrôle(s) qui selectionne(nt) le jeu favoris suivant
_help_control_next_filter;Définit le(s) contrôle(s) qui bascule(nt) au filtre suivant
_help_control_next_letter;Définit le(s) contrôle(s) qui bascule(nt) à la lettre suivante
_help_control_next_page;Définit le(s) contrôle(s) qui décrémente(nt) la séléction d'une page
_help_control_prev_display;Définit le(s) contrôle(s) qui bascule(nt) à la liste précédente
_help_control_prev_favourite;Définit le(s) contrôle(s) qui selectionne(nt) le jeu favoris precedent
_help_control_prev_filter;Définit le(s) contrôle(s) qui bascule(nt) au filtre précédente
_help_control_prev_letter;Définit le(s) contrôle(s) qui bascule(nt) à la lettre précédente
_help_control_random_game;Définit le(s) contrôle(s) qui sélectionne(nt) un jeu aléatoirement dans la liste de rom active
_help_control_replay_last_game;Définit le(s) contrôle(s) qui relance(nt) le dernier jeu joué
_help_control_screen_saver;Définit le(s) contrôle(s) qui lance(nt) le mode "économiseur d'écran"
_help_control_screenshot;Définit le(s) contrôle(s) qui enregistre(nt) une impression écran d'Attract Mode
_help_control_select;Définit le(s) contrôle(s) qui valide(nt) la valeur sélectionnée 
_help_control_toggle_flip;Définit le(s) contrôle(s) qui active(nt)/désactive(nt) la rotation de l'écran de 180 degrés
_help_control_toggle_layout;Définit le(s) contrôle(s) qui  active(nt)/désactive(nt) le script du theme utilisé (Ceci dépend du theme que vous utilisez)
_help_control_toggle_movie;Définit le(s) contrôle(s) qui active(nt)/désactive(nt) la lecture des vidéos.  
_help_control_toggle_mute;Définit le(s) contrôle(s) qui active(nt)/désactive(nt) le son. 
_help_control_toggle_rotate_left;Définit le(s) contrôle(s) qui active(nt)/désactive(nt) la rotation de l'écran de 90 degrés sur la gauche 
_help_control_toggle_rotate_right;Définit le(s) contrôle(s) qui active(nt)/désactive(nt) la rotation de l'écran de 90 degrés sur la droite 
_help_control_up;Définit le(s) contrôle(s) qui incrémente(nt) la séléction d'une valeur
_help_controls;Configurer les contrôles
_help_default_font;Le nom de la police par défaut à utiliser
_help_display_add;Ajouter une nouvelle liste d'affichage
_help_display_add_filter;Ajouter un filtre à cette liste d'affichage
_help_display_delete;Suppression de la liste d'affichage
_help_display_filter;Configurer le filtre
_help_display_global_filter;Définit les règles du filtre global. Elles s'appliqueront à l'ensemble des valeurs de la liste de roms affichée.
_help_display_layout;Thème à utiliser pour cette liste d'affichage
_help_display_layout_options;Configurer une option spécifique du Layout
_help_display_name;Titre de cette liste d'affichage
_help_display_romlist;Liste de ROM à utiliser pour cette liste d'affichage
_help_display_sel;Configurer la liste d'affichage
_help_displays;Configurer les listes d'affichage
_help_displays_menu_exit;Indiquer si une option de sortie doit être prévue dans le menu des listes
_help_emu_add;Ajouter un nouvel émulateur
_help_emu_args;Arguments de la ligne de commande de cet émulateur. Options de substitution: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_emu_delete;Supprime l'entrée pour cet émulateur
_help_emu_executable;Chemin et nom de l'exécutable de l'émulateur. $HOME sera remplacé par le répertoire de l'utilisateur
_help_emu_exit_hotkey;Définit un raccourci clavier pour sortir de l'émulateur. Attract-Mode arrêtera le process de l'émulateur lorsque ce raccourci clavier sera pressé.
_help_emu_gen_romlist;Génére une liste de ROM en cherchant dans le chemin des ROM avec l'extension choisie, incorporant l'XML et les fichiers additionnels d'information dans la liste générée (si disponible)
_help_emu_import_extras;Fichiers additionels nécessitant d'être lus lors de la génération de la liste de ROM pour cet émulateur. Fichiers supportés: catver.ini (catégories) et nplayers.ini (nombre de joueur). Plusieurs fichiers peuvent être saisis si séparés par un point-virgule
_help_emu_info_source;Saisir "listxml" si cet émulateur propose un fichier de type mame -listxml, "listsoftware" pour les fichiers du type mame/mess -listsoftware, "thegamesdb.net" pour extraire les informations du site thegamesdb.net, ou "steam" pour les lires depuis une installation de steam. Les sources "listsoftware" et "thegamesdb.net" nécessitent que des identifiants systèmes spécifiques soient configurés pour fonctionner correctement
_help_emu_nb_mode_wait;Définit un temps minimum de fonctionnement (en secondes). Attract-Mode va attendre, après avoir lancé l'émulateur, que ce temps minimum se soit écoulé avant de re-basculer au premier plan. Ceci est nécessaire pour que Steam fonctionne correctement sous Windows. Saisir 0 si vous n'en avez pas besoin
_help_emu_romext;Extension des ROM pour cet émulateur (ex .zip).  Possibilité d'utiliser des extensions multiples séparées par un point-virgule
_help_emu_rompath;Chemin des ROM pour cet émulateur
_help_emu_scrape_artwork;Aspirer les artworks manquants pour cet émulateur sur TheGamesDB.net et mamedb.com
_help_emu_sel;Configuration de l'émulateur
_help_emu_system;Identifiant(s) système(s) pour cet émulateur. Plusieurs valeurs peuvent être saisies, séparées par un point virgule
_help_emulators;Configurer les émulateurs
_help_exit_command;Commande à exécuter en quittant (Confirmer) [exemple "sudo shutdown"]
_help_filter_add_rule;Ajouter une règle à ce filtre
_help_filter_delete;Supprimer ce filtre
_help_filter_list_limit;Saisir un nombre différent de zéro pour limiter la taille de la liste triée. Un nombre positif remonte les X premières valeurs (ex : "10" donne les 10 premières valeurs), un nombre négatif remonte les X dernières valeurs (ex : "-25" donne les 25 dernières valeurs). "0" affiche toute la liste.
_help_filter_name;Nom du filtre
_help_filter_rule;Configurer le filtre
_help_filter_sort_by;C'est l'information du jeu par lequel vous souhaitez classer votre liste. Sélectionner "Non classé" pour conserver l'ordre de la liste de rom source.
_help_filter_wrap_mode;Définit l'action a mener lorsque "Filtre suivant" ou "Filtre précédent" arrivent à une  extrémité de la liste de filtre.
_help_font_path;Répertoires contenant les polices (séparés par des points virgules)
_help_hide_brackets;Cacher le texte entre crochets lors de l'affichage du titre du jeu
_help_input_add;Ajouter un nouveau contrôle
_help_input_delete;Enlever ce contrôle
_help_intro;Configurer l'intro
_help_joystick_threshold;Seuil d'amplitude des mouvements du joystick, de 1 à 100 (100=moins sensible)
_help_language;Sélectionner la langue
_help_misc;Configurations diverses
_help_mouse_threshold;Seuil d'amplitude des mouvements de la souris, de 1 à 100 (100=moins sensible)
_help_plugin_command;Exécutable associé à ce plug-in
_help_plugin_enabled;Indiquer si ce plug-in est activé
_help_plugin_sel;Configurer le plug-in
_help_plugins;Configurer les plug-ins
_help_rule_comp;Règle de comparaison pour le filtre
_help_rule_delete;Supprimer cette règle de filtrage
_help_rule_target;L'attribut du jeu que vous souhaitez filtrer sur la base de
_help_rule_value;Valeur à filtrer.  Par exemple, si la cible de filtrage est "Année" et le comparateur "est égale à", une valeur de "1984" correspondra à l'année 1984, "198." correspondra à n'importe quelle année des années 1980, et "(198.)|(199.)" correspondra aux années comprises entre 1980 et 1999
_help_scrape_fanart;Définir où les 'fan art' des jeux doivent être téléchargés lorsqu'ils sont aspirés 
_help_scrape_flyers;Définir où les 'flyers' et les couvertures des boîtes des jeux doivent être téléchargés lorsqu'ils sont aspirés
_help_scrape_marquees;Définir où les 'marquees' et les bannières des jeux doivent être téléchargés lorsqu'ils sont aspirés
_help_scrape_snaps;Définir où les 'snapshots' des jeux doivent être téléchargés lorsqu'ils sont aspirés
_help_scrape_vids;Définir où les videos des jeux doivent être téléchargés lorsqu'ils sont aspirés 
_help_scrape_wheels;Définir où les logos des jeux doivent être téléchargés lorsqu'ils sont aspirés
_help_scraper;Configurer les parametres d'aspiration des artworks
_help_screen_saver;Configurer l'économiseur d'écran
_help_screen_saver_timeout;Temps total en seconde à attendre pour activer l'économiseur d'écran.  0 pour désactiver
_help_sound;Configurer le volume et les affectations sonores
_help_sound_sel;Assigner un son à cet événement/action
_help_track_usage;Active les compteurs d'Attract-Mode (Compteur de jeu et Temps de jeu)
_help_volume;Les valeurs possibles pour le volume vont de 0 (silence) à 100
_help_window_mode;Définit si Attract Mode rempli l'écran, fonctionne en mode plein écran ou si il s'exécute dans une fenêtre.
_sort_regexp;^(Vs\. The |The |Vs\. )

#
# Extra strings provided by translation
#
Add a rule to this filter;Ajouter une règle à ce filtre
Allow Exit from 'Lists Menu';Permettre la sortie des listes de menu 
Ambient Sounds;Son d'ambiance
Configure available emulators;Configurer les émulateurs disponibles
Configure filter rule;Configuration de la règle de filtrage
Delete this filter;Supprimer ce filtre
Exit menu;Quitter le menu
Generate Collection/Romlist;Générer la liste de ROM
Launch Last Game on Startup;Lancer le dernier jeu au démarrage
Lists;Listes
Lists Menu;Menu des listes
Minimum Run Time;Temps minimum fonctionnement 
Next List;Liste suivante
Previous List;Liste précédent
XML Mode;Mode XML
en;Anglais
es;Español
fr;Français
jp;Japonais
kr;Coréen
_help_autolaunch_last_game;Lancer automatiquement au démarrage le dernier jeu joué
_help_control_previous_page;Définit le(s) contrôle(s) qui incrémente(nt) la séléction d'une page

#@DONE_TRANSLATED
#
# Strings still needing translation
#
$1 Rule(s);$1 Rule(s)
Add '$1' to Favourites?;Add '$1' to Favourites?
Add Exception;Add Exception
Add tag: '$1';Add tag: '$1'
Artwork Name;Artwork Name
Attract-Mode detected emulator(s) that can be imported automatically.  Import them now?;Attract-Mode detected emulator(s) that can be imported automatically.  Import them now?
Blank Game;Blank Game
Buttons;Buttons
Clear Hotkey?;Clear Hotkey?
Configure / Displays Menu;Configure / Displays Menu
Configure / Joystick Mapping;Configure / Joystick Mapping
Configure Intro;Configure Intro
Configure Layout;Configure Layout
Confirm Exit;Confirm Exit
Create new tag;Create new tag
Custom Arguments;Custom Arguments
Custom Executable;Custom Executable
Default;Default
Default Action;Default Action
Delete game '$1'?;Delete game '$1'?
Delete shortcut '$1'?;Delete shortcut '$1'?
Delete this Game;Delete this Game
Delete this Shortcut;Delete this Shortcut
Edit Game;Edit Game
Edit Shortcut;Edit Shortcut
Empty;Empty
Enable Multiple Monitors;Enable Multiple Monitors
Enter Romlist Name;Enter Romlist Name
Enter new tag name;Enter new tag name
Exception;Exception
Exception Edit;Exception Edit
Exit Message;Exit Message
Extra;Extra
FileIsAvailable;FileIsAvailable
Insert Command Shortcut;Insert Command Shortcut
Insert Display Shortcut;Insert Display Shortcut
Insert Game Entry;Insert Game Entry
Insert Menu Entry;Insert Menu Entry
Intro;Intro
Joystick $1;Joystick $1
Joystick Mappings;Joystick Mappings
Launch Last Game;Launch Last Game
Layout File;Layout File
Menu Prompt;Menu Prompt
Menu Style / Layout;Menu Style / Layout
Next Game;Next Game
Non-Blocking Mode Wait;Non-Blocking Mode Wait
Overview;Overview
Pause Hotkey;Pause Hotkey
Play Sound;Play Sound
Please Wait;Please Wait
Press Hotkey;Press Hotkey
Previous Game;Previous Game
Remove '$1' from Favourites?;Remove '$1' from Favourites?
Remove tag: '$1';Remove tag: '$1'
Scrape Videos (MAME only);Scrape Videos (MAME only)
Select template to use for emulator settings;Select template to use for emulator settings
Show Displays Menu;Show Displays Menu
Show Last Selection (Default);Show Last Selection (Default)
Show in Cycle;Show in Cycle
Show in Menu;Show in Menu
Startup Mode;Startup Mode
Video Decoder;Video Decoder
Window (No Border);Window (No Border)
Working Directory;Working Directory
multi;multi
_help_art;An artwork resource available for use by layouts
_help_back;Exit menu
_help_confirm_exit;Confirm before exiting Attact-Mode?
_help_control_back;Set the control(s) that go back
_help_control_edit_game;Set the control(s) to edit the current selection
_help_control_intro;Set the control(s) that show the intro video
_help_control_left;Set the control(s) that move the selection left
_help_control_next_game;Set the control(s) that move to the next game
_help_control_prev_game;Set the control(s) that move to the previous game
_help_control_prev_page;Set the control(s) that move the selection down one page
_help_control_right;Set the control(s) that move the selection right
_help_display_in_cycle;Include this display in the "Previous Display"/"Next Display" cycle?
_help_display_in_menu;Include this display in the "Displays Menu"?
_help_displays_menu;Configure options for the "Displays Menu"
_help_displays_menu_layout;The layout to use for the 'Displays Menu'. Set to 'Default' to use the frontend's built-in menu
_help_displays_menu_prompt;The 'Displays Menu' prompt (i.e. "Select System")
_help_emu_pause_hotkey;Set a global hotkey to pause the emulator.  When pressed, Attract-Mode will pause the emulator process and return to the frontend. The emulator process can be resumed by selecting the same game again in the frontend.
_help_emu_sel_gen_romlist;Generate a Collection/Romlist containing games for multiple emulators
_help_emu_workdir;The working directory for this emulator.  This is the directory that the frontend runs the emulator from.  Also, any relative rom paths, artwork paths, or additional import file paths are treated as being relative to this directory
_help_exit_message;Alternate message to exit the frontend [i.e. "Shut Down System"]
_help_filter_add_exception;Add an exception to this filter.  If a game matches an exception (and wasn't filtered out by an earlier rule) it will be listed in the filter
_help_filter_exception;Configure this filter exception.  If a game matches an exception it will be listed in the filter.  Rules and exceptions get applied in the order that they are listed
_help_game_custom_args;Set this to override the default command line arguments for this game.  Set this to [nothing] if you want to override with no parameters.  The following get substituted appropriately: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_game_custom_executable;Set this to override the default executable for this game
_help_game_delete;Delete this game from the Romlist
_help_game_edit;Edit this game information
_help_game_overview;Edit game overview
_help_generator_build;Generate romlist with the selected emulator(s)
_help_generator_opt;Set whether this emulator is to be included in the generated romlist
_help_hide_console;Hide console on startup. Note that this only works if starting Attract-Mode from a Windows GUI. If started from an existing console window (e.g. a batch file) then the process will always "attach" to the existing console and output to it.
_help_input_action;
_help_input_default_action;Set the default behaviour for this control
_help_joystick_map;Map the frontend's joystick slots to specifically named joystick/gamepad devices attached to your computer (You can use this to force the frontend to always use 'Microsoft X-Box 360 pad' as Joystick 0, for example.)
_help_layout_file;Some layouts provide multiple layout*.nut files.  Select which layout file to use
_help_multiple_monitors;Enable the use of multiple monitors by Attract-Mode.  Setting this to 'No' may reduce screen flicker when launching games
_help_shortcut_artwork_name_edit;Optionally provide an artwork name to be associated with this shortcut.  The frontend will try to load artworks with this name when displaying the shortcut
_help_shortcut_delete;Delete this shortcut from the Romlist
_help_shortcut_label_edit;Edit this shortcut's label
_help_shortcut_target_edit;Edit this shortcut's target
_help_startup_mode;Set what should happen when Attract-Mode first starts up
_help_video_decoder;Configure the decoder to use for video playback (if multiple decoders are available)
