#@Italiano
# Traduzione a cura di Piergiorgio Ghezzo <PJ@piggei.com>
#
# Interface strings
#
$1 Rule(s);$1 regole
Action;Azione
Add '$1' to Favourites?;Aggiungo '$1' ai preferiti?
Add Artwork;Aggiungi risorsa immagini
Add Emulator;Aggiungi emulatore
Add Exception;Aggiungi eccezione
Add Filter;Aggiungi filtro
Add Input;Aggiungi controllo
Add New Display;Aggiungi nuovo display
Add Rule;Aggiungi regola
Add tag: '$1';Aggiungi etichetta: '$1'
Add/Remove Favourite;Aggiungi/rimuovi preferito
Add/Remove Tags;Aggiungi/rimuovi etichetta
Additional Import File(s);File aggiuntivo di import
All;Tutto
Allow Exit from 'Displays Menu';Aggiungere opzione di uscita
AltRomname;Nome alternativo della ROM
AltTitle;Titolo alternativo
Ambient Soundtrack;Musica di sottofondo
Ambient Volume;Volume musica di sottofondo
Artwork Label;Nome della risorsa
Artwork Path;Percorso della risorsa
Back;Indietro
Buttons;Pulsanti
Category;Categoría
CloneOf;Clone di
Collection/Rom List;Lista di ROM
Command;Comando
Command Arguments;Argomenti del comando
Comparison;Comparazione
Configure;Configurazione
Configure / Controls;Configurazione / Controlli
Configure / Displays;Configurazione / Display
Configure / Displays Menu;Configura / Menù dei display
Configure / Emulators;Configurazione / Emulatori
Configure / Miscellaneous;Configurazione / Varie
Configure / Plug-ins;Configurazione / Plugin
Configure / Scraper;Configurazione / Recupera dalla rete
Configure / Sound;Configurazione / Suoni
Configure Intro;Configura il video di introduzione
Configure Layout;Configura il tema
Configure Plug-in;Configura i plugin
Configure Screen Saver;Configura il salvaschermo
Confirm Exit;Conferma l'uscita
Confirm Favourites;Conferma aggiunta preferito
Control;Controllo
Controls;Controlli
Create new tag;Crea una nuova etichetta
Custom Arguments;Argomenti personalizzati
Custom Executable;Eseguibile personalizzato
Custom1; Personalizzato 1
Custom2; Personalizzato 2
Custom3; Personalizzato 3
Custom4; Personalizzato 4
Custom5; Personalizzato 5
Custom6; Personalizzato 6
Default;Predefinito
Default Action;Azione predefinita
Default Font;Font predefinito
Delete display '$1'?;Cancello il display '$1'?
Delete emulator '$1'?;Cancello l'emulatore '$1'?
Delete filter '$1'?;Cancello il filtro '$1'?
Delete game '$1'?;Cancello il gioco '$1'?
Delete this Display;Cancella questo display
Delete this Emulator;Cancella questo emulatore
Delete this Filter;Cancella questo filtro
Delete this Game;Cancella il gioco
Delete this Rule;Cancella questa regola
Disabled;Disabilitato
Display Edit;Modifica il display
Display Name;Nome del display
DisplayCount;Contatore di display
DisplayType;Tipo di display
Displays;Display
Displays Menu;Menù dei display
Down;Giù
Edit Artwork;Modifica risorsa immagini
Edit Emulator;Modifica emulatore
Edit Game;Modifica il gioco
Edit Input;Modifica controlli
Empty;Vuoto
Emulator;Emulatore
Emulator Name;Nome dell'emulatore
Emulators;Emulatori
Enable Multiple Monitors;Abilita monitor multipli
Enabled;Attivo
Enter Display Name;Inserisci il nome del display
Enter Emulator Name;Inserisci il nome dell'emulatore
Enter Filter Name;Inserisci il nome del filtro
Enter Romlist Name;Inserisci il nome della Romlist
Enter new tag name;Inserisci il nome dell'etichetta
Exception;Eccezione
Exception Edit;Modifica l'eccezione
Executable;Eseguibile
Exit;Uscita (Conferma)
Exit Attract-Mode;Esci da Attract-Mode
Exit Attract-Mode?;Uscire da Attract-Mode?
Exit Command;Comando per uscire
Exit Hotkey; Tasto per uscire
Exit to Desktop;Esci al desktop
Extra;Extra
Favourite;Preferito
FileIsAvailable;FileIsAvailable
Fill Screen (Default);Riempi schermo (Predefinito)
Filter;Filtro
Filter Edit;Modifica filtro
Filter Name;Nome del filtro
Filter Value;Valore da comparare
Filter Wrap Mode;Metodo di scorrimento dei filtri
Filters Menu;Menù dei filtri
Flip;Inverti
Font Path;Percorso dei font
Fullscreen Mode;A tutto schermo
Game Return Sound;Suono di ritorno al gioco
General;Varie
Generate Collection/Rom List;Genera la lista di ROM
Generating Rom List: $1%;Generazione lista: $1%
Global Filter;Filtro globale
Hide Brackets in Game Title;Nascondere le parentesi nei titoli
Info Source/Scraper;Sorgente informazioni/Recupero
Intro;Video introduttivo
Joystick Threshold;Soglia del joystick
Jump to Next Display;Salta al display successivo 
Language;Lingua
Launch Last Game;Esegui l'ultimo gioco
Layout;Tema
Layout Options;Opzioni del tema
Left;Sinistra
List Limit;Límite della lista
Manufacturer;Produttore
Menu Prompt;Titolo del menù
Menu Style / Layout;Tema del menù
Mouse Threshold;Soglia del mouse
Movie Volume;Volume dei video
Name;Nome
Next Display;Display successivo
Next Favourite;Preferito successivo
Next Filter;Filtro successivo
Next Game;Gioco successivo
Next Letter;Lettera successiva
Next Page;Pagina successiva
No;No
No Sort;Nessun ordinamento
No Wrap;Non ciclare
None;Nessuno
OR;o
Overview;Panoramica
Overwrite existing '$1' list?;Sovrascrivere la lista '$1'?
Play Sound;Esegui il suono
PlayedCount;Partite giocate
PlayedTime;Tempo giocato
Players;Giocatori
Plug-ins;Plugin
Press Input;Premi il tasto
Previous Display;Display precedente
Previous Favourite;Preferito precedente
Previous Filter;Filtro precedente
Previous Game;Gioco precedente
Previous Letter;Lettera precedente
Previous Page;Pagina precedente
Random Game;Gioco casuale
Remove '$1' from Favourites?;Elimino '$1' dai preferiti?
Remove Input;Eliminare il controllo
Remove tag: '$1';Elimina etichetta: '$1'
Replay Last Game;Esegui l'ultimo gioco
Right;Destra
Rom Extension(s);Estensioni delle ROM
Rom Path(s);Percorsi delle ROM
Rom path '$1' not found, proceed anyways?;Percorso delle rom '$1' non trovato, continuare?
Rotation;Rotazione
Rule;Regola
Rule Edit;Modifica la regola
Scrape Artwork;Recupera le immagini
Scrape Fanart;Recupera le fanart
Scrape Flyers/Boxart;Recupera i flyer/boxart
Scrape Game Logos (Wheel Art);Recupera i logo
Scrape Marquees;Recupera i marquee
Scrape Snaps;Recupera le snap
Scrape Videos (MAME only);Scarica video (solo per MAME)
Scraper;Recupera immagini in rete
Scraping Artwork: $1%;Sto recuperando le immagini: $1%
Screen Saver;Salvaschermo
Screen Saver Timeout;Timeout salvaschermo
Screenshot;Screenshot
Select;Selezione
Show Displays Menu;Mostra menù dei display
Show Last Selection (Default);Mostra l'ultima selezione (Predefinito)
Show in Cycle;Mostra nel ciclo
Show in Menu;Mostra nel menù
Sort By;Ordinato per
Sound;Suoni
Sound Volume;Volume generale
Startup Mode;Modalità di avvio
Startup Sound;Volume avvio
Status;Stato
System Identifier;Identificatore del sistema
Tags;Etichette
Target;Obbiettivo
The name for this filter;Nome per questo filtro
This will overwrite an existing mapping ($1).  Proceed?;Sovrascrivere l'associazione esistente ($1)?
Title;Titolo
Toggle Flip;Invertire
Toggle Layout;Pagina successiva tema
Toggle Movie;Pausa video
Toggle Mute;Muto
Toggle Rotate Left;Rotazione a sinistra
Toggle Rotate Right;Rotazione a destra
Track Usage;Memorizza statistiche di utilizzo
Up;Su
Video Decoder;Decoder video
Window;Finestra
Window (No Border);Finestra (Senza bordi)
Window Mode;Modalità finestra
Working Directory;Directory di lavoro
Wrap within Display (Default);Non cambiare display (Predefinito)
Wrote $1 entries to Collection/Rom List;$1 titoli scritti nella lista di ROM
Year;Anno
Yes;Si
contains;contiene
does not contain;non contiene
does not equal;non è uguale
equals;è uguale
multi;multi

#
# Help messages
#
_help_art;Una sorgente di immagini disponible per essere utilizzata con questo tema
_help_art_add;Aggiunge una nuova risorsa immagini (marquee, flyer, screenshot, etc.)
_help_art_label;Nome che identifica questa risorsa immagini (viene utilizzato nei temi)
_help_art_path;Percorso nel quale è possibile trovare le immagini. Possono essere specificate più directory separandole con il punto e virgola.
_help_back;Menù precedente
_help_confirm_exit;Permette di chiedere la conferma prima di uscire da Attact-Mode
_help_confirm_favs;Conferma l'aggiunta/rimozione del gioco dai preferiti
_help_control_add_favourite;Configura i controlli per aggiungere/togliere dai preferiti il gioco selezionato
_help_control_add_tags;Configura i controlli per aggiungere/togliere etichette al gioco selezionato
_help_control_back;Configura i controlli per tornare indietro
_help_control_configure;Configura i controlli per mostrare il menù di configurazione
_help_control_custom1;Configura i controlli per il "Personalizzato 1"
_help_control_custom2;Configura i controlli per il "Personalizzato 2"
_help_control_custom3;Imposta il controllo "Personalizzato 3"
_help_control_custom4;Imposta il controllo "Personalizzato 4"
_help_control_custom5;Imposta il controllo "Personalizzato 5"
_help_control_custom6;Imposta il controllo "Personalizzato 6"
_help_control_displays_menu;Configura i controlli per mostrare il menù dei display
_help_control_down;Configura i controlli che muovono la selezione in basso
_help_control_edit_game;Configura i controlli per modificare la selezione corrente
_help_control_exit;Configura i controlli che permettono di uscire dal frontend
_help_control_exit_to_desktop;Configura i controlli che permettono di uscire immediatamente dal programma e tornare al desktop
_help_control_filters_menu;Configura i controlli per mostrare il menù dei filtri
_help_control_intro;Configura i controlli per riprodurre il video introduttivo
_help_control_left;Configura i controlli per spostare la selezione a sinistra
_help_control_next_display;Configura i controlli per passare al display successivo
_help_control_next_favourite;Configura i controlli per passare al preferito successivo
_help_control_next_filter;Configura i controlli per passare al filtro successivo
_help_control_next_game;Configura i controlli per spostarsi al gioco successivo
_help_control_next_letter;Configura i controlli per passare alla lettera successiva
_help_control_next_page;Configura i controlli per spostarsi alla pagina successiva
_help_control_prev_display;Configura i controlli per passare al display precedente
_help_control_prev_favourite;Configura i controlli per passare al preferito precedente
_help_control_prev_filter;Configura i controlli per passare al filtro precedente
_help_control_prev_game;Configura i controlli per spostarsi al gioco precedente
_help_control_prev_letter;Configura i controlli per passare alla lettera precedente
_help_control_prev_page;Configura i controlli per spostarsi alla pagina precedente
_help_control_random_game;Configura i controlli per saltare ad un gioco casuale
_help_control_replay_last_game;Configura i controlli per eseguire nuovamente l'ultimo titolo giocato
_help_control_right;Configura i controlli per spostare la selezione a destra
_help_control_screen_saver;Configura i controlli per eseguire immediatamente il salvaschermo
_help_control_screenshot;Configura i controlli per realizzare uno screenshot
_help_control_select;Configura i controlli per eseguire la selezione attuale
_help_control_toggle_flip;Configura i controlli per ruotare display di 180 gradi
_help_control_toggle_layout;Configura i controlli per cambiare la pagina del tema. Tale funzione dipende da come è stato costruito il tema stesso: con alcuni potrebbe non succedere nulla.
_help_control_toggle_movie;Configura i controlli per attivare/disattivare l'esecuzione dei video
_help_control_toggle_mute;Configura i controlli che disabilitano e riabilitano l'audio del frontend
_help_control_toggle_rotate_left;Configura i controlli per ruotare il display a sinistra di 90 gradi
_help_control_toggle_rotate_right;Configura i controlli per ruotare il display a destra di 90 gradi
_help_control_up;Configura i controlli che muovono la selezione in alto
_help_controls;Configura gli input di joystick, tastiera e mouse per controllare Attract-Mode
_help_default_font;Il nome del font predefinito da utilizzare
_help_display_add;Aggiunge un nuovo display
_help_display_add_filter;Aggiungere un filtro al gruppo di filtri di questo display
_help_display_delete;Cancella questo display
_help_display_filter;Modifica la configurazione di questo filtro
_help_display_global_filter;Configura regole ed eccezioni che verranno applicate a ciascun titolo presente nella lista di ROM di questo display
_help_display_in_cycle;Includere questo display nel ciclo "Display precedente"/"Display successivo"?
_help_display_in_menu;Includere questo display nel menù dei display?
_help_display_layout;Tema da utilizzare con questo display
_help_display_layout_options;Configura le impostazioni specifiche per questo tema
_help_display_name;Il nome di questo display
_help_display_romlist;Lista di ROM da utilizzare con questo display
_help_display_sel;Configura il display
_help_displays;I display sono associazioni lista di ROM/tema che possono essere utilizzati in Attract-Mode per visualizzare liste di giochi e selezionare quello che si vuole giocare
_help_displays_menu;Configura le opzioni per il Menù dei display
_help_displays_menu_exit;Definisce se l'opzione di uscita dal programma deve essere presente nel menù dei display
_help_displays_menu_layout;Il tema da utilizzare per il Menù dei display. Imposta su 'Predefinito' per utilizzare quello interno del frontend.
_help_displays_menu_prompt;Il titolo del Menù dei display (es: "Scegli l'emulatore")
_help_emu_add;Aggiungere un nuovo emulatore
_help_emu_args;Gli argomenti della linea di comando di questo emulatore. I seguenti parametri verranno sostituiti appropriatamente: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_emu_delete;Cancella le impostazioni di questo emulatore
_help_emu_executable;Percorso completo e nome dell'eseguibile dell'emulatore. $HOME verrà rimpiazzato con la home directory dell'utente
_help_emu_exit_hotkey;Configura una hotkey per uscire dall'emulatore. Attract-Mode terminerà l'emulatore se questa hotkey verrà premuta
_help_emu_gen_romlist;Genera la lista di ROM cercando all'interno dei percorsi indicati file con le estensioni specificate, incorporando anche le informazioni recuperate dai file aggiuntivi quando disponibili
_help_emu_import_extras;Percorso per ogni file aggiuntivo che deve essere letto quando viene generata una lista di ROM per questo emulatore. I file supportati sono: catver.ini (per le categorie dei giochi), nplayers.ini (per il numero dei giocatori) e mame.xml. Possono essere specificate più directory separandole con il punto e virgola.
_help_emu_info_source;Usare "listxml" se l'emulatore restituisce un output compatibile MAME -listxml, "listsoftware" per le liste software compatibili mame/mess -listsoftware, "thegamesdb.net" per recuperare le informazioni da thegamesdb.net, o "steam" per leggere da una installazione Steam, o "scummvm" se l'emulatore è ScummVM.  "listsoftware" e "thegamesdb.net" richiedono che venga configurato un identificatore di sistema riconosciuto da queste sorgenti.
_help_emu_nb_mode_wait;Configura un tempo mínimo di esecuzione (in secondi).  Attract-Mode aspetterà dopo aver eseguito l'emulatore finché è scaduto il tempo minimo, dopodiché passerà in primo piano. Questo deve essere impostato con Steam per funzionare correttamente su Windows. Impostare questo valore a 0 a meno che non si sappia quello che si fa.
_help_emu_romext;Estensioni dei file ROM per questo emulatore (per es. .zip) Più estensioni possono essere inserite utilizzando il punto e virgola. Specificare "<DIR>" come valore se i giochi sono memorizzati in sottodirectory separate.
_help_emu_rompath;Percorsi per le ROM di questo emulatore. Possono essere specificate più directory separandole con il punto e virgola.
_help_emu_scrape_artwork;Recupera le immagini mancanti per questo emulatore dai siti specializzati
_help_emu_sel;Configura le impostazioni dell'emulatore
_help_emu_sel_gen_romlist;Genera una Collezione/Romlist contenente giochi per più emulatori
_help_emu_system;Identificatori del sistema per questo emulatore. Più valori possono essere inseriti utilizzando il punto e virgola.
_help_emu_workdir;Imposta la directory di lavoro per questo emulatore: si tratta della directory dalla quale il frontend eseguirà l'emulatore. Tutti i percorsi relativi di ROM, artwork paths o altro faranno riferimento a questa directory.
_help_emulators;Configura le impostazioni degli emulatori
_help_exit_command;Comando da eseguire quando viene selezionata l'uscita dal programma (con conferma) [per es. "sudo shutdown"]
_help_filter_add_exception;Aggiunge un'eccezione per questo filtro. Se un gioco soddisfa l'eccezione (e non è già stato escluso da una regola precedente), questo verrà incluso nel filtro.
_help_filter_add_rule;Aggiunge una regola per questo filtro
_help_filter_delete;Cancella questo filtro
_help_filter_exception;Configura l'eccezione
_help_filter_list_limit;Imposta un valore diverso da zero se vuoi limitare il numero di voci presenti nella lista. Utilizza un valore positivo per recuperare i primi titoli (per esempio "10" restituirà i primi 10 titoli), un valore negativo per recuperare gli ultimi (per esempio "-25" restituirà gli ultimi 25 titoli), oppure "0" per averli tutti
_help_filter_name;Il nome di questo filtro
_help_filter_rule;Configura le regole per il filtro
_help_filter_sort_by;L'attributo del gioco che deve essere utilizzato per ordinare la lista. Imposta "Nessun ordinamento" per mantenere l'ordinamento originale della lista
_help_filter_wrap_mode;Configura cosa succede quando i comandi "Filtro successivo" o "Filtro precedente" raggiungono il termine della lista
_help_font_path; La directory che contiene i font. Possono essere specificate più directory separandole con il punto e virgola. Attract-Mode cercherà ricorsivamente all'interno di queste directory il font specificato.
_help_game_custom_args;Imposta dei parametri differenti per questo gioco
_help_game_custom_executable;Imposta un eseguibile differente per eseguire questo gioco
_help_game_delete;Cancella questo gioco dalla lista
_help_game_edit;Modifica le informazioni del gioco
_help_game_overview;Modifica la panoramica del gioco
_help_generator_build;Genera la Romlist utilizzando gli emulatori selezionati
_help_generator_opt;Permette di specificare se includere i giochi di questo emulatore nella RomList
_help_hide_brackets;Nasconde il testo tra parentesi quando viene mostrato il titolo del gioco
_help_input_action;
_help_input_add;Aggiunge una nuova associazione dei tasti per questa azione
_help_input_default_action;Configura l'azione predefinita per questo controllo
_help_input_delete;Cancella questa associazione dei tasti
_help_intro;Configura il video di introduzione
_help_joystick_threshold;Umbral para los movimientos de palanca registrados, de 1 a 100 (100=menos sensible)
_help_language;Seleziona la lingua dell'interfaccia di Attract-Mode
_help_misc;Configurazioni varie
_help_mouse_threshold;Sogla per il riconoscimento dei movimenti del mouse, accetta un valore da 1 a 100 (100 = meno sensibile)
_help_multiple_monitors;Abilita l'utilizzo di monitor multipli
_help_plugin_command;Eseguibile associato a questo plugin
_help_plugin_enabled;Configura se questo plugin è abilitato
_help_plugin_sel;Configura i plugin
_help_plugins;Configura i plugin disponibili
_help_rule_comp;Tipo di comparazione per questo filtro
_help_rule_delete;Cancellare questa regola
_help_rule_target;L'attributo del gioco sul quale basare il filtro
_help_rule_value;Espressione regolare con la quale filtrare. Per esempio, se l'obbiettivo del filtro è "Anno" e la comparazione è "Uguale", un valore di "1984" restituirà tutti i giochi prodotti nel 1984, mentre "198." restituirà tutti i giochi prodotti negli anni '80
_help_scrape_fanart;Stabilisce se le fanart devono essere recuperate dalla rete
_help_scrape_flyers;Stabilisce se i flyers e le copertine delle confezioni devono essere recuperate dalla rete
_help_scrape_marquees;Stabilisce se i marquee devono essere recuperati dalla rete
_help_scrape_snaps;Stabilisce se gli snapshot devono essere recuperati dalla rete
_help_scrape_vids;Stabilisce se i video devono essere recuperati dalla rete
_help_scrape_wheels;Stabilisce se i logo devono essere recuperati dalla rete
_help_scraper;Configura le impostazioni per il recupero delle immagini dalla rete
_help_screen_saver;Configura il salvaschermo
_help_screen_saver_timeout;Numero di secondi da attendere prima di attivare il salvaschermo. Inserire 0 per disabilitarlo
_help_sound;Configura il volume dei suoni, l'associazione dei suoni agli eventi e la musica d'ambiente
_help_sound_sel;Assegna un suono a questo evento/azione
_help_startup_mode;Configura come si deve comportare Attract-Mode quando viene eseguito
_help_track_usage;Configura se Attract-Mode deve gestire le statistiche di utilizzo (tempo complessivo e numero di partite giocate per ciascun titolo)
_help_video_decoder;Configura il decoder da utilizzare per riprodurre i video (nel caso siano disponibili più decoder)
_help_volume;I valori consentiti per il volume vanno da 0 (silenzio) a 100 (massimo)
_help_window_mode;Configura se il frontend deve lavorare a tutto schermo o essere eseguito in una finestra
_sort_regexp;^(Vs\. The |The |Vs\. )

#
# Extra strings provided by translation
#
'Displays Menu' Options;Opzioni del Menù dei display
Add a rule to this filter;Aggiungi una regola per questo filtro
Ambient Sounds;Suono ambiente
Back (Displays Menu);Indietro (Mostra menù)
Basic Movie;Video base
Configure available emulators;Configura gli emulatori disponibili
Configure filter rule;Configura la regola del filtro
Custom 1;Personalizzato 1
Custom 2;Personalizzato 2
Delete this filter;Cancella questo filtro
Down (Next Game); Giù (Gioco successivo)
Edit Control;Modifica controllo
Image collage;Collezione di immagini
Launch Last Game on Startup;Esegui l'ultimo gioco alla partenza
Left (Previous Display); Sinistra (Tema precedente)
Minimum Run Time;Tempo minimo di esecuzione
Minutes;minuti
Movie collage;Collezione di video
Overlay Artwork;Overlay artwork
Page Down;Pagina precedente
Page Up;Pagina seguente
Preserve Aspect Ratio;Rispetta le proporzioni
Right (Next Display); Destra (Tema successivo)
Scrape mamedb.com (MAME only);Utilizza mamedb.com (solo per MAME)
Scraped $1 artwork file(s);Immagini recuperate: $1
Up (Previous Game); Su (Gioco precedente)
XML Mode;Modo XML
en;English
es;Español
fr;Français
it;Italiano
_help_autolaunch_last_game;Esegui automaticamente l'ultimo titolo giocato
_help_control_page_down;Configura i controlli che muovono la selezione una pagina in basso
_help_control_page_up;Configura i controlli che muovono la selezione una pagina in alto
_help_scrape_mamedb;Stabilisce se utilizzare il sito mamedb.com per recuperare snapshot e marquee dei giochi MAME

#@DONE_TRANSLATED
#
# Strings still needing translation
#
Artwork Name;Artwork Name
Attract-Mode detected emulator(s) that can be imported automatically.  Import them now?;Attract-Mode detected emulator(s) that can be imported automatically.  Import them now?
Blank Game;Blank Game
Clear Hotkey?;Clear Hotkey?
Configure / Joystick Mapping;Configure / Joystick Mapping
Delete shortcut '$1'?;Delete shortcut '$1'?
Delete this Shortcut;Delete this Shortcut
Edit Shortcut;Edit Shortcut
Exit Message;Exit Message
Insert Command Shortcut;Insert Command Shortcut
Insert Display Shortcut;Insert Display Shortcut
Insert Game Entry;Insert Game Entry
Insert Menu Entry;Insert Menu Entry
Joystick $1;Joystick $1
Joystick Mappings;Joystick Mappings
Layout File;Layout File
Non-Blocking Mode Wait;Non-Blocking Mode Wait
Pause Hotkey;Pause Hotkey
Please Wait;Please Wait
Press Hotkey;Press Hotkey
Select template to use for emulator settings;Select template to use for emulator settings
_help_emu_pause_hotkey;Set a global hotkey to pause the emulator.  When pressed, Attract-Mode will pause the emulator process and return to the frontend. The emulator process can be resumed by selecting the same game again in the frontend.
_help_exit_message;Alternate message to exit the frontend [i.e. "Shut Down System"]
_help_hide_console;Hide console on startup. Note that this only works if starting Attract-Mode from a Windows GUI. If started from an existing console window (e.g. a batch file) then the process will always "attach" to the existing console and output to it.
_help_joystick_map;Map the frontend's joystick slots to specifically named joystick/gamepad devices attached to your computer (You can use this to force the frontend to always use 'Microsoft X-Box 360 pad' as Joystick 0, for example.)
_help_layout_file;Some layouts provide multiple layout*.nut files.  Select which layout file to use
_help_shortcut_artwork_name_edit;Optionally provide an artwork name to be associated with this shortcut.  The frontend will try to load artworks with this name when displaying the shortcut
_help_shortcut_delete;Delete this shortcut from the Romlist
_help_shortcut_label_edit;Edit this shortcut's label
_help_shortcut_target_edit;Edit this shortcut's target
