#@日本語 (Japanese);win_font=YuGothR,ARIALUNI,MSMINCHO;mac_font=Osaka;linux_font=TakaoGothic,TakaoPGothic,NotoSansCJK-Regular
#
# Interface strings
#
Action;アクション
Add Artwork;アートワークを追加
Add Emulator;エミュレータを追加
Add Filter;フィルターを追加
Add Input;キー追加
Add New Display;ディスプレイを追加
Add Rule;ルールを追加
Add/Remove Favourite;お気に入り追加/削除
Add/Remove Tags;タッグ追加/削除
Additional Import File(s);追加入力ファイル
All;全て
Allow Exit from 'Displays Menu';ディスプレイメニューからのプログラム終了可能
AltRomname;Romの別称(AltRomname)
AltTitle;タイトルの別称(AltTitle)
Ambient Soundtrack;BGMファイル
Ambient Volume;BGMボリューム
Artwork Label;アートワークのレーベル
Artwork Path;アートワークの位置
Back;戻る
Category;ジャンル(Category)
CloneOf;クローン(CloneOf)
Collection/Rom List;Romファイルリスト
Command;コマンド
Command Arguments;実行パラメータ
Comparison;ルールの比較方式
Configure;設定
Configure / Controls;設定 / 入力
Configure / Displays;設定 / ディスプレイ
Configure / Emulators;設定 / エミュレータ
Configure / Miscellaneous;設定 / その他
Configure / Plug-ins;設定 / プラグイン
Configure / Scraper;設定 / オンラインゲーム情報
Configure / Sound;設定 / サウンド
Configure Plug-in;プラグインを設定
Configure Screen Saver;スクリーンセーバー設定
Confirm Favourites;お気に入りの確認
Control;コントローラ(Control)
Controls;入力
Custom1;カスタム 1
Custom2;カスタム 2
Custom3;カスタム 3
Custom4;カスタム 4
Custom5;カスタム 5
Custom6;カスタム 6
Default Font;基本フォント
Delete display '$1'?;ディスプレイ '$1' を削除してもよろしいですか？
Delete emulator '$1'?;'$1' エミュレータを削除しますか?
Delete filter '$1'?;'$1' フィルターを削除しますか？
Delete this Display;このディスプレイを削除
Delete this Emulator;エミュレータを削除
Delete this Filter;このフィルターを削除
Delete this Rule;このルールを削除
Disabled;無効
Display Edit;ディスプレイを設定
Display Name;ディスプレイの名前
DisplayCount;ディスプレイの数(DisplayCount)
DisplayType;ディスプレイタイプ(DisplayType)
Displays;ディスプレイ
Displays Menu;ディスプレイメニュー
Down;下
Edit Artwork;アートワークを編集
Edit Emulator;エミュレータを編集
Edit Input;入力編集
Emulator;エミュレータ(Emulator)
Emulator Name;エミュレータの名前
Emulators;エミュレータ
Enabled;使用する
Enter Display Name;新しいディスプレイの名前を入力して下さい
Enter Emulator Name;エミュレータの名前を入力して下さい
Enter Filter Name;フィルターの名前を入れて下さい
Executable;実行ファイル
Exit;終了 (Yes/No 確認)
Exit Attract-Mode;プログラムを終了
Exit Attract-Mode?;終了しますか?
Exit Command;終了コマンド
Exit Hotkey;終了ホットキー
Exit to Desktop;終了
Extra;その他(Extra)
Favourite;お気に入り
FileIsAvailable;Romファイルの存在
Fill Screen (Default);全画面に広げる (デフォルト)
Filter;フィルター
Filter Edit;フィルターを編集
Filter Name;フィルターの名前
Filter Value;フィルターの表現式
Filter Wrap Mode;リストの最後のフィルターに着いた時
Filters Menu;フィルターメニュー
Flip;180°
Font Path;フォントの位置
Fullscreen Mode;全画面モード
Game Return Sound;ゲーム終了のサウンド
General;その他
Generate Collection/Rom List;Romファイルリストを作成
Generating Rom List: $1%;Romファイルリストを作成しています: $1%
Global Filter;グローバルフィルターの設定
Hide Brackets in Game Title;ゲームタイトルのブラケットを隠す
Info Source/Scraper;情報元 設定
Joystick Threshold;ジョイスティックの感度
Jump to Next Display;次のリストに
Language;言語
Layout;レイアウットの名前
Layout Options;レイアウト別設定
Left;270°
List Limit;リストのサイズ限度
Manufacturer;発売元(Manufacturer)
Mouse Threshold;マウスの感度
Movie Volume;ムービーボリューム
Name;名前
Next Display;次のディスプレイ
Next Favourite;前のお気に入り
Next Filter;次のフィルター
Next Letter;次の文字
No;いいえ
No Sort;並び替えない
No Wrap;何もしない
None;0°
OR;又は
Overwrite existing '$1' list?;既存のRomファイルリスト '$1' に上書きしてもよろしいですか?
PlayedCount;プレイ数
PlayedTime;プレイ時間
Players;プレイヤー数(Players)
Plug-ins;プラグイン
Press Input;キーを押してください
Previous Display;前のディスプレイ
Previous Favourite;次のお気に入り
Previous Filter;前のフィルター
Previous Letter;前の文字
Random Game;任意のゲーム選択
Remove Input;キー削除
Replay Last Game;最後にプレイしたゲームを再プレイ
Right;90°
Rom Extension(s);Romファイルの拡張子
Rom Path(s);Romファイルの位置
Rom path '$1' not found, proceed anyways?;Romファイル経路 '$1' が存在しません. 続きますか?
Rotation;ディスプレイ回転(Rotation)
Rule;ルール
Rule Edit;ルール編集
Scrape Artwork;ファンアートーワークをダウンロード
Scrape Flyers/Boxart;箱のアートーワーク, ポスターをダウンロード
Scrape Game Logos (Wheel Art);ゲームロゴをダウンロード (Wheel Art)
Scrape Marquees;Marqueeをダウンロード
Scrape Snaps;スクリーンショットをダウンロード
Scraper;オンラインゲーム情報出典
Scraping Artwork: $1%;オンラインから $1% をダウンロード中です
Screen Saver;スクリーンセーバー
Screen Saver Timeout;スクリーンセーバーのタイムアウト時間
Screenshot;スクリーンショット
Select;選択
Sort By;並び替え
Sound;サウンド
Sound Volume;サウンドボリューム
Startup Sound;プログラム起動のサウンド
Status;エミュレーションレベル(Status)
System Identifier;システムのID
Tags;タッグ
Target;ルールのターゲット
The name for this filter;このフィルターの名前
This will overwrite an existing mapping ($1).  Proceed?;既存の入力 ($1) を上書きしてもよろしいですか？
Title;タイトル(Title)
Toggle Flip;画面 180°回転
Toggle Layout;レイアウット選択
Toggle Movie;ムービー再生
Toggle Mute;ミュート
Toggle Rotate Left;画面 270°回転
Toggle Rotate Right;画面 90°回転
Track Usage;プレイ時間記録
Up;上
Window;ウィンドウモード
Window Mode;スクリーンモードー
Wrap within Display (Default);リストの最初のフィルターに (デフォルト)
Wrote $1 entries to Collection/Rom List;$1 個のRomファイルをリストに記録しました
Year;発売年(Year)
Yes;はい
contains;含む
does not contain;含まない
does not equal;一致しない
equals;一致する

#
# Help messages
#
_help_art_add;新しいアートワーク (スクリンショット, タイトル, ムービー) を追加します
_help_art_label;指定したレーベルがレイアウトに使われます
_help_art_path;アートワークの位置です
_help_confirm_favs;お気に入りのゲームを追加,削除する時, Yes/Noで確認するかを設定します
_help_control_add_favourite;現在選択されたゲームをお気に入りに追加/削除するキーを設定します
_help_control_add_tags;現在選択されたゲームのタッグを編集するキーを設定します
_help_control_configure;この '設定画面' を表示するキーを設定します
_help_control_custom1;カスタムキー1を設定します
_help_control_custom2;カスタムキー2を設定します
_help_control_displays_menu;'リストメニュー' を表示するキーを設定します
_help_control_down;下に移動するキーを設定します
_help_control_exit;このプログラムを終了するキーを設定します
_help_control_exit_to_desktop;このプログラムを確認無しで終了するキーを設定します
_help_control_filters_menu;'フィルターメニュー' を表示するキーを設定します
_help_control_next_display;次のリストに移動するキーを設定します
_help_control_next_favourite;次のお気に入りゲームに移動するキーを設定します
_help_control_next_filter;次のフィルターに移動するキーを設定します
_help_control_next_letter;次のアルファベットに移動するキーを設定します
_help_control_prev_display;前のリストに移動するキーを設定します
_help_control_prev_favourite;前のお気に入りゲームに移動するキーを設定します
_help_control_prev_filter;前のフィルターに移動するキーを設定します
_help_control_prev_letter;前のアルファベットに移動するキーを設定します
_help_control_random_game;任意のゲームを選択するキーを設定します
_help_control_replay_last_game;最後にプレイしたゲームを再びプレイするキーを設定します
_help_control_screen_saver;スクリーンショットを起動するキーを設定します
_help_control_screenshot;スクリーンショットを撮るキーを設定します
_help_control_select;現在選択されたゲームをプレイするキーを設定します
_help_control_toggle_flip;画面を180°回転するキーを設定します
_help_control_toggle_layout;レイアウットを変更するキーを設定します. (レイアウットにより無視される場合があります)
_help_control_toggle_movie;ムービーの再生をオン/オフにするキーを設定します
_help_control_toggle_mute;ミュートするキーを設定します
_help_control_toggle_rotate_left;画面を反時計回りに90°回転するキーを設定します
_help_control_toggle_rotate_right;画面を時計回りに90°回転するキーを設定します
_help_control_up;上に移動するキーを設定します
_help_controls;様々な入力を設定します
_help_default_font;プログラムが基本で使うフォントの名前を指定します
_help_display_add;新しいディスプレイを追加します
_help_display_add_filter;ディスプレイに新しいフィルターを追加します
_help_display_delete;このディスプレイを削除します
_help_display_filter;このディスプレイのフィルターを設定します
_help_display_global_filter;このリスト全体に適用するグローバルフィルターを設定します
_help_display_layout;このディスプレイが使うレイアウットを設定します
_help_display_layout_options;レイアウトで指定されたオプションを設定できます
_help_display_name;このディスプレイの名前です
_help_display_romlist;このディスプレイが使うRomファイルリストを設定します
_help_display_sel;このディスプレイを設定します
_help_displays;ディスプレイ(ゲームリスト)を設定します
_help_displays_menu_exit;ディスプレイメニューに"プログラム終了"項目を追加するか設定します
_help_emu_add;新しいエミュレータを登録します
_help_emu_args;エミュレータの実行パラメータを設定します. 以下のパラメータはその内容で置換されます : [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_emu_delete;エミュレータに関する設定を削除します
_help_emu_executable;エミュレータの実行ファイルの位置を指定します. $HOMEはユーザーのホームディレクトリに置換されます
_help_emu_exit_hotkey;このエミュレータを終了するグローバルホットキーを設定します. このホットキーを押せばこのエミュレータを強制終了できます.
_help_emu_gen_romlist;指定されたRomファイルの位置, XML モード, 追加ファイル (catver.ini 等) を使ってRomファイルリストを作成します
_help_emu_import_extras;Romファイルリストの作成時に追加で使うファイルを指定します. ジャンル (catver.ini), またはプレイ人数 (nplayers.ini) などを使えます
_help_emu_info_source;mess : MAME タイプの -listxml, mess : MESS タイプの -listsoftware, thegamesdb.net : このサイトを使う, steam : steamサイトを使う. mess, thegamesdb.net の場合IDを正しく設定する必要があります.
_help_emu_nb_mode_wait; 最小の実行時間を秒単位で設定します. 普通は0で構わないですが,一部のゲーム(steam等)には適当に設定する必要があります
_help_emu_romext;Romファイルの拡張子(.zip 等)を指定します. セミコロン(
_help_emu_rompath;エミュレータのRomファイルの位置を指定します
_help_emu_scrape_artwork;TheGamesDB.net または mamedb.com からゲームの情報をダウンロードします
_help_emu_sel;エミュレータの設定を変更します
_help_emu_system;このエミュレータのIDです. セミコロン(
_help_emulators;エミュレータを設定します
_help_exit_command;終了 (Yes/No 確認) でプログラムを終了する時に実行する外部コマンドを設定します (例. "sudo shutdown")
_help_filter_add_rule;このフィルターに新しいルールを追加します
_help_filter_delete;このフィルターを削除します
_help_filter_list_limit;リストのサイズに制限を付けます. プラスで上からの××個, マイナスで下からの××個を設定します. 0 は無限です.
_help_filter_name;フィルターの名前
_help_filter_rule;フィルターのルールを設定します
_help_filter_sort_by;リストの並び方を設定します. "並び替えない" で元の順番で並べます.
_help_filter_wrap_mode;リストの最後のフィルターで"次のフィルター"が押された時, どのように反応するかを設定します.
_help_font_path;フォントの位置を設定します.セミコロン(
_help_hide_brackets;ゲームのタイトルを表示する時, ブラケットに囲まれた部分は隠すかを設定します
_help_input_add;入力キーを追加します
_help_input_delete;入力キーを削除します
_help_joystick_threshold;ジョイスティックの感度を設定します. (1から100まで), 高いほど鈍感です
_help_language;言語を設定します
_help_misc;その他を設定します
_help_mouse_threshold;マウスの感度を設定します. (1から100まで), 高いほど鈍感です
_help_plugin_command;プラグインのコマンドを設定します
_help_plugin_enabled;プラグインを使うかを設定します
_help_plugin_sel;プラグインを設定します
_help_plugins;外部プラグインを設定します
_help_rule_comp;フィルターのルールを比較する方式を設定します
_help_rule_delete;このルールを削除します
_help_rule_target;フィルターが使うゲームのカテゴリーを設定します
_help_rule_value;フィルターのルールを正規表現で設定します. 例えばターゲットが"発売年"で,比較方式が"一致する"で,表現式が"1984"の場合,1984年に発売されたゲームのみ表示されます．"198."の場合 1980年代の全てのゲームが表示されます.　"(198.)|(199.)"の場合1980年代と1990年代の全てのゲームを表示します
_help_scrape_fanart;オンラインからファンアートーワークをダウンロードするかを設定します
_help_scrape_flyers;オンラインから箱のアートーワーク, ポスターをダウンロードするかを設定します
_help_scrape_marquees;オンラインからMarqueeをダウンロードするかを設定します
_help_scrape_snaps;オンラインからスクリーンショットをダウンロードするかを設定します
_help_scrape_wheels;オンラインからWheel Artタイプのゲームロゴをダウンロードするかを設定します
_help_scraper;ゲームの情報を担当するオンラインサイトを設定します
_help_screen_saver;スクリーンセーバーを設定します
_help_screen_saver_timeout;何秒まで入力が無ければスクリーンセーバーを起動するかを設定します. 0 でスクリーンセーバーをオフにします
_help_sound;効果音, 背景音楽, ボリューム等を設定します
_help_sound_sel;この状態でプレイするサウンドを設定します
_help_track_usage;ゲームのプレイ内容(プレイ数,プレイ時間)を記録するかを設定します.
_help_volume;ボリュームを設定します(0から100まで), 0はミュートです
_help_window_mode;.Attract-Mode がウィンドウモードで起動するかフルスクリーンモードで起動するかを設定します
_sort_regexp;^(Vs\. The |The |Vs\. )

#
# Extra strings provided by translation
#
Add a rule to this filter;ルールー追加
Ambient Sounds;BGMファイル
Configure available emulators;エミュレータの設定
Configure filter rule;フィルターのルールー編集
Delete this filter;このフィルターを削除
Exit menu;出る
Launch Last Game on Startup;最後にプレイしたゲームを次の起動時 再起動
Minimum Run Time;最小実行時間
Page Down;1画面下
Page Up;1画面上
XML Mode;XML モード
en;英語
fr;フランス語
jp;日本語
kr;韓国語
_help_autolaunch_last_game;プラグラムの起動時, 最後にプレイしたゲームを一緒に起動するかを設定します
_help_control_page_down;1ページ下に移動するキーを設定します
_help_control_page_up;1ページ上に移動するキーを設定します
_help_control_sel;
_help_emu_listxml;

#@DONE_TRANSLATED
#
# Strings still needing translation
#
$1 Rule(s);$1 Rule(s)
Add '$1' to Favourites?;Add '$1' to Favourites?
Add Exception;Add Exception
Add tag: '$1';Add tag: '$1'
Artwork Name;Artwork Name
Attract-Mode detected emulator(s) that can be imported automatically.  Import them now?;Attract-Mode detected emulator(s) that can be imported automatically.  Import them now?
Blank Game;Blank Game
Buttons;Buttons
Clear Hotkey?;Clear Hotkey?
Configure / Displays Menu;Configure / Displays Menu
Configure / Joystick Mapping;Configure / Joystick Mapping
Configure Intro;Configure Intro
Configure Layout;Configure Layout
Confirm Exit;Confirm Exit
Create new tag;Create new tag
Custom Arguments;Custom Arguments
Custom Executable;Custom Executable
Default;Default
Default Action;Default Action
Delete game '$1'?;Delete game '$1'?
Delete shortcut '$1'?;Delete shortcut '$1'?
Delete this Game;Delete this Game
Delete this Shortcut;Delete this Shortcut
Edit Game;Edit Game
Edit Shortcut;Edit Shortcut
Empty;Empty
Enable Multiple Monitors;Enable Multiple Monitors
Enter Romlist Name;Enter Romlist Name
Enter new tag name;Enter new tag name
Exception;Exception
Exception Edit;Exception Edit
Exit Message;Exit Message
Insert Command Shortcut;Insert Command Shortcut
Insert Display Shortcut;Insert Display Shortcut
Insert Game Entry;Insert Game Entry
Insert Menu Entry;Insert Menu Entry
Intro;Intro
Joystick $1;Joystick $1
Joystick Mappings;Joystick Mappings
Launch Last Game;Launch Last Game
Layout File;Layout File
Menu Prompt;Menu Prompt
Menu Style / Layout;Menu Style / Layout
Next Game;Next Game
Next Page;Next Page
Non-Blocking Mode Wait;Non-Blocking Mode Wait
Overview;Overview
Pause Hotkey;Pause Hotkey
Play Sound;Play Sound
Please Wait;Please Wait
Press Hotkey;Press Hotkey
Previous Game;Previous Game
Previous Page;Previous Page
Remove '$1' from Favourites?;Remove '$1' from Favourites?
Remove tag: '$1';Remove tag: '$1'
Scrape Fanart;Scrape Fanart
Scrape Videos (MAME only);Scrape Videos (MAME only)
Select template to use for emulator settings;Select template to use for emulator settings
Show Displays Menu;Show Displays Menu
Show Last Selection (Default);Show Last Selection (Default)
Show in Cycle;Show in Cycle
Show in Menu;Show in Menu
Startup Mode;Startup Mode
Video Decoder;Video Decoder
Window (No Border);Window (No Border)
Working Directory;Working Directory
multi;multi
_help_art;An artwork resource available for use by layouts
_help_back;Exit menu
_help_confirm_exit;Confirm before exiting Attact-Mode?
_help_control_back;Set the control(s) that go back
_help_control_custom3;Set the "Custom3" control(s)
_help_control_custom4;Set the "Custom4" control(s)
_help_control_custom5;Set the "Custom5" control(s)
_help_control_custom6;Set the "Custom6" control(s)
_help_control_edit_game;Set the control(s) to edit the current selection
_help_control_intro;Set the control(s) that show the intro video
_help_control_left;Set the control(s) that move the selection left
_help_control_next_game;Set the control(s) that move to the next game
_help_control_next_page;Set the control(s) that move the selection up one page
_help_control_prev_game;Set the control(s) that move to the previous game
_help_control_prev_page;Set the control(s) that move the selection down one page
_help_control_right;Set the control(s) that move the selection right
_help_display_in_cycle;Include this display in the "Previous Display"/"Next Display" cycle?
_help_display_in_menu;Include this display in the "Displays Menu"?
_help_displays_menu;Configure options for the "Displays Menu"
_help_displays_menu_layout;The layout to use for the 'Displays Menu'. Set to 'Default' to use the frontend's built-in menu
_help_displays_menu_prompt;The 'Displays Menu' prompt (i.e. "Select System")
_help_emu_pause_hotkey;Set a global hotkey to pause the emulator.  When pressed, Attract-Mode will pause the emulator process and return to the frontend. The emulator process can be resumed by selecting the same game again in the frontend.
_help_emu_sel_gen_romlist;Generate a Collection/Romlist containing games for multiple emulators
_help_emu_workdir;The working directory for this emulator.  This is the directory that the frontend runs the emulator from.  Also, any relative rom paths, artwork paths, or additional import file paths are treated as being relative to this directory
_help_exit_message;Alternate message to exit the frontend [i.e. "Shut Down System"]
_help_filter_add_exception;Add an exception to this filter.  If a game matches an exception (and wasn't filtered out by an earlier rule) it will be listed in the filter
_help_filter_exception;Configure this filter exception.  If a game matches an exception it will be listed in the filter.  Rules and exceptions get applied in the order that they are listed
_help_game_custom_args;Set this to override the default command line arguments for this game.  Set this to [nothing] if you want to override with no parameters.  The following get substituted appropriately: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_game_custom_executable;Set this to override the default executable for this game
_help_game_delete;Delete this game from the Romlist
_help_game_edit;Edit this game information
_help_game_overview;Edit game overview
_help_generator_build;Generate romlist with the selected emulator(s)
_help_generator_opt;Set whether this emulator is to be included in the generated romlist
_help_hide_console;Hide console on startup. Note that this only works if starting Attract-Mode from a Windows GUI. If started from an existing console window (e.g. a batch file) then the process will always "attach" to the existing console and output to it.
_help_input_action;
_help_input_default_action;Set the default behaviour for this control
_help_intro;Configure intro
_help_joystick_map;Map the frontend's joystick slots to specifically named joystick/gamepad devices attached to your computer (You can use this to force the frontend to always use 'Microsoft X-Box 360 pad' as Joystick 0, for example.)
_help_layout_file;Some layouts provide multiple layout*.nut files.  Select which layout file to use
_help_multiple_monitors;Enable the use of multiple monitors by Attract-Mode.  Setting this to 'No' may reduce screen flicker when launching games
_help_scrape_vids;Set whether game videos should be downloaded when scraping
_help_shortcut_artwork_name_edit;Optionally provide an artwork name to be associated with this shortcut.  The frontend will try to load artworks with this name when displaying the shortcut
_help_shortcut_delete;Delete this shortcut from the Romlist
_help_shortcut_label_edit;Edit this shortcut's label
_help_shortcut_target_edit;Edit this shortcut's target
_help_startup_mode;Set what should happen when Attract-Mode first starts up
_help_video_decoder;Configure the decoder to use for video playback (if multiple decoders are available)
