#@한국어 (Korean);win_font=ARIALUNI,DOTUM,MALGUN;mac_font=AppleSDGothicNeo;linux_font=UnDotum,NotoSansCJK-Regular
#
# Interface strings
#
$1 Rule(s);$1 규칙
Action;기능
Add '$1' to Favourites?;'$1' 게임을 즐겨하는 목록에 추가하겠습니까?
Add Artwork;동영상/그림 추가
Add Emulator;새 에뮬레이터 등록
Add Exception;예외 추가
Add Filter;필터 추가
Add Input;입력 추가
Add New Display;목록 추가
Add Rule;규칙 추가
Add tag: '$1';'$1' 태그 추가
Add/Remove Favourite;즐겨하는 게임 추가/삭제
Add/Remove Tags;태그 추가/삭제
Additional Import File(s);기타 입력 파일
All;전체
Allow Exit from 'Displays Menu';목록 관리 메뉴에서 프로그램 종료 가능
AltRomname;롬 별칭(AltRomname)
AltTitle;제목 별칭(AltTitle)
Ambient Soundtrack;배경 음악
Ambient Volume;배경 음악 음량
Artwork Label;아트워크 라벨
Artwork Name;이트워크 이름
Artwork Path;아트워크 경로
Back;뒤로 가기
Blank Game;빈 게임
Buttons;버튼
Category;장르(Category)
CloneOf;원작(CloneOf)
Collection/Rom List;롬 목록 파일
Command;명령어
Command Arguments;실행 인자
Comparison;비교 조건
Configure;설정
Configure / Controls;설정 / 입력
Configure / Displays;목록 설정
Configure / Displays Menu;설정 / 목록 관리 메뉴
Configure / Emulators;설정 / 에뮬레이터 관련
Configure / Joystick Mapping;설정 / 조이스틱 매핑
Configure / Miscellaneous;설정 / 기타
Configure / Plug-ins;설정 / 플러그 인
Configure / Scraper;온라인 정보원 설정
Configure / Sound;설정 / 소리
Configure Intro;인트로 설정
Configure Layout;레이아웃 설정
Configure Plug-in;플러그 인 설정
Configure Screen Saver;화면 보호기 설정
Confirm Exit;종료 확인
Confirm Favourites;즐겨하는 게임 확인 창 표시
Control;입력 장치(Control)
Controls;입력
Create new tag;새 태그 설정
Custom Arguments;사용자 정의 매개변수
Custom Executable;사용자 정의 실행 파일
Custom1;사용자 정의 1
Custom2;사용자 정의 2
Custom3;사용자 정의 3
Custom4;사용자 정의 4
Custom5;사용자 정의 5
Custom6;사용자 정의 6
Default;기본값
Default Action;기본 행동
Default Font;기본 폰트
Delete display '$1'?;'$1' 목록을 제거하시겠습니까?
Delete emulator '$1'?;'$1' 에뮬레이터를 삭제하시겠습니까?
Delete filter '$1'?;'$1' 필터를 삭제하시겠습니까?
Delete game '$1'?;'$1' 게임을 삭제하겠습니까?
Delete shortcut '$1'?;'$1' 바로가기를 삭제하겠습니까? 
Delete this Display;목록 삭제
Delete this Emulator;에뮬레이터 삭제
Delete this Filter;필터 삭제
Delete this Game;게임 삭제
Delete this Rule;규칙 삭제
Delete this Shortcut;바로가기 삭제
Disabled;비활성
Display Edit;목록 편집
Display Name;목록 이름
DisplayCount;디스플레이 수(DisplayCount)
DisplayType;디스플레이 종류(DisplayType)
Displays;목록
Displays Menu;목록 관리 메뉴
Down;아래
Edit Artwork;아트워크 정보 편집
Edit Emulator;에뮬레이터 편집
Edit Game;게임 편집
Edit Input;입력 편집
Edit Shortcut;바로가기 편집
Empty;(없음)
Emulator;에뮬레이터
Emulator Name;에뮬레이터 이름
Emulators;에뮬레이터
Enable Multiple Monitors;다중 모니터 사용
Enabled;활성화 여부
Enter Display Name;새 목록의 이름을 입력하여 주십시오
Enter Emulator Name;에뮬레이터의 이름을 입력하여 주십시오
Enter Filter Name;필터 이름을 입력하여 주십시오
Enter Romlist Name;새 롬 목록 이름을 입력하십시오
Enter new tag name;새 태그 이름을 입력하십시오
Exception;예외 규칙
Exception Edit;예외 편집
Executable;실행 파일
Exit;확인 후 종료
Exit Attract-Mode;프로그램 종료
Exit Attract-Mode?;종료하시겠습니까?
Exit Command;종료 명령어
Exit Hotkey;종료 핫키
Exit to Desktop;바탕화면으로 나가기
Extra;기타정보(Extra)
Favourite;즐겨찾기
FileIsAvailable;롬파일 존재여부
Fill Screen (Default);전체 화면 크기로 확장 (기본값)
Filter;필터
Filter Edit;필터를 편집합니다
Filter Name;필터 이름
Filter Value;필터 값
Filter Wrap Mode;목록의 마지막 필터에 도달하였을 때
Filters Menu;필터 관리 메뉴
Flip;180도
Font Path;폰트 경로
Fullscreen Mode;전체 화면 모드
Game Return Sound;게임 종료 시 소리 파일
General;기타
Generate Collection/Rom List;롬 목록 생성
Generating Rom List: $1%;롬 목록을 생성중입니다 ($1%)
Global Filter;전역 필터 설정
Hide Brackets in Game Title;게임 제목에서 괄호 생략
Info Source/Scraper;외부 정보 제공자 설정
Insert Command Shortcut;명령어 바로가기 추가
Insert Display Shortcut;창 바로가기 추가
Insert Game Entry;게임 추가
Insert Menu Entry;메뉴 추가
Intro;인트로 영상
Joystick $1;$1 조이스틱
Joystick Mappings;조이스틱 매핑
Joystick Threshold;조이스틱 민감도
Jump to Next Display;다음 목록
Language;언어 설정
Launch Last Game;마지막 게임 실행
Layout;레이아웃 이름
Layout Options;레이아웃 별 옵션
Left;270도
List Limit;목록 크기 제한
Manufacturer;제작사(Manufacturer)
Menu Prompt;화면에 표시할 메뉴 이름
Menu Style / Layout;메뉴 스타일 / 레이아웃
Mouse Threshold;마우스 민감도
Movie Volume;동영상 음량
Name;이름
Next Display;다음 목록으로
Next Favourite;다음 즐겨하는 게임
Next Filter;다음 필터로
Next Game;다음 게임
Next Letter;다음 글자
Next Page;다음 페이지
No;아니오
No Sort;정렬 안 함
No Wrap;아무 것도 하지 않음
None;0도
OR;또는
Overview;설명
Overwrite existing '$1' list?;기존의 롬 목록 '$1' 에 덮어써도 좋습니까?
Play Sound;소리 재생
PlayedCount;플레이 횟수
PlayedTime;플레이 시간
Players;플레이어 수(Players)
Plug-ins;외부 플러그 인
Press Input;키를 누르십시오
Previous Display;이전 목록
Previous Favourite;이전 즐겨하는 게임
Previous Filter;이전 필터로
Previous Game;이전 게임
Previous Letter;이전 글자
Previous Page;이전 페이지
Random Game;랜덤 게임 선택
Remove '$1' from Favourites?;'$1' 게임을 즐겨하는 목록에서 제거하겠습니까?
Remove Input;입력 삭제
Remove tag: '$1';'$1' 태그 제거
Replay Last Game;마지막으로 한 게임 다시 실행
Right;90도
Rom Extension(s);롬 파일 확장자
Rom Path(s);롬 파일 경로
Rom path '$1' not found, proceed anyways?;롬 파일 경로 '$1' 가 존재하지 않습니다. 계속 진행하시겠습니까?
Rotation;화면 회전 방향(Rotation)
Rule;규칙
Rule Edit;규칙 편집
Scrape Artwork;팬 아트워크 다운로드
Scrape Fanart;외부 팬아트 다운로드
Scrape Flyers/Boxart;박스 아트, 홍보 포스터 다운로드
Scrape Game Logos (Wheel Art);게임 로고 (Wheel Art) 다운로드
Scrape Marquees;Marquee 다운로드
Scrape Snaps;스크린샷 다운로드
Scrape Videos (MAME only);외부 영상 다운로드 (MAME 전용)
Scraper;온라인 게임 정보 출처
Scraping Artwork: $1%;온라인에서 $1% 을 다운로드하는 중입니다
Screen Saver;화면 보호기
Screen Saver Timeout;화면 보호기 타임아웃 시간
Screenshot;스크린샷
Select;선택
Show Displays Menu;목록 관리 메뉴 표시
Show Last Selection (Default);마지막 메뉴 표시 (기본값)
Show in Cycle;사이클에 보이기
Show in Menu;목록 관리 메뉴에 보이기
Sort By;목록 정렬 기준
Sound;소리
Sound Volume;효과음 음량
Startup Mode;시작 모드
Startup Sound;프로그램 시작 소리 파일
Status;에뮬레이션 수준(Status)
System Identifier;시스템 식별자
Tags;태그 정보
Target;규칙의 대상
The name for this filter;본 필터의 이름
This will overwrite an existing mapping ($1).  Proceed?;기존 입력 ($1)을 덮어써도 되겠습니까?
Title;제목(Title)
Toggle Flip;화면 180도 회전
Toggle Layout;레이아웃 변경
Toggle Movie;동영상 켜기/끄기
Toggle Mute;음소거
Toggle Rotate Left;화면 270도 회전
Toggle Rotate Right;화면 90도 회전
Track Usage;플레이 시간/횟수 기록
Up;위
Video Decoder;비디오 디코더
Window;창 모드
Window (No Border);창 모드 (테두리 없음)
Window Mode;화면 모드
Working Directory;작업 디렉토리
Wrap within Display (Default);해당 목록의 첫 필터로 (기본값)
Wrote $1 entries to Collection/Rom List;총 $1 개의 롬 파일을 목록에 기록하였습니다.
Year;제작연도(Year)
Yes;예
contains;포함
does not contain;미포함
does not equal;불일치
equals;일치
multi;다중 목록

#
# Help messages
#
_help_art;레이아웃에서 사용되는 아트워크 등 리소스의 경로를 설정합니다
_help_art_add;새로운 아트워크 (스크린샷, 타이틀 화면, 기타 동영상 등) 를 추가할 수 있습니다
_help_art_label;지정된 라벨명이 레이아웃에서 사용됩니다
_help_art_path;해당 동영상/그림 파일의 경로입니다
_help_back;메뉴를 빠져나갑니다
_help_confirm_exit;프로그램을 정말로 종료할 것인지 묻습니다
_help_confirm_favs;즐겨하는 게임을 추가/삭제할 때에 사용자에게 Yes/No 로 물을 지 여부를 설정합니다
_help_control_add_favourite;현재 선택된 게임을 즐겨찾기에 추가/삭제 하는 키를 설정합니다
_help_control_add_tags;현재 선택된 게임의 태그를 편집하는 키를 설정합니다
_help_control_back;뒤로 가기 버튼을 설정합니다
_help_control_configure;본 '설정 화면' 을 띄우는 키를 설정합니다
_help_control_custom1;사용자 지정 키 1을 설정합니다
_help_control_custom2;사용자 지정 키 2를 설정합니다
_help_control_custom3;사용자 지정 키 3을 설정합니다
_help_control_custom4;사용자 지정 키 4를 설정합니다
_help_control_custom5;사용자 지정 키 5를 설정합니다
_help_control_custom6;사용자 지정 키 6을 설정합니다
_help_control_displays_menu;'목록 메뉴' 를 호출하는 키를 설정합니다
_help_control_down;아래 항목으로 한 칸 이동하는 키를 설정합니다
_help_control_edit_game;선택한 게임을 편집하는 키를 설정합니다
_help_control_exit;본 프로그램을 종료하는 키를 설정합니다
_help_control_exit_to_desktop;본 프로그램을 확인 창 없이 바로 종료하는 키를 설정합니다.
_help_control_filters_menu;'필터 메뉴' 를 호출하는 키를 설정합니다.
_help_control_intro;인트로 영상을 표시할 키를 설정합니다
_help_control_left;왼쪽 항목으로 한 칸 이동하는 키를 설정합니다
_help_control_next_display;다음 항목으로 이동하는 키를 설정합니다.
_help_control_next_favourite;다음 즐겨찾기 게임으로 이동하는 키를 설정합니다.
_help_control_next_filter;다음 필터로 이동하는 키를 설정합니다.
_help_control_next_game;다음 게임으로 이동하는 키를 설정힙니다
_help_control_next_letter;다음 글자로 이동하는 키를 설정합니다.
_help_control_next_page;다음 페이지로 이동하는 키를 설정힙니다
_help_control_prev_display;이전 목록으로 이동하는 키를 설정합니다.
_help_control_prev_favourite;이전 즐겨찾기 게임으로 이동하는 키를 설정합니다.
_help_control_prev_filter;이전 필터로 이동하는 키를 설정합니다.
_help_control_prev_game;이전 게임으로 이동하는 키를 설정힙니다
_help_control_prev_letter;이전 글자로 이동하는 키를 설정합니다.
_help_control_prev_page;이전 페이지로 이동하는 키를 설정힙니다
_help_control_random_game;랜덤한 게임을 선택하는 키를 설정합니다.
_help_control_replay_last_game;마지막으로 실행했던 게임을 다시 실행하는 키를 설정합니다.
_help_control_right;오른쪽 항목으로 한 칸 이동하는 키를 설정합니다
_help_control_screen_saver;화면 보호기를 활성화하는 키를 설정합니다.
_help_control_screenshot;스크린샷을 찍는 키를 설정합니다.
_help_control_select;현재 선택된 게임을 실행하는 키를 설정합니다.
_help_control_toggle_flip;화면을 180도 회전하는 키를 설정합니다.
_help_control_toggle_layout;레이아웃을 변경하는 키를 설정합니다. (사용중인 레이아웃에 따라 동작 여부가 달라질 수 있습니다.)
_help_control_toggle_movie;동영상 재생을 켜고 끄는 키를 설정합니다.
_help_control_toggle_mute;음소거 키를 설정합니다.
_help_control_toggle_rotate_left;화면을 반시계 방향으로 90도 회전하는 키를 설정합니다.
_help_control_toggle_rotate_right;화면을 시계 방향으로 90도 회전하는 키를 설정합니다.
_help_control_up;위 항목으로 한 칸 이동하는 키를 설정합니다.
_help_controls;각종 입력을 설정합니다
_help_default_font;프로그램이 기본으로 사용할 폰트 이름을 지정합니다
_help_display_add;새로운 목록을 추가합니다
_help_display_add_filter;목록에 새로운 필터를 추가합니다
_help_display_delete;목록를 삭제합니다
_help_display_filter;목록의 필터 정보를 관리합니다
_help_display_global_filter;전체 목록에 적용될 전역 필터를 설정합니다.
_help_display_in_cycle;이 목록을 "이전 목록"/"다음 목록" 사이클에 보일 지 여부를 설정합니다
_help_display_in_menu;목록 관리 메뉴에 이 화면을 추가할 지 여부를 설정합니다
_help_display_layout;목록이 사용할 레이아웃을 지정합니다
_help_display_layout_options;레이아웃에서 지정한 옵션을 바꿀 수 있습니다
_help_display_name;목록의 이름을 나타냅니다
_help_display_romlist;목록이 사용할 롬 목록 파일을 지정합니다
_help_display_sel;목록의 설정을 변경합니다
_help_displays;목록을 설정합니다
_help_displays_menu;목록 관리 메뉴를 설정합니다
_help_displays_menu_exit;목록 관리 메뉴에 '프로그램 종료' 항목을 넣을 지 여부를 설정합니다
_help_displays_menu_layout;목록 관리 메뉴에 사용할 레이아웃을 설정합니다
_help_displays_menu_prompt;목록 관리 메뉴의 이름을 지정합니다 (예: "기종 선택")
_help_emu_add;새로운 에뮬레이터를 등록합니다.
_help_emu_args;에뮬레이터에 전달할 실행 인자를 설정합니다. 이하의 항목은 각각 알맞게 치환되어 전달됩니다 : [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_emu_delete;에뮬레이터에 대한 항목을 삭제합니다.
_help_emu_executable;에뮬레이터의 실행파일 위치를 지정합니다. $HOME 은 사용자의 홈 디렉토리로 치환됩니다.
_help_emu_exit_hotkey;해당 에뮬레이터를 종료할 전역 핫키를 지정합니다. 해당 핫키가 눌리면 에뮬레이터를 강제종료합니다.
_help_emu_gen_romlist;지정된 롬 파일 경로와 XML 옵션, 추가 파일 (catver.ini 등) 을 이용하여 롬 목록을 생성합니다.
_help_emu_import_extras;롬 파일 목록 생성시에 추가로 활용할 파일을 지정합니다. 장르 (catver.ini) 나 게임 플레이 인원 (nplayers.ini) 정보를 담은 파일을 지정할 수 있습니다.
_help_emu_info_source;mess : MAME 방식의 -listxml, mess : MESS 방식의 -listsoftware, thegamesdb.net : 해당 사이트에서 정보를 취득할 경우, steam : 스팀 사이트에서 정보를 취득할 경우. mess, thegamesdb.net 의 경우 식별자가 해당 방식에 맞게 설정되어 있어야 합니다.
_help_emu_nb_mode_wait; 최소 실행 시간을 초 단위로 지정합니다. 게임 실행 시 적어도 해당 시간 만큼이 지난 후 이 프로그램으로 제어가 돌아가게 됩니다. 보통은 0 으로 설정하면 되지만, 스팀 게임은 적절한 값을 설정해주어야 합니다.
_help_emu_romext;롬 파일들의 확장자 (.zip 등) 을 지정합니다. 세미콜론을 사용해 여러 개를 지정할 수 있습니다.
_help_emu_rompath;에뮬레이터의 롬 파일들이 위치한 경로를 지정합니다. 세미콜론을 사용해 여러 개를 지정할 수 있습니다.
_help_emu_scrape_artwork;TheGamesDB.net 및 mamedb.com 에서 게임 관련 데이터를 다운로드 합니다.
_help_emu_sel;에뮬레이터의 설정을 변경합니다.
_help_emu_sel_gen_romlist;여러 에뮬레이터의 게임을 포함한 목록을 생성합니다
_help_emu_system;에뮬레이터의 식별자입니다. 세미콜론을 사용해 여러 개를 지정할 수 있습니다.
_help_emu_workdir;에뮬레이터의 작업 디렉토리를 설정합니다. 프론트엔드에서 에뮬레이터를 실행하는 데 사용되는 경로입니다. 또한 모든 상대 경로는 이 경로의 하위 경로로 취급됩니다
_help_emulators;에뮬레이터를 설정합니다
_help_exit_command;확인 후 종료 명령으로 프로그램을 끌 때 실행할 외부 명령어 입니다. (예. "sudo shutdown")
_help_filter_add_exception;필터의 예외 사항을 추가합니다. 게임이 이 규칙을 만족하고 앞의 필터에서 걸러지지 않았다면 필터에 추가될 것입니다
_help_filter_add_rule;필터에 새 규칙을 추가합니다
_help_filter_delete;본 필터를 삭제합니다.
_help_filter_exception;이 필터의 예외 사항을 설정합니다. 게임이 이 규칙을 만족하면 필터에 추가됩니다. 규칙과 필터는 추가된 순서대로 적용됩니다
_help_filter_list_limit;목록의 크기 제한을 설정할 수 있습니다. 양수는 상위 X 개, 음수는 하위 X 개를 지정하는 데 사용할 수 있습니다. 0 은 무제한입니다.
_help_filter_name;필터의 이름
_help_filter_rule;필터의 규칙을 정의합니다.
_help_filter_sort_by;목록을 정렬할 기준을 설정합니다. 원래 목록 순서대로 표시하려면 '정렬 안 함' 을 선택하십시오.
_help_filter_wrap_mode;목록의 마지막 필터에서 '다음 필터' 키가 입력되었을 때 처리 방식을 결정합니다.
_help_font_path;폰트를 찾을 경로를 지정합니다. 세미콜론을 사용해 여러 개를 지정할 수 있습니다.
_help_game_custom_args;이 게임을 실행할 에뮬레이터의 기본 매개변수를 덮어씁니다. 빈 값으로 덮어쓰려면 [nothing]을 입력하여 주십시오. 사용 가능한 매크로는 다음과 같습니다. [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_game_custom_executable;이 게임을 실행할 실행 파일을 덮어씁니다
_help_game_delete;롬 목록에서 게임을 제거합니다
_help_game_edit;게임의 정보를 편집합니다
_help_game_overview;게임의 설명을 편집합니다
_help_generator_build;선택한 에뮬레이터를 포함한 롬 목록을 생성합니다
_help_generator_opt;생성된 목록에 포함할 에뮬레이터를 선택합니다
_help_hide_brackets;게임 제목을 표시할 때에, 괄호로 둘러싸인 부분은 표시하지 않을 지 여부를 설정합니다
_help_hide_console;콘솔 창을 숨깁니다. 이 옵션은 프로그램을 윈도우 GUI상에서 실행할 때에만 적용됩니다. 이미 띄워진 콘솔 창에서 실행하는 경우 (예: 배치 파일에서 실행하는 경우) Attract-Mode 프로세스는 해당 창에 달라붙을 것입니다.
_help_input_add;입력 키를 추가합니다
_help_input_default_action;이 키의 기본 행동을 설정합니다
_help_input_delete;해당 입력 키를 삭제합니다
_help_intro;인트로 영상을 설정합니다
_help_joystick_threshold;조이스틱 입력 민감도를 설정합니다. 1에서 100까지이며, 클수록 덜 민감합니다
_help_language;언어를 설정합니다
_help_misc;그 외 여러 가지 설정을 변경합니다
_help_mouse_threshold;마우스 입력 민감도를 설정합니다. 1 에서 100까지이며, 클수록 덜 민감합니다
_help_multiple_monitors;다중 모니터 환경을 사용할 지 여부를 설정합니다
_help_plugin_command;플러그 인의 실행 파일을 지정합니다
_help_plugin_enabled;플러그 인을 사용할 지 여부를 설정합니다
_help_plugin_sel;플러그 인을 설정합니다
_help_plugins;외부 플러그 인을 설정합니다
_help_rule_comp;필터에 속한 규칙을 설정합니다
_help_rule_delete;해당 규칙을 삭제합니다
_help_rule_target;필터가 게임의 어떤 특성을 가지고 걸러낼 지를 설정합니다
_help_rule_value;필터의 규칙을 정규 표현식으로 설정합니다. 예를 들어 규칙 대상이 '연도' 이며 비교 조건이 '일치' 에 표현식이 "1984" 이면 1984년도에 제작된 게임만 표시합니다. "198." 이면 1980년도에 제작된 모든 게임이 표시됩니다. "(198.)|(199.)" 은 1980년도 및 1990년도의 모든 게임을 표시합니다.
_help_scrape_fanart;온라인에서 팬들이 그린 그림을 다운로드 할지 설정합니다.
_help_scrape_flyers;온라인에서 게임 홍보 포스터 / 박스 아트를 다운로드 할지 설정합니다.
_help_scrape_marquees;온라인에서 Marquee를 다운로드 할지 설정합니다.
_help_scrape_snaps;온라인에서 스크린샷을 다운로드 할지 설정합니다.
_help_scrape_vids;게임 영상을 가져올 지 여부를 설정합니다
_help_scrape_wheels;온라인에서 Wheel Art 형식의 게임 로고를 다운로드 할지 설정합니다.
_help_scraper;게임 관련 데이터를 다운로드할 사이트 정보를 설정합니다.
_help_screen_saver;화면 보호기를 설정합니다
_help_screen_saver_timeout;몇 초 동안 입력이 없을 시 화면 보호기를 작동시킬 지를 설정합니다. 0 이면 화면 보호기 기능을 정지합니다
_help_shortcut_artwork_name_edit;이 바로가기에 연결될 아트워크를 설정합니다. 바로가기를 표시할 때 이 이름으로 된 아트워크를 찾을 것입니다
_help_shortcut_delete;롬 목록에서 이 바로가기를 제거합니다
_help_shortcut_label_edit;이 바로가기의 이름을 설정합니다
_help_shortcut_target_edit;이 바로가기의 목적지를 설정합니다
_help_sound;효과음, 배경음악, 볼륨 조절 등을 설정합니다
_help_sound_sel;해당 상황에 재생할 소리를 지정합니다
_help_startup_mode;프로그램이 처음 실행될 때 무엇을 해야하는 지를 설정합니다
_help_track_usage;플레이 내역 (플레이 횟수, 시간) 을 기록할지 설정합니다.
_help_video_decoder;영상을 재생하는 데 사용할 디코더를 선택합니다
_help_volume;음량을 설정합니다. 0 에서 100 까지 이며, 0 이 음소거 입니다.
_help_window_mode;창 모드로 동작할지 전체 화면으로 동작할지를 설정합니다.
_sort_regexp;^(Vs\. The |The |Vs\. )

#
# Extra strings provided by translation
#
Add a rule to this filter;필터에 규칙 추가
Ambient Sounds;배경 음악 파일
Configure available emulators;기존 에뮬레이터 편집
Configure filter rule;필터 내용 수정
Delete this filter;필터 삭제
Exit menu;나가기
Launch Last Game on Startup;기동시 직전 게임 자동 재시작
Minimum Run Time;최소 실행 시간
Page Down;페이지 아래로
Page Up;페이지 위로
XML Mode;XML 모드
en;영어
fr;프랑스어
jp;일본어
kr;한국어
_help_autolaunch_last_game;프로그램 시작 시에, 마지막으로 실행하였던 게임을 바로 재시작할지 여부를 설정합니다
_help_control_page_down;아래 항목으로 한 페이지 이동하는 키를 설정합니다.
_help_control_page_up;위 항목으로 한 페이지 이동하는 키를 설정합니다.
_help_control_sel;
_help_emu_listxml;
_help_scrape_mamedb;MAME snap과 marquee를 mamedb.com에서 가져올 지 여부를 설정합니다

#@DONE_TRANSLATED
#
# Strings still needing translation
#
Attract-Mode detected emulator(s) that can be imported automatically.  Import them now?;Attract-Mode detected emulator(s) that can be imported automatically.  Import them now?
Clear Hotkey?;Clear Hotkey?
Exit Message;Exit Message
Layout File;Layout File
Non-Blocking Mode Wait;Non-Blocking Mode Wait
Pause Hotkey;Pause Hotkey
Please Wait;Please Wait
Press Hotkey;Press Hotkey
Select template to use for emulator settings;Select template to use for emulator settings
_help_emu_pause_hotkey;Set a global hotkey to pause the emulator.  When pressed, Attract-Mode will pause the emulator process and return to the frontend. The emulator process can be resumed by selecting the same game again in the frontend.
_help_exit_message;Alternate message to exit the frontend [i.e. "Shut Down System"]
_help_input_action;
_help_joystick_map;Map the frontend's joystick slots to specifically named joystick/gamepad devices attached to your computer (You can use this to force the frontend to always use 'Microsoft X-Box 360 pad' as Joystick 0, for example.)
_help_layout_file;Some layouts provide multiple layout*.nut files.  Select which layout file to use
