#@Português brasileiro
#
# Interface strings
#
$1 Rule(s); $1 Regra(s)
Action; Ação
Add '$1' to Favourites?; Adicionar '$1' aos Favoritos?
Add Artwork; Adicionar Arte
Add Emulator; Adicionar Emulador
Add Exception; Adicionar Exceção
Add Filter; Adicionar Filtro
Add Input; Adicionar Entrada
Add New Display; Adicionar Novo Display
Add Rule; Adicionar Regra
Add tag: '$1'; Adicionar tag: '$1'
Add/Remove Favourite; Adicionar/Remover Favorito
Add/Remove Tags; Adicionar/Remover Tags
Additional Import File(s); Arquivo(s) de Importação Adicional(is)
All; Todos
Allow Exit from 'Displays Menu'; Permitir Saída do 'Menu de Displays'
AltRomname; AltRomname
AltTitle; AltTitle
Ambient Soundtrack; Trilha Sonora Ambiente
Ambient Volume; Volume Ambiente
Artwork Label; Rótulo da Arte
Artwork Name; Nome da Arte
Artwork Path; Caminho da Arte
Attract-Mode detected emulator(s) that can be imported automatically. Import them now?; O Attract-Mode detectou emulador(es) que podem ser importados automaticamente. Importá-los agora?
Back; Voltar
Blank Game; Jogo em Branco
Buttons; Botões
Category; Categoria
Clear Hotkey?; Limpar Tecla de Atalho?
CloneOf; CloneDe
Collection/Rom List; Lista de Coleção/Rom
Command; Comando
Command Arguments; Argumentos do Comando
Comparison; Comparação
Configure; Configurar
Configure / Controls; Configurar / Controles
Configure / Displays; Configurar / Displays
Configure / Displays Menu; Configurar / Menu de Displays
Configure / Emulators; Configurar / Emuladores
Configure / Joystick Mapping; Configurar / Mapeamento de Joystick
Configure / Miscellaneous; Configurar / Diversos
Configure / Plug-ins; Configurar / Plug-ins
Configure / Scraper; Configurar / Scraper
Configure / Sound; Configurar / Som
Configure Intro; Configurar Introdução
Configure Layout; Configurar Layout
Configure Plug-in; Configurar Plug-in
Configure Screen Saver; Configurar Protetor de Tela
Confirm Exit; Confirmar Saída
Confirm Favourites; Confirmar Favoritos
Control; Controle
Controls; Controles
Create new tag; Criar nova tag
Custom Arguments; Argumentos Personalizados
Custom Executable; Executável Personalizado
Custom1; Personalizado1
Custom2; Personalizado2
Custom3; Personalizado3
Custom4; Personalizado4
Custom5; Personalizado5
Custom6; Personalizado6
Default; Padrão
Default Action; Ação Padrão
Default Font; Fonte Padrão
Delete display '$1'?; Deletar display '$1'?
Delete emulator '$1'?; Deletar emulador '$1'?
Delete filter '$1'?; Deletar filtro '$1'?
Delete game '$1'?; Deletar jogo '$1'?
Delete shortcut '$1'?; Deletar atalho '$1'?
Delete this Display; Deletar este Display
Delete this Emulator; Deletar este Emulador
Delete this Filter; Deletar este Filtro
Delete this Game; Deletar este Jogo
Delete this Rule; Deletar esta Regra
Delete this Shortcut; Deletar este Atalho
Disabled; Desativado
Display Edit; Editar Display
Display Name; Nome do Display
DisplayCount; Contagem de Displays
DisplayType; Tipo de Display
Displays; Displays
Displays Menu; Menu de Displays
Down; Para baixo
Edit Artwork; Editar Arte
Edit Emulator; Editar Emulador
Edit Game; Editar Jogo
Edit Input; Editar Entrada
Edit Shortcut; Editar Atalho
Empty; Vazio
Emulator; Emulador
Emulator Name; Nome do Emulador
Emulators; Emuladores
Enable Multiple Monitors; Ativar Múltiplos Monitores
Enabled; Ativado
Enter Display Name; Inserir Nome do Display
Enter Emulator Name; Inserir Nome do Emulador
Enter Filter Name; Inserir Nome do Filtro
Enter Romlist Name; Inserir Nome da Lista de Roms
Enter new tag name; Inserir novo nome de tag
Exception; Exceção
Exception Edit; Editar Exceção
Executable; Executável
Exit; Sair
Exit Attract-Mode; Sair do Attract-Mode
Exit Attract-Mode?; Sair do Attract-Mode?
Exit Command; Comando de Saída
Exit Hotkey; Tecla de Atalho de Saída
Exit Message; Mensagem de Saída
Exit to Desktop; Sair para a Área de Trabalho
Extra; Extra
Favourite; Favorito
FileIsAvailable; ArquivoDisponível
Fill Screen (Default); Preencher Tela (Padrão)
Filter; Filtro
Filter Edit; Editar Filtro
Filter Name; Nome do Filtro
Filter Value; Valor do Filtro
Filter Wrap Mode; Modo de Envoltório do Filtro
Filters Menu; Menu de Filtros
Flip; Virar
Font Path; Caminho da Fonte
Fullscreen Mode; Modo Tela Cheia
Game Return Sound; Som de Retorno do Jogo
General; Geral
Generate Collection/Rom List; Gerar Lista de Coleção/Rom
Generating Rom List: $1%; Gerando Lista de Roms: $1%
Global Filter; Filtro Global
Group Clones; Agrupar Clones
Hide Brackets in Game Title; Ocultar Colchetes no Título do Jogo
Image Cache Size; Tamanho do Cache de Imagens
Info Source/Scraper; Fonte de Informação/Scraper
Insert Command Shortcut; Inserir Atalho de Comando
Insert Display Shortcut; Inserir Atalho de Display
Insert Game Entry; Inserir Entrada de Jogo
Insert Menu Entry; Inserir Entrada de Menu
Intro; Introdução
Joystick Mappings; Mapeamentos de Joystick
Joystick Threshold; Limite do Joystick
Joystick $1; Joystick $1
Jump to Next Display; Ir para o Próximo Display
Language; Idioma
Launch Last Game; Iniciar Último Jogo
Layout; Layout
Layout File; Arquivo de Layout
Layout Options; Opções de Layout
Left; Esquerda
List Limit; Limite da Lista
Manufacturer; Fabricante
Menu Prompt; Solicitação do Menu
Menu Style / Layout; Estilo / Layout do Menu
Mouse Threshold; Limite do Mouse
Movie Volume; Volume do Filme
Name; Nome
Next Display; Próximo Display
Next Favourite; Próximo Favorito
Next Filter; Próximo Filtro
Next Game; Próximo Jogo
Next Letter; Próxima Letra
Next Page; Próxima Página
No; Não
No Sort; Sem Ordenação
No Wrap; Sem Quebra
None; Nenhum
Non-Blocking Mode Wait; Espera em Modo Não Bloqueante
OR; OU
Overview; Visão Geral
Overwrite existing '$1' list?; Substituir a lista '$1' existente?
Pause Hotkey; Tecla de Atalho de Pausa
Play Sound; Reproduzir Som
PlayedCount; Contagem de Jogos Reproduzidos
PlayedTime; Tempo de Jogo
Players; Jogadores
Please Wait; Por Favor, Aguarde
Plug-ins; Plug-ins
Power Saving; Economia de Energia
Press Input; Pressione Entrada
Press Hotkey; Pressione Tecla de Atalho
Previous Display; Display Anterior
Previous Favourite; Favorito Anterior
Previous Filter; Filtro Anterior
Previous Game; Jogo Anterior
Previous Letter; Letra Anterior
Previous Page; Página Anterior
Random Game; Jogo Aleatório
Remove '$1' from Favourites?; Remover '$1' dos Favoritos?
Remove Input; Remover Entrada
Remove tag: '$1'; Remover tag: '$1'
Replay Last Game; Reproduzir Último Jogo
Right; Direita
Rom Extension(s); Extensão(ões) de Rom
Rom Path(s); Caminho(s) da Rom
Rom path '$1' not found, proceed anyways?; Caminho da Rom '$1' não encontrado, prosseguir assim mesmo?
Rotation; Rotação
Rule; Regra
Rule Edit; Editar Regra
Scrape Artwork; Raspar Arte
Scrape Fanart; Raspar Fanart
Scrape Flyers/Boxart; Raspar Flyers/Boxart
Scrape Game Logos (Wheel Art); Raspar Logos de Jogos (Arte de Roda)
Scrape Marquees; Raspar Marquees
Scrape Snaps; Raspar Snaps
Scrape Videos (MAME only); Raspar Vídeos (somente MAME)
Scraper; Scraper
Scraping Artwork: $1%; Raspar Arte: $1%
Screen Saver; Protetor de Tela
Screen Saver Timeout; Tempo Limite do Protetor de Tela
Screenshot; Captura de Tela
Select; Selecionar
Select template to use for emulator settings; Selecionar modelo para usar nas configurações do emulador
Show in Cycle; Mostrar em Ciclo
Show in Menu; Mostrar no Menu
Show Displays Menu; Mostrar Menu de Displays
Show Last Selection (Default); Mostrar Última Seleção (Padrão)
Sort By; Ordenar Por
Sound; Som
Sound Volume; Volume do Som
Startup Mode; Modo de Inicialização
Startup Sound; Som de Inicialização
Status; Status
System Identifier; Identificador do Sistema
Tags; Tags
Target; Alvo
The name for this filter; O nome para este filtro
This will overwrite an existing mapping ($1). Proceed?; Isso substituirá um mapeamento existente ($1). Prosseguir?
Title; Título
Toggle Flip; Alternar Virar
Toggle Layout; Alternar Layout
Toggle Movie; Alternar Filme
Toggle Mute; Alternar Mudo
Toggle Rotate Left; Alternar Rotação para a Esquerda
Toggle Rotate Right; Alternar Rotação para a Direita
Track Usage; Rastrear Uso
Up; Para cima
Video Decoder; Decodificador de Vídeo
Window; Janela
Window Mode; Modo de Janela
Window (No Border); Janela (Sem Borda)
Working Directory; Diretório de Trabalho
Wrap within Display (Default); Enrolar dentro do Display (Padrão)
Wrote $1 entries to Collection/Rom List; Escreveu $1 entradas na Lista de Coleção/Rom
Year; Ano
Yes; Sim
contains; contém
does not contain; não contém
does not equal; não é igual
equals; é igual
multi; múltiplo

#
# Help message strings
#
_help_art; Um recurso de arte disponível para uso por layouts
_help_art_add; Adicionar um novo recurso de arte (imagens de marquee, capturas de tela, etc.)
_help_art_label; O rótulo que identifica este recurso de arte (usado por layouts)
_help_art_path; O caminho para os arquivos desta arte. Múltiplos caminhos podem ser inseridos se separados por ponto e vírgula.
_help_back; Sair do menu
_help_confirm_exit; Confirmar antes de sair do Attact-Mode?
_help_confirm_favs; Confirmar a adição/remoção de Favoritos?
_help_control_add_favourite; Definir o(s) controle(s) que marcam/desmarcam o jogo selecionado atualmente como favorito
_help_control_add_tags; Definir o(s) controle(s) que adicionam/removem tags do jogo selecionado atualmente
_help_control_back; Definir o(s) controle(s) que retornam
_help_control_configure; Definir o(s) controle(s) que mostram o "Menu de Configuração"
_help_control_custom1; Definir o(s) controle(s) "Custom1"
_help_control_custom2; Definir o(s) controle(s) "Custom2"
_help_control_custom3; Definir o(s) controle(s) "Custom3"
_help_control_custom4; Definir o(s) controle(s) "Custom4"
_help_control_custom5; Definir o(s) controle(s) "Custom5"
_help_control_custom6; Definir o(s) controle(s) "Custom6"
_help_control_displays_menu; Definir o(s) controle(s) que mostram o "Menu de Displays"
_help_control_down; Definir o(s) controle(s) que movem a seleção para baixo
_help_control_edit_game; Definir o(s) controle(s) para editar a seleção atual
_help_control_exit; Definir o(s) controle(s) que saem do frontend
_help_control_exit_to_desktop; Definir o(s) controle(s) que saem do frontend imediatamente para a área de trabalho
_help_control_filters_menu; Definir o(s) controle(s) que mostram o "Menu de Filtros"
_help_control_intro; Definir o(s) controle(s) que mostram o vídeo de introdução
_help_control_left; Definir o(s) controle(s) que movem a seleção para a esquerda
_help_control_next_display; Definir o(s) controle(s) que movem para o próximo display
_help_control_next_favourite; Definir o(s) controle(s) que movem para o próximo favorito
_help_control_next_filter; Definir o(s) controle(s) que movem para o próximo filtro
_help_control_next_game; Definir o(s) controle(s) que movem para o próximo jogo
_help_control_next_letter; Definir o(s) controle(s) que movem para a próxima letra
_help_control_next_page; Definir o(s) controle(s) que movem a seleção para cima em uma página
_help_control_prev_display; Definir o(s) controle(s) que movem para o display anterior
_help_control_prev_favourite; Definir o(s) controle(s) que movem para o favorito anterior
_help_control_prev_filter; Definir o(s) controle(s) que movem para o filtro anterior
_help_control_prev_game; Definir o(s) controle(s) que movem para o jogo anterior
_help_control_prev_letter; Definir o(s) controle(s) que movem para a letra anterior
_help_control_prev_page; Definir o(s) controle(s) que movem a seleção para baixo em uma página
_help_control_random_game; Definir o(s) controle(s) que selecionam um jogo aleatório da lista atual
_help_control_replay_last_game; Definir o(s) controle(s) que relançam o último jogo jogado
_help_control_right; Definir o(s) controle(s) que movem a seleção para a direita
_help_control_screen_saver; Definir o(s) controle(s) que ativam o modo de protetor de tela
_help_control_screenshot; Definir o(s) controle(s) que capturam uma captura de tela do frontend
_help_control_select; Definir o(s) controle(s) que lançam a seleção atual
_help_control_toggle_flip; Definir o(s) controle(s) que alternam se o display deve ser rotacionado 180 graus
_help_control_toggle_layout; Definir o(s) controle(s) que alternam o script de layout a ser usado (depende do layout que você está usando se isso faz alguma coisa)
_help_control_toggle_movie; Definir o(s) controle(s) que alternam se os vídeos devem ser reproduzidos
_help_control_toggle_mute; Definir o(s) controle(s) que silenciam/ativam o som do frontend
_help_control_toggle_rotate_left; Definir o(s) controle(s) que alternam se o display deve ser rotacionado 90 graus para a esquerda
_help_control_toggle_rotate_right; Definir o(s) controle(s) que alternam se o display deve ser rotacionado 90 graus para a direita
_help_control_up; Definir o(s) controle(s) que movem a seleção para cima
_help_controls; Configurar os inputs de joystick, teclado e mouse que controlam o Attract-Mode
_help_default_font; O nome da fonte padrão a ser usada
_help_display_add; Adicionar um novo display
_help_display_add_filter; Adicionar um filtro ao conjunto de filtros deste display
_help_display_delete; Excluir este display
_help_display_filter; Configurar este filtro no conjunto de filtros do display
_help_display_global_filter; Configurar regras de filtro globais aplicadas a cada entrada na coleção/lista de roms deste display
_help_display_in_cycle; Incluir este display no ciclo "Display Anterior"/"Próximo Display"?
_help_display_in_menu; Incluir este display no "Menu de Displays"?
_help_display_layout; O layout a ser usado para este display
_help_display_layout_options; Configurar opções específicas do layout
_help_display_name; O título para este display
_help_display_romlist; A coleção/lista de roms a ser usada para este display
_help_display_sel; Configurar display
_help_displays; Configurar os agrupamentos de romlist/layout (também conhecidos como "Displays") disponíveis para serem ciclicamente exibidos no Attract-Mode
_help_displays_menu; Configurar opções para o "Menu de Displays"
_help_displays_menu_exit; Configurar se uma opção de Sair deve ser fornecida no "Menu de Displays"
_help_displays_menu_layout; O layout a ser usado para o 'Menu de Displays'. Defina como 'Padrão' para usar o menu integrado do frontend
_help_displays_menu_prompt; O prompt do 'Menu de Displays' (por exemplo, "Selecione o Sistema")
_help_emu_add; Adicionar um novo emulador
_help_emu_args; Os argumentos da linha de comando para este emulador. Os seguintes serão substituídos adequadamente: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn], [workdir], [nothing], além de quaisquer 'tokens mágicos' válidos (veja a documentação do layout)
_help_emu_delete; Excluir a entrada para este emulador
_help_emu_executable; O caminho completo e nome do executável do emulador. Variáveis possíveis: $HOME = Diretório home do usuário, $PROGDIR = Diretório do programa Attract-Mode. O Windows também tem %SYSTEMROOT% e %PROGRAMFILES% correspondendo às variáveis de ambiente do sistema.
_help_emu_exit_hotkey; Definir uma tecla de atalho global para sair do emulador. O Attract-Mode terminará o processo do emulador se esta tecla de atalho for pressionada
_help_emu_gen_romlist; Gerar uma romlist procurando o caminho de roms configurado para roms com a extensão configurada, incorporando informações XML e de arquivos adicionais importados na lista gerada (se disponível)
_help_emu_import_extras; Caminho para quaisquer arquivos adicionais que precisam ser lidos ao gerar uma romlist para este emulador. Arquivos suportados são: catver.ini (categorias), nplayers.ini (número de jogadores), series.ini (séries), language.ini (idioma) e mame.xml. Múltiplos caminhos de arquivos podem ser inseridos se separados por ponto e vírgula
_help_emu_info_source; Use "listxml" para saída mame -listxml, "listsoftware" para saída mame/mess -listsoftware, "thegamesdb.net" para extrair dados do thegamesdb.net, "steam" para ler de uma instalação steam, ou "scummvm" se o emulador for scummvm. "listsoftware" e "thegamesdb.net" também exigem que um Identificador de Sistema reconhecido por essas fontes esteja configurado
_help_emu_nb_mode_wait; Se for diferente de zero, o emulador será executado em 'modo não bloqueante'. O frontend aguardará até esse número de segundos para perder o foco para a janela do emulador e voltará quando o foco retornar à janela do frontend. Isso é necessário para lançar programas como Steam corretamente. Deve ser 0, a menos que você saiba que precisa disso
_help_emu_pause_hotkey; Definir uma tecla de atalho global para pausar o emulador. Quando pressionada, o Attract-Mode pausará o processo do emulador e retornará ao frontend. O processo do emulador pode ser retomado selecionando o mesmo jogo novamente no frontend.
_help_emu_romext; A(s) extensão(ões) de rom para este emulador (por exemplo, .zip). Múltiplas extensões podem ser inseridas se separadas por ponto e vírgula. Especifique "<DIR>" como uma entrada se os jogos estiverem armazenados em subdiretórios separados
_help_emu_rompath; O caminho para as roms para este emulador. Múltiplos caminhos podem ser inseridos se separados por ponto e vírgula.
_help_emu_scrape_artwork; Buscar imagens de arte ausentes para este emulador na internet
_help_emu_sel; Configurar emulador
_help_emu_sel_gen_romlist; Gerar uma Coleção/Romlist contendo jogos para múltiplos emuladores
_help_emu_system; Os identificadores de sistema para este emulador. Múltiplos valores podem ser inseridos se separados por ponto e vírgula
_help_emu_workdir; O diretório de trabalho para este emulador. Este é o diretório a partir do qual o frontend executa o emulador. Além disso, quaisquer caminhos relativos de roms, caminhos de arte ou caminhos de arquivos adicionais importados são tratados como relativos a este diretório
_help_emulators; Configurar configurações do emulador
_help_exit_command; Comando a ser executado ao sair do frontend [por exemplo, "sudo shutdown"]
_help_exit_message; Mensagem alternativa para sair do frontend [por exemplo, "Desligar Sistema"]
_help_filter_add_exception; Adicionar uma exceção a este filtro. Se um jogo corresponder a uma exceção (e não tiver sido filtrado por uma regra anterior), será listado no filtro
_help_filter_add_rule; Adicionar uma regra a este filtro. Um jogo deve corresponder a todas as regras de filtro (ou a uma única exceção) para ser listado em um filtro
_help_filter_delete; Excluir este filtro
_help_filter_exception; Configurar esta exceção de filtro. Se um jogo corresponder a uma exceção, será listado no filtro. Regras e exceções são aplicadas na ordem em que são listadas
_help_filter_list_limit; Defina isso para um valor diferente de zero se desejar limitar o tamanho de uma lista ordenada. Use um valor positivo para os primeiros X itens (por exemplo, "10" dá os primeiros 10 itens), um valor negativo para os últimos X itens (por exemplo, "-25" dá os últimos 25 itens), ou "0" para sem limite
_help_filter_name; O nome para este filtro
_help_filter_rule; Configurar esta regra de filtro. Um jogo deve corresponder a todas as regras de filtro (ou a uma única exceção) para ser listado em um filtro
_help_filter_sort_by; O atributo de informação do jogo pelo qual você deseja ordenar a coleção/lista de roms. Defina como "Sem Ordenação" para manter a ordenação da lista de coleção/roms original
_help_filter_wrap_mode; Definir o que acontece quando as ações "Próximo Filtro" ou "Filtro Anterior" alcançam o final do conjunto de filtros
_help_font_path; Os diretórios contendo fontes. Múltiplos diretórios podem ser inseridos se separados por ponto e vírgula. O Attract-Mode pesquisará recursivamente nesses diretórios para encontrar uma fonte especificada
_help_game_custom_args; Defina isso para substituir os argumentos padrão da linha de comando para este jogo. Defina isso para [nothing] se desejar substituir com nenhum parâmetro. Os seguintes serão substituídos adequadamente: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_game_custom_executable; Defina isso para substituir o executável padrão para este jogo
_help_game_delete; Excluir este jogo da Romlist
_help_game_edit; Editar as informações deste jogo
_help_game_overview; Editar visão geral do jogo
_help_generator_opt; Definir se este emulador deve ser incluído na romlist gerada
_help_generator_build; Gerar romlist com o(s) emulador(es) selecionado(s)
_help_group_clones; Agrupar todos os clones de um jogo sob uma única entrada de lista
_help_hide_brackets; Ocultar texto entre colchetes ao mostrar títulos de jogos
_help_image_cache_mbytes; Configurar o tamanho máximo do cache interno de imagens do Attract-Mode (em megabytes)
_help_input_action;
_help_input_add; Adicionar um novo mapeamento de entrada para este controle
_help_input_default_action; Definir o comportamento padrão para este controle
_help_input_delete; Remover este mapeamento de entrada
_help_intro; Configurar introdução
_help_joystick_map; Mapear os slots de joystick do frontend para dispositivos de joystick/gamepad especificamente nomeados conectados ao seu computador (Você pode usar isso para forçar o frontend a sempre usar 'Microsoft X-Box 360 pad' como Joystick 0, por exemplo.)
_help_joystick_threshold; O limite para registrar movimentos do joystick, de 1 a 100 (100=menos sensível)
_help_language; Selecionar o idioma a ser usado na interface do usuário do Attract-Mode
_help_layout_file; Alguns layouts fornecem vários arquivos layout*.nut. Selecione qual arquivo de layout usar
_help_misc; Configurar configurações diversas
_help_mouse_threshold; O limite para registrar movimentos do mouse, de 1 a 100 (100=menos sensível)
_help_multiple_monitors; Ativar o uso de múltiplos monitores pelo Attract-Mode. Definir isso para 'Não' pode reduzir o cintilamento da tela ao iniciar jogos
_help_plugin_command; O executável associado a este plug-in
_help_plugin_enabled; Definir se este plug-in está habilitado
_help_plugin_sel; Configurar plug-in
_help_plugins; Configurar plug-ins disponíveis
_help_rule_comp; Tipo de comparação para o filtro
_help_rule_delete; Excluir esta regra de filtro
_help_rule_target; O atributo de informação do jogo com base no qual você deseja filtrar
_help_rule_value; O valor da expressão regular para filtrar. Por exemplo, se o alvo do filtro for "Ano" e a comparação for "igual", um valor de "1984" corresponderá ao ano de 1984, "198." corresponderá a qualquer ano na década de 80, e "(198.)|(199.)" corresponderá a qualquer ano na década de 80 ou 90
_help_scrape_fanart; Definir se a arte de fã dos jogos deve ser baixada ao buscar
_help_scrape_flyers; Definir se flyers e capas de caixas dos jogos devem ser baixados ao buscar
_help_scrape_marquees; Definir se marquee e banners dos jogos devem ser baixados ao buscar
_help_scrape_snaps; Definir se capturas de tela dos jogos devem ser baixadas ao buscar
_help_scrape_vids; Definir se vídeos dos jogos devem ser baixados ao buscar
_help_scrape_wheels; Definir se logos dos jogos devem ser baixados ao buscar
_help_scraper; Configurar as definições do scraper de arte
_help_screen_saver; Configurar protetor de tela
_help_screen_saver_timeout; A quantidade de tempo em segundos a esperar antes de mudar para o protetor de tela. 0 para desativar
_help_shortcut_label_edit; Editar o rótulo deste atalho
_help_shortcut_target_edit; Editar o alvo deste atalho
_help_shortcut_artwork_name_edit; Opcionalmente fornecer um nome de arte para ser associado a este atalho. O frontend tentará carregar artes com este nome ao exibir o atalho
_help_shortcut_delete; Excluir este atalho da Romlist
_help_sound; Configurar volumes de som, mapeamentos de eventos sonoros e a trilha sonora ambiente
_help_sound_sel; Atribuir um som a este evento/ação
_help_startup_mode; Definir o que deve acontecer quando o Attract-Mode inicia
_help_track_usage; Configurar se o Attract-Mode deve rastrear o uso (tempo jogado e contagem de jogos para cada jogo)
_help_video_decoder; Configurar o decodificador a ser usado para reprodução de vídeo (se múltiplos decodificadores estiverem disponíveis)
_help_volume; As configurações de volume válidas vão de 0 (mudo) a 100
_help_window_mode; Definir se o Attract-Mode deve preencher a tela ou rodar em uma janela
_help_hide_console; Ocultar o console na inicialização. Observe que isso só funciona se iniciar o Attract-Mode a partir de uma GUI do Windows. Se iniciado a partir de uma janela de console existente (por exemplo, um arquivo de lote), o processo sempre "anexará" ao console existente e enviará a saída para ele.
_help_power_saving; Ajuda a economizar energia apenas redesenhando a tela quando necessário. Pode causar engasgos na animação em alguns layouts ou congelamento no Linux.
_sort_regexp; ^(Vs. The |The |Vs. )


