#@繁體中文 (Traditional Chinese);win_font=SourceHanSansTC-Regular,MSJH;mac_font=AppleLiGothic;linux_font=SourceHanSansTC-Regular
#
# Interface strings
#
$1 Rule(s);$1 規則
Action;操作
Add '$1' to Favourites?;要將「$1」加入我的最愛嗎？
Add Artwork;新增插圖資源
Add Emulator;新增模擬器
Add Exception;新增例外條件
Add Filter;新增遊戲過濾
Add Input;新增輸入按鍵
Add New Display;新增顯示介面
Add Rule;新增規則
Add tag: '$1';新增分類標籤: $1
Add/Remove Favourite;加入/移除我的最愛
Add/Remove Tags;加入/移除分類標籤
Additional Import File(s);附加匯入檔案
All;全部
Allow Exit from 'Displays Menu';允許在主選單顯示結束項目
AltRomname;替代檔案名稱
AltTitle;替代標題名稱
Ambient Soundtrack;環境音效
Ambient Volume;環境音量
Artwork Label;插圖類型
Artwork Name;插圖名稱
Artwork Path;插圖路徑
Attract-Mode detected emulator(s) that can be imported automatically.  Import them now?;Attract-Mode 已偵測到能夠自動匯入的模擬器，要立即匯入嗎？
Back;返回
Blank Game;空遊戲
Buttons;按鍵
Category;類型
Clear Hotkey?;要清除熱鍵嗎？
CloneOf;衍生
Collection/Rom List;收藏集/遊戲清單
Command;命令
Command Arguments;命令參數
Comparison;比對方式
Configure;設定
Configure / Controls;設定 / 輸入控制
Configure / Displays;設定 / 顯示介面
Configure / Displays Menu;設定 / 主選單
Configure / Emulators;設定 / 模擬器
Configure / Joystick Mapping;設定 / 搖桿映射
Configure / Miscellaneous;設定 / 一般
Configure / Plug-ins;設定 / 外掛
Configure / Scraper;設定 / 搜刮器
Configure / Sound;設定 / 聲音
Configure Intro;設定啟動視訊
Configure Layout;設定畫面佈局
Configure Plug-in;設定外掛
Configure Screen Saver;設定螢幕保護
Confirm Exit;結束時確認
Confirm Favourites;操作我的最愛時確認
Control;輸入控制
Controls;輸入控制
Create new tag;建主新分類標籤
Custom Arguments;自訂參數
Custom Executable;自訂執行檔
Custom1;自訂 1
Custom2;自訂 2
Custom3;自訂 3
Custom4;自訂 4
Custom5;自訂 5
Custom6;自訂 6
Default;預設
Default Action;預設操作
Default Font;預設字型
Delete display '$1'?;要刪除「$1」顯示介面嗎？
Delete emulator '$1'?;要刪除「$1」模擬器嗎？
Delete filter '$1'?;要刪除「$1」遊戲過濾嗎？
Delete game '$1'?;要刪除「$1」遊戲嗎？
Delete shortcut '$1'?;要刪除「$1」捷徑嗎？
Delete this Display;刪除這個顯示介面
Delete this Emulator;刪除這個模擬器
Delete this Filter;刪除這個遊戲過濾
Delete this Game;刪除這個遊戲
Delete this Rule;刪除這個規則
Delete this Shortcut;刪除這個捷徑
Disabled;停用
Display Edit;顯示介面設定
Display Name;顯示介面名稱
DisplayCount;顯示器數量
DisplayType;顯示類型
Displays;顯示介面
Displays Menu;主選單
Down;下移
Edit Artwork;編輯插圖
Edit Emulator;編輯模擬器
Edit Game;編輯遊戲
Edit Input;編輯輸入按鍵
Edit Shortcut;編輯捷徑
Empty;空
Emulator;模擬器
Emulator Name;模擬器名稱
Emulators;模擬器
Enable Multiple Monitors;啟用多螢幕支援
Enabled;啟用
Enter Display Name;輸入顯示介面名稱
Enter Emulator Name;輸入模擬器名稱
Enter Filter Name;輸入遊戲過濾名稱
Enter Romlist Name;輸入遊戲清單名稱
Enter new tag name;輸入分類標籤名稱
Exception;例外條件
Exception Edit;編輯例外條件
Executable;執行檔
Exit;結束
Exit Attract-Mode;結束 Attract-Mode
Exit Attract-Mode?;要結束 Attract-Mode 嗎？
Exit Command;結束時指令
Exit Hotkey;結束熱鍵
Exit Message;結束時訊息
Exit to Desktop;結束至桌面
Extra;其它
Favourite;我的最愛
FileIsAvailable;檔案可用性
Fill Screen (Default);填滿螢幕 (預設)
Filter;遊戲過濾
Filter Edit;編輯遊戲過濾
Filter Name;過濾名稱
Filter Value;過濾值
Filter Wrap Mode;遊戲過濾循環模式
Filters Menu;遊戲過濾選單
Flip;翻轉
Font Path;字型路徑
Fullscreen Mode;全螢幕模式
Game Return Sound;遊戲返回音效
General;一般
Generate Collection/Rom List;產生收藏集/遊戲清單
Generating Rom List: $1%;正在產生收藏集/遊戲清單: $1%
Global Filter;全域過濾
Hide Brackets in Game Title;隱藏遊戲標題裡的括號內容
Image Cache Size;影像快取大小
Info Source/Scraper;資訊來源/搜刮器
Insert Command Shortcut;插入命令捷徑
Insert Display Shortcut;插入顯示介面捷徑
Insert Game Entry;插入遊戲項目
Insert Menu Entry;插入選單項目
Intro;啟動視訊
Joystick Mappings;搖桿映射
Joystick Threshold;搖桿靈敏度
Joystick $1;搖桿 $1
Jump to Next Display;跳到下一個顯示介面
Language;語言
Launch Last Game;最後執行的遊戲
Layout;畫面佈局
Layout File;畫面佈局檔案
Layout Options;畫面佈局選項
Left;左移
List Limit;清單大小限制
Manufacturer;製作廠商
Menu Prompt;選單提示
Menu Style / Layout;選單樣式 / 畫面佈局
Mouse Threshold;滑鼠靈敏度
Movie Volume;影片音量
Name;檔案名稱
Next Display;下一個顯示介面
Next Favourite;下一個我的最愛
Next Filter;下一個遊戲過濾
Next Game;下一個遊戲
Next Letter;下一個文字清單
Next Page;下一頁
No;否
No Sort;不排序
No Wrap;不循環
None;皆否
Non-Blocking Mode Wait;非阻塞等待模式
OR;或
Overview;簡介
Overwrite existing '$1' list?;要覆寫現有的「$1」清單嗎？
Pause Hotkey;暫停熱鍵
Play Sound;播放聲音
PlayedCount;遊戲次數
PlayedTime;遊戲時間
Players;遊戲人數
Please Wait;請稍待
Plug-ins;外掛
Power Saving;省電模式
Press Input;請按下要使用的輸入按鍵
Press Hotkey;請按下要使用的熱鍵
Previous Display;上一個顯示介面
Previous Favourite;上一個我的最愛
Previous Filter;上一個遊戲過濾
Previous Game;上一個遊戲
Previous Letter;上一個文字清單
Previous Page;上一頁
Random Game;隨機選取遊戲
Remove '$1' from Favourites?;要從我的最愛移除「$1」嗎？
Remove Input;移除輸入按鍵
Remove tag: '$1';移除分類標籤: $1
Replay Last Game;重玩最後執行的遊戲
Right;右移
Rom Extension(s);遊戲副檔名
Rom Path(s);遊戲檔路徑
Rom path '$1' not found, proceed anyways?;遊戲檔路徑「$1」未找到，要繼續處理嗎？
Rotation;旋轉
Rule;規則
Rule Edit;編輯規則
Scrape Artwork;搜刮插圖
Scrape Fanart;搜刮玩家自製插圖
Scrape Flyers/Boxart;搜刮宣傳/盒裝插圖
Scrape Game Logos (Wheel Art);搜刮遊戲圖標 (輪播插圖)
Scrape Marquees;搜刮遊戲招牌插圖
Scrape Snaps;搜刮遊戲捉圖
Scrape Videos (MAME only);搜刮視訊 (僅 MAME)
Scraper;搜刮器
Scraping Artwork: $1%;正在搜刮插圖: $1%
Screen Saver;螢幕保護
Screen Saver Timeout;螢幕保護啟動時間
Screenshot;螢幕截圖
Select;選擇
Select template to use for emulator settings;選擇模擬器設定模板
Show in Cycle;顯示在顯示介面循環裡
Show in Menu;顯示在主選單
Show Displays Menu;顯示主選單
Show Last Selection (Default);顯示最後選擇的項目 (預設)
Sort By;排序方式
Sound;聲音
Sound Volume;聲音音量
Startup Mode;啟動模式
Startup Sound;啟動音效
Status;狀態
System Identifier;系統識別
Tags;分類標籤
Target;目標
The name for this filter;這個遊戲過濾的名稱
This will overwrite an existing mapping ($1).  Proceed?;這將會覆寫現有的映射 ($1)，要繼續處理嗎？
Title;標題
Toggle Flip;切換翻轉
Toggle Layout;切換畫面佈局
Toggle Movie;切換影片
Toggle Mute;切換靜音
Toggle Rotate Left;切換向左旋轉
Toggle Rotate Right;切換向右旋轉
Track Usage;記錄遊戲時間/次數
Up;上移
Video Decoder;視訊解碼器
Window;視窗模式
Window Mode;顯示模式
Window (No Border);視窗模式 (無邊框)
Working Directory;工作目錄
Wrap within Display (Default);循環至第一個遊戲過濾 (預設)
Wrote $1 entries to Collection/Rom List;寫入 $1 項目至收藏集/遊戲清單
Year;年份
Yes;是
contains;包含
does not contain;不包含
does not equal;不等於
equals;等於
multi;多個

#
# Help message strings
#
_help_art;一種提供給畫面佈局使用的插圖資源
_help_art_add;新增插圖資源 (遊戲招牌插圖、遊戲捉圖、其它...)
_help_art_label;設定用來識別插圖資源類型的識別名稱 (使用在畫面佈局)
_help_art_path;設定插圖資源檔案所存放的路徑 (多重路徑可用分號間隔)
_help_back;離開選單
_help_confirm_exit;結束 Attact-Mode 前先確認？
_help_confirm_favs;加入/移除我的最愛前先確認？
_help_control_add_favourite;設定「加入/移除當前遊戲至我的最愛」的控制鍵
_help_control_add_tags;設定「加入/移除當前遊戲至分類標籤」的控制鍵
_help_control_back;設定「返回」的控制鍵
_help_control_configure;設定「顯示設定選單」的控制鍵
_help_control_custom1;設定「自訂 1」的控制鍵
_help_control_custom2;設定「自訂 2」的控制鍵
_help_control_custom3;設定「自訂 3」的控制鍵
_help_control_custom4;設定「自訂 4」的控制鍵
_help_control_custom5;設定「自訂 5」的控制鍵
_help_control_custom6;設定「自訂 6」的控制鍵
_help_control_displays_menu;設定「顯示主選單」的控制鍵
_help_control_down;設定「下移選項」的控制鍵
_help_control_edit_game;設定「編輯當前選項」的控制鍵
_help_control_exit;設定「結束 Attract-Mode」的控制鍵
_help_control_exit_to_desktop;設定「結束並立即返回桌面」的控制鍵
_help_control_filters_menu;設定「顯示遊戲過濾選單」的控制鍵
_help_control_intro;設定「顯示啟動視訊」的控制鍵
_help_control_left;設定「左移選項」的控制鍵
_help_control_next_display;設定「移至下一個顯示介面」的控制鍵
_help_control_next_favourite;設定「移至下一個我的最愛」的控制鍵
_help_control_next_filter;設定「移至下一個遊戲過濾」的控制鍵
_help_control_next_game;設定「移至下一個遊戲」的控制鍵
_help_control_next_letter;設定「移至下一個文字清單」的控制鍵
_help_control_next_page;設定「移至下一頁」的控制鍵
_help_control_prev_display;設定「移至上一個顯示介面」的控制鍵
_help_control_prev_favourite;設定「移至上一個我的最愛」的控制鍵
_help_control_prev_filter;設定「移至上一個遊戲過濾」的控制鍵
_help_control_prev_game;設定「移至上一個遊戲」的控制鍵
_help_control_prev_letter;設定「移至上一個文字清單」的控制鍵
_help_control_prev_page;設定「移至上一頁」的控制鍵
_help_control_random_game;設定「從當前清單隨機選取遊戲」的控制鍵
_help_control_replay_last_game;設定「重玩最後執行的遊戲」的控制鍵
_help_control_right;設定「右移選項」的控制鍵
_help_control_screen_saver;設定「進入螢幕保護模式」的控制鍵
_help_control_screenshot;設定「螢幕截圖」的控制鍵
_help_control_select;設定「執行當前選項」的控制鍵
_help_control_toggle_flip;設定「將顯示畫面旋轉 180 度」的控制鍵
_help_control_toggle_layout;設定「切換畫面佈局」的控制鍵 (主題資料夾中含有多個畫面佈局檔案時才會進行切換)
_help_control_toggle_movie;設定「切換影片播放」的控制鍵
_help_control_toggle_mute;設定「切換聲音靜音」的控制鍵
_help_control_toggle_rotate_left;設定「將顯示畫面向左旋轉 90 度」的控制鍵
_help_control_toggle_rotate_right;設定「將顯示畫面向右旋轉 90 度」的控制鍵
_help_control_up;設定「上移選項」的控制鍵
_help_controls;設定搖桿、鍵盤及滑鼠按鍵用來操作 Attract-Mode 功能
_help_default_font;預設使用的字型名稱
_help_display_add;新增一個新的顯示介面
_help_display_add_filter;新增一個遊戲過濾至這個顯示介面的遊戲過濾集
_help_display_delete;刪除這個顯示介面
_help_display_filter;在這個顯示介面的遊戲過濾集中設定這個遊戲過濾
_help_display_global_filter;設定一個適用於整個收藏集/遊戲清單的全域遊戲過濾規則
_help_display_in_cycle;在切換「上一個顯示介面/下一個顯示介面」循環裡加入這個顯示介面
_help_display_in_menu;在主選單裡顯示這個顯示介面
_help_display_layout;設定這個顯示介面所要使用的畫面佈局
_help_display_layout_options;設定畫面佈局所提供的設定選項
_help_display_name;這個顯示介面的標題名稱
_help_display_romlist;設定這個顯示介面所要使用的收藏集/遊戲清單
_help_display_sel;設定顯示介面
_help_displays;設定遊戲清單/畫面佈局群組 (又稱顯示介面)，用於在 Attract-Mode 裡循環顯示。
_help_displays_menu;設定主選單的設定選項
_help_displays_menu_exit;設定結束項目是否顯示在主選單
_help_displays_menu_layout;設定主選單所使用的畫面佈局 (設為「Default」為使用程式內建的主選單)
_help_displays_menu_prompt;主選單的提示訊息 (例: 選擇系統)
_help_emu_add;新增一個新的模擬器
_help_emu_args;這個模擬器的命令行參數 (可用的變數: [name]、[romext]、[rompath]、[emulator]、[romfilename]、[system]、[systemn]、[workdir]、[nothing]，以及任何有效的其它標記，詳情請參考 layout 文件)
_help_emu_delete;刪除這個模擬器項目
_help_emu_executable;這個模擬器的完整路徑及檔名 (可用的變數: $HOME = 用戶主目錄、$PROGDIR = Attract-Mode 程式目錄，Windows 系統額外還有符合系統環境變數的 %SYSTEMROOT% 及 %PROGRAMFILES% 可以使用)
_help_emu_exit_hotkey;設定一個全域熱鍵來結束模擬器 (當這個熱鍵按下時，Attract-Mode 將會終結這個模擬器處理程序)
_help_emu_gen_romlist;使用設定裡的遊戲檔路徑、副檔名、XML 及附加匯入檔案裡的資料來產生遊戲清單
_help_emu_import_extras;設定產生遊戲清單時所要使用的附加檔案路徑。 支援的檔案: catver.ini (遊戲分類)、nplayers.ini (玩家人數)、series.ini (系列遊戲)、language.ini (遊戲語言) 及 mame.xml (多個檔案路徑可用分號間隔)
_help_emu_info_source;使用 "listxml" 為 mame -listxml 輸出、"listsoftware" 為 mame/mess -listsoftware 輸出、"thegamesdb.net" 為從 thegamesdb.net 搜刮資料、"steam" 為從 steam 安裝中讀取、"scummvm" 為當模擬器為 scummvm 時使用 (使用 "listsoftware" 及 "thegamesdb.net" 必須正確設定系統識別名稱)
_help_emu_nb_mode_wait;若此值非 0，這個模擬器將會執行在非阻塞模式 (Attract-Mode 將會等待至所設定的秒數後才將視窗焦點從模擬器轉回並喚醒 Attract-Mode，這對於正確啟動 Steam 之類的程序是必要的，在你了解它的作用前請保持為 0)
_help_emu_pause_hotkey;設定一個全域熱鍵來暫停模擬器 (當這個熱鍵按下時，Attract-Mode 將會暫停這個模擬器處理程序並返回前導，這個模擬器處理程序可在再次選擇同樣遊戲後繼續)
_help_emu_romext;這個模擬器的遊戲副檔名 (例: .zip)，若遊戲在個別的子目錄時請設為 "<DIR>" (多個副檔名可用分號間隔)
_help_emu_rompath;這個模擬器的遊戲檔存放路徑 (多個路徑可用分號間隔)
_help_emu_scrape_artwork;從網路搜刮這個模擬器所沒有的遊戲插圖
_help_emu_sel;設定模擬器
_help_emu_sel_gen_romlist;為多個模擬器產生收藏集/遊戲清單
_help_emu_system;這個模擬器的系統識別名稱 (多個識別名稱可用分號間隔)
_help_emu_workdir;這個模擬器的工作目錄 (Attract-Mode 會將工作目錄作為執行模擬器的開始位置，一些在這個前導裡以相對路徑所設定的資源路徑也都會以此工作目錄為開始位置)
_help_emulators;設定模擬器設定選項
_help_exit_command;設定當結束 Attract-Mode 時所要執行的命令 [例: "sudo shutdown"]
_help_exit_message;設定當結束 Attract-Mode 時所要顯示的訊息 [例: "關機"]
_help_filter_add_exception;新增例外條件至這個遊戲過濾 (若遊戲符合這個例外條件且未被先前的規則過濾到，它將會列在這個遊戲過濾裡)
_help_filter_add_rule;新增一個規則至這個遊戲過濾 (遊戲必須符合所有過濾規則或例外條件才會列在這個遊戲過濾)
_help_filter_delete;刪除這個遊戲過濾
_help_filter_exception;設定這個遊戲過濾的例外條件 (若遊戲符合這個例外條件，它將會列在這個遊戲過濾裡)
_help_filter_list_limit;設為 0 為無限制，若你想限制排序清單的數量請設為 0 之外的數值 (例: "10" 將會取得前 10 個項目，"-25" 將會取得最後 25 個項目)
_help_filter_name;這個遊戲過濾的名稱
_help_filter_rule;設定這個遊戲過濾的規則 (遊戲必須符合所有過濾規則或例外條件才會列在這個遊戲過濾)
_help_filter_sort_by;設定用來排序收藏集/遊戲清單的遊戲資訊屬性 (設為「不排序」則保持收藏集/遊戲清單原始的排序順序)
_help_filter_wrap_mode;設定當使用「下一個遊戲過濾」或「上一個遊戲過濾」切換至底時所要執行的動作
_help_font_path;設定字型檔案存放目錄，Attract-Mode 將會遞迴搜尋這些目錄以找到指定的字型 (多個目錄可用分號間隔)
_help_game_custom_args;設定此項目將會替這個遊戲覆寫預設的命令參數，設為 [nothing] 則會覆寫為無參數 (可用的變數: [name]、[romext]、[rompath]、[emulator]、[romfilename]、[system]、[systemn])
_help_game_custom_executable;設定此項目將會替這個遊戲覆寫預設的執行檔
_help_game_delete;從遊戲清單刪除這個遊戲
_help_game_edit;編輯這個遊戲的資訊
_help_game_overview;編輯遊戲簡介
_help_generator_opt;設定要為哪些模擬器建立遊戲清單
_help_generator_build;開始為已選擇的模擬器建立遊戲清單
_help_hide_brackets;顯示遊戲標題時隱藏括號內容
_help_image_cache_mbytes;設定 Attract-Mode 內部影像快取最大值大小 (以 MB 為單位)
_help_input_action;目前所設定的 Attract-Mode 操作控制
_help_input_add;新增一個輸入映射給這個操作控制使用
_help_input_default_action;設定這個操作控制的預設操作功能
_help_input_delete;移除這個輸入映射
_help_intro;設定啟動視訊
_help_joystick_map;指定電腦的搖桿裝置在 Attract-Mode 裡的搖桿順序 (例: 你可以強制這個前導永遠使用 'Microsoft X-Box 360 pad' 作為搖桿 0)
_help_joystick_threshold;這個設定用來定位搖桿移動的靈敏度，數值從 1 到 100 (100 為最大值)。
_help_language;選擇 Attract-Mode 使用者介面所要使用的語言
_help_layout_file;一些畫面佈局主題提供多個 layout*.nut 檔案，須選擇要使用的畫面佈局檔案。
_help_misc;設定一般設定
_help_mouse_threshold;這個設定用來定位滑鼠移動的靈敏度，數值從 1 到 100 (100 為最大值)。
_help_multiple_monitors;為 Attract-Mode 啟用多螢幕支援 (設定為「否」可能減少執行遊戲時的螢幕閃爍問題)
_help_plugin_command;這個外掛所關聯的外部執行檔
_help_plugin_enabled;設定這個外掛是否要啟用
_help_plugin_sel;設定外掛
_help_plugins;設定目前存在的外掛
_help_rule_comp;這個過濾規則的比對方式
_help_rule_delete;刪除這個過濾規則
_help_rule_target;設定所要過濾的遊戲資訊內容
_help_rule_value;設定所要過濾的正規表達式過濾值 (例: 若過濾目標為「年份」且比對方式為「等於」，過濾值為「1984」時將會比對所有年份為 1984 的遊戲、「198.」將會比對所有 80 年代的遊戲、「(198.)|(199.)」將會比對所有 80 及 90 年代的遊戲)
_help_scrape_fanart;設定是否要搜刮玩家自製插圖
_help_scrape_flyers;設定是否要搜刮宣傳/盒裝插圖
_help_scrape_marquees;設定是否要搜刮遊戲招牌插圖
_help_scrape_snaps;設定是否要搜刮遊戲捉圖
_help_scrape_vids;設定是否要搜刮遊戲視訊
_help_scrape_wheels;設定是否要搜刮遊戲圖標 (輪播插圖)
_help_scraper;設定插圖搜刮設定選項
_help_screen_saver;設定螢幕保護
_help_screen_saver_timeout;設定切換至螢幕保護模式前的等待秒數 (0 為停用)
_help_shortcut_label_edit;編輯這個捷徑的標題名稱
_help_shortcut_target_edit;編輯這個捷徑的目標顯示介面
_help_shortcut_artwork_name_edit;提供要與此捷徑關聯的插圖名稱 (Attract-Modend 將會在顯示這個捷徑時嘗試使用這個名稱載入插圖資源)
_help_shortcut_delete;從遊戲清單刪除這個捷徑
_help_sound;設定聲音音量、操作事件聲音對映及環境音效
_help_sound_sel;分配這個操作事件所要使用的音訊檔案
_help_startup_mode;設定 Attract-Mode 啟動時所要顯示的選單項目
_help_track_usage;設定 Attract-Mode 是否要記錄使用狀況 (每個遊戲的遊戲時間及遊戲次數)
_help_video_decoder;設定視訊播放時所要使用的解碼器 (若存在多個解碼器)
_help_volume;音量值為 0 到 100 (0 為靜音)
_help_window_mode;設定 Attract-Mode 所要使用的顯示模式
_help_hide_console;啟動時隱藏主控台視窗 (註: 這僅在從 Windows 介面啟動 Attract-Mode 時能正常運作，若從命令提示字元視窗啟動 (例: 批次檔)，這個處理程式將始終附加並輸出到這個命令提示字元視窗)
_help_power_saving;僅在需要時才重新繪製螢幕進而達成省電 (可能造成一些畫面佈局動畫卡頓或在 Linux 系統畫面凍結)
_sort_regexp;^(Vs\. The |The |Vs\. )

#
# Extra strings provided by translation
#
'Displays Menu' Options;主選單選項
Series;系列遊戲
Region;遊戲區域
Rating;遊戲評比
Back (Exit);返回 (結束)
Up (Previous Game);↑ (上一個遊戲)
Down (Next Game);↓ (下一個遊戲)
Left (Previous Page);← (上一頁)
Right (Next Page);→ (下一頁)

#@DONE_TRANSLATED